// Auto-generated from cards.js split. Module: Commercial Law
export const commercialLawCards = [
  {
    "id": "1",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "corporate personality",
      "veil"
    ],
    "crossCutting": false,
    "front": "What is the principle established in Salomon v A Salomon & Co Ltd [1897]?",
    "back": "A company is a legal entity distinct from its members. The corporate veil separates the company's liabilities from those of its shareholders, even where one person holds virtually all shares.",
    "details": "House of Lords unanimously reversed the CA. Lord Macnaghten: the company is at law a different person altogether from the subscribers. Key exceptions: fraud, façade/sham, agency, group enterprises (Adams v Cape Industries).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "13",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "sale of goods",
      "implied terms"
    ],
    "crossCutting": false,
    "front": "What are the key implied terms in a contract for the sale of goods under the Sale of Goods Act 1979?",
    "back": "S.12: right to sell. S.13: goods correspond to description. S.14(2): satisfactory quality. S.14(3): fitness for particular purpose. S.15: sale by sample. These terms cannot be excluded in consumer contracts (CRA 2015).",
    "details": "Satisfactory quality (s.14(2)): assessed by appearance, freedom from minor defects, safety, durability. A reasonable person test. Fitness for purpose (s.14(3)): buyer must make known the particular purpose; reliance must be reasonable.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "commercial-nemo-dat",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "nemo dat",
      "title",
      "sale of goods",
      "exceptions",
      "sga 1979"
    ],
    "crossCutting": false,
    "front": "State the nemo dat rule and its main exceptions under the Sale of Goods Act 1979.",
    "back": "Nemo dat quod non habet — no one can transfer better title than they have (s21 SGA 1979). Exceptions: (1) estoppel (s21(1)); (2) sale by mercantile agent (Factors Act 1889 s2); (3) sale under voidable title (s23); (4) sale by seller in possession after sale (s24); (5) sale by buyer in possession (s25); (6) sale under court order.",
    "details": "The rule protects original owners but exceptions protect bona fide purchasers for value. S23: if the original sale was voidable (e.g. for fraudulent misrepresentation) and the rogue re-sells before the contract is avoided, a bona fide purchaser gets good title (Ingram v Little [1961] contrast with Lewis v Averay [1972]). S25 buyer in possession: the buyer who has received delivery can pass good title to a bona fide third party (Newtons of Wembley v Williams [1965]). The Factors Act s2 protects purchasers who buy from a mercantile agent acting with the owner's consent and in the ordinary course of business.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "commercial-apparent-authority",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "agency",
      "apparent authority",
      "ostensible authority",
      "Freeman Lockyer",
      "principal"
    ],
    "crossCutting": false,
    "front": "What is apparent (ostensible) authority in agency law and what are its requirements?",
    "back": "Apparent authority arises where the principal represents to a third party that the agent has authority, even though actual authority is absent or exceeded. Requirements (Freeman & Lockyer v Buckhurst Park Properties [1964]): (1) representation by the principal; (2) reliance by the third party; (3) consequent alteration of position. The principal is bound.",
    "details": "Freeman & Lockyer: a managing director who had never been formally appointed was allowed to contract on behalf of a company — the board's conduct created the representation. Contrast actual authority (express or implied by conduct/position). Watteau v Fenwick [1893] is controversial: a manager prohibited from buying certain goods bound his undisclosed principal because those goods fell within the usual authority of a manager — critics argue this exceeds apparent authority and is better explained as usual authority. Apparent authority is important in commercial contexts where principals are undisclosed.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "commercial-romalpa-retention-of-title",
    "type": "case",
    "module": "Commercial Law",
    "tags": [
      "retention of title",
      "romalpa",
      "reservation of title",
      "insolvency",
      "sga s19"
    ],
    "crossCutting": false,
    "front": "What did Aluminium Industrie Vaassen v Romalpa Aluminium [1976] establish about retention of title clauses?",
    "back": "A seller may retain legal title in goods until the purchase price is paid (s19 SGA 1979 allows reservation of title). Where goods are identifiable and unmixed, an effective Romalpa clause allows the seller to recover them in the buyer's insolvency, ranking ahead of unsecured creditors.",
    "details": "The full 'Romalpa clause' in the case also claimed proceeds of sub-sales held on trust — a claim that later courts restricted. Simple retention of title (title remains until paid) is routinely upheld. Extended clauses claiming products after mixing or sub-sale proceeds have generally failed: Borden (UK) v Scottish Timber [1981] — resin mixed into chipboard lost identity; Re Peachdart [1984] — leather made into handbags converted the goods. In practice, simple clauses are commonplace in commercial supply contracts as a credit protection device.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "commercial-passing-property-risk",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "property",
      "risk",
      "sale of goods",
      "sga 1979",
      "specific goods",
      "unascertained"
    ],
    "crossCutting": false,
    "front": "When does property (and hence risk) pass in a contract for the sale of goods?",
    "back": "Property passes when the parties intend it to pass (ss17–18 SGA 1979). For specific goods the statutory rules in s18 apply by default (Rule 1: unconditional contract for specific goods — property passes at contract). Risk prima facie passes with property (s20), but delivery delay by one party puts risk on the delaying party.",
    "details": "S18 Rules: Rule 1 — specific goods in deliverable state, property passes on contract. Rule 2 — seller must do something to put goods in deliverable state, property passes when done and buyer notified. Rule 5 — unascertained goods: property passes when goods are unconditionally appropriated (with assent). Practical importance: the party with property bears the risk of accidental damage. Retention of title clauses defer the passage of property. Cf Re Goldcorp Exchange [1995] — unascertained goods from a bulk cannot pass property until ascertained, leaving customers as unsecured creditors.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "commercial-bills-of-lading",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "bills of lading",
      "carriage of goods by sea",
      "document of title",
      "Carriage of Goods by Sea Act 1992"
    ],
    "crossCutting": false,
    "front": "What are the three functions of a bill of lading?",
    "back": "A bill of lading is: (1) a receipt for goods shipped, acknowledging the condition and quantity of goods on loading; (2) evidence of (or the actual) contract of carriage between shipper and carrier; (3) a document of title — endorsement and delivery transfers constructive possession and, under the Carriage of Goods by Sea Act 1992, contractual rights.",
    "details": "As a document of title, only a negotiable (order) bill transfers property when endorsed in blank or to order — making it essential in CIF and FOB international sale contracts where goods are sold 'afloat'. The Carriage of Goods by Sea Act 1992 replaced the Bills of Lading Act 1855 and transfers contractual rights to a lawful holder who becomes the holder by endorsement. A sea waybill is not a document of title and is used for non-negotiable consignments. The Hague-Visby Rules (Carriage of Goods by Sea Act 1971) imply minimum carrier obligations and limit liability.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-sga-title-s12",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "sale of goods",
      "s12 SGA",
      "title",
      "right to sell"
    ],
    "crossCutting": false,
    "front": "What is the implied term as to title under s.12 Sale of Goods Act 1979?",
    "back": "S.12(1) implies a condition that the seller has the right to sell the goods (or will have at the time property is to pass). S.12(2) implies warranties that the goods are free from undisclosed encumbrances and that the buyer will enjoy quiet possession. This term cannot be excluded in any contract (s.6(1) UCTA 1977 / s.31 CRA 2015 for consumer contracts).",
    "details": "Rowland v Divall [1923]: a buyer of a stolen car could recover the full purchase price despite using the car for months — there had been a total failure of consideration because the seller had no right to sell. Niblett v Confectioners' Materials [1921]: a breach of s.12 where labels infringed a third party's trademark. The buyer's right to reject is not lost by lapse of time under s.12 (unlike ss.13-15).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-sga-satisfactory-quality",
    "type": "application",
    "module": "Commercial Law",
    "tags": [
      "satisfactory quality",
      "s14(2) SGA",
      "reasonable person"
    ],
    "crossCutting": false,
    "front": "A business buys a new commercial printer that breaks down after 2 weeks of normal use. Can the buyer rely on the implied term of satisfactory quality?",
    "back": "Likely yes. Under s.14(2) SGA 1979, goods supplied under a sale in the course of business must be of satisfactory quality. Quality includes fitness for common purpose, freedom from minor defects, appearance, safety, and durability (s.14(2B)). A new printer that fails after only 2 weeks of normal use would fail the reasonable person test — it is not of the standard a reasonable person would regard as satisfactory.",
    "details": "The assessment is objective. Factors: description, price, and all other relevant circumstances (s.14(2A)). The buyer cannot rely on s.14(2) for defects specifically drawn to their attention before the contract (s.14(2C)(a)), or defects which ought to have been revealed by examination where the buyer examined the goods (s.14(2C)(b)). Remedies: short-term right to reject (s.22 CRA 2015 for consumers); or accept and claim damages. In B2B: right to reject under s.35 SGA unless acceptance has occurred.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-passing-of-property",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "passing of property",
      "risk",
      "s17-18 SGA",
      "intention"
    ],
    "crossCutting": false,
    "front": "When does property (ownership) pass from seller to buyer under the SGA 1979?",
    "back": "For specific goods: property passes when the parties intend it to pass (s.17). If no intention appears, s.18 provides default rules: Rule 1 — in an unconditional contract for specific goods in a deliverable state, property passes at the time of the contract. Rule 5 — for unascertained goods, property passes when goods matching the description are unconditionally appropriated to the contract with the assent of both parties. Risk passes with property (s.20).",
    "details": "S.18 Rules 2-4 deal with goods requiring weighing, testing, or approval. The 'nemo dat quod non habet' rule (s.21) means a buyer gets no better title than the seller had — subject to exceptions (market overt (abolished), voidable title (s.23), seller/buyer in possession (ss.24-25), agency). Retention of title (Romalpa) clauses: the seller retains property until payment — effective if properly drafted (Aluminium Industrie Vaassen v Romalpa [1976]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-remedies-breach-sga",
    "type": "distinction",
    "module": "Commercial Law",
    "tags": [
      "remedies",
      "rejection",
      "damages",
      "SGA 1979",
      "buyer's remedies"
    ],
    "crossCutting": false,
    "front": "What remedies does a buyer have for breach of a sale of goods contract?",
    "back": "The buyer may: (1) reject the goods and terminate the contract — available for breach of condition (ss.13-15 terms) unless the right is lost through acceptance (s.35); (2) claim damages for non-delivery (s.51) or for breach of warranty (s.53) — the measure is prima facie the difference between the value of the goods as delivered and their value as warranted; (3) sue for specific performance of the contract (s.52) — available only for specific or ascertained goods at the court's discretion.",
    "details": "Acceptance (s.35) occurs when the buyer: (a) intimates acceptance, (b) acts inconsistently with the seller's ownership (but this is now subject to a right to examine — s.35(2)), or (c) retains the goods beyond a reasonable time. In consumer contracts, the CRA 2015 provides additional remedies: short-term right to reject (30 days), right to repair/replacement (s.23), right to price reduction or final right to reject (s.24). Damages for consequential loss are available per ordinary contractual principles.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-agency-authority",
    "type": "distinction",
    "module": "Commercial Law",
    "tags": [
      "agency",
      "actual authority",
      "apparent authority",
      "Watteau v Fenwick"
    ],
    "crossCutting": false,
    "front": "Distinguish actual authority from apparent (ostensible) authority in agency law.",
    "back": "Actual authority: the authority the principal has expressly or impliedly conferred on the agent. Express = stated in words. Implied = reasonably incidental to express authority or customary in the trade (Hely-Hutchinson v Brayhead [1968]). Apparent authority: the authority the agent appears to have to a reasonable third party, based on a representation by the principal — even if the agent's actual authority has been restricted (Freeman & Lockyer v Buckhurst Park [1964]).",
    "details": "Requirements for apparent authority (Diplock LJ in Freeman & Lockyer): (1) a representation by the principal (or someone with authority) that the agent has authority, (2) reliance by the third party on the representation, (3) alteration of the third party's position. Watteau v Fenwick [1893] — 'usual authority' of an undisclosed principal's agent: the principal can be bound by acts within the agent's usual authority even if the third party did not know of the principal's existence. This doctrine is controversial.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-undisclosed-principal",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "undisclosed principal",
      "agency",
      "third party rights"
    ],
    "crossCutting": false,
    "front": "What is the undisclosed principal doctrine?",
    "back": "An undisclosed principal is one whose existence is not revealed to the third party — the agent contracts as if on their own behalf. The principal can intervene and enforce the contract against the third party, and the third party can enforce against the principal once discovered. However, the third party may elect to hold either the agent or the principal liable (but not both). The principal cannot intervene where the contract is personal to the agent.",
    "details": "Said v Butt [1920]: the undisclosed principal cannot enforce a contract where the identity of the contracting party was material (here, a theatre ticket sold to a named buyer who was persona non grata). Sui Northern Gas v Nestle [2018]: the undisclosed principal can only enforce the contract as actually made — they cannot expand its terms. Criticism: the doctrine contradicts privity and consent-based theory of contract.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-cif-fob",
    "type": "distinction",
    "module": "Commercial Law",
    "tags": [
      "CIF",
      "FOB",
      "international trade",
      "Incoterms"
    ],
    "crossCutting": false,
    "front": "Distinguish CIF and FOB contracts in international sale of goods.",
    "back": "CIF (Cost, Insurance, Freight): the seller's price includes the cost of goods, insurance, and freight to the named destination. The seller must procure a contract of carriage, insure the goods, and tender conforming shipping documents (bill of lading, insurance policy, commercial invoice). Property and risk pass on shipment, but the documents control the buyer's rights. FOB (Free on Board): the seller delivers by placing goods on board the vessel at the named port of shipment. The buyer arranges carriage and insurance. Risk passes when goods cross the ship's rail.",
    "details": "CIF: Biddell Brothers v E Clemens Horst [1911] — the buyer must pay against tender of conforming documents, even before inspecting the goods. The documents are the key — rejection is based on documents, not goods themselves (Kwei Tek Chao v British Traders [1954]). FOB variants: 'strict' FOB (buyer names the ship and books cargo space), 'classic' FOB (seller may arrange shipment as buyer's agent). Incoterms (ICC) standardise these terms in modern practice.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-bill-of-lading",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "bill of lading",
      "document of title",
      "international trade"
    ],
    "crossCutting": false,
    "front": "What are the three functions of a bill of lading?",
    "back": "(1) Receipt for goods shipped — evidence that the carrier has received the goods described. (2) Evidence of the contract of carriage — though not the contract itself (the contract is formed before the bill is issued). (3) Document of title — the holder can claim delivery of the goods and can transfer rights by endorsement and delivery of the bill. This function makes bills of lading central to international trade financing.",
    "details": "As a document of title, the bill of lading enables goods to be bought and sold while at sea — the buyer obtains constructive possession through the document. Under the Carriage of Goods by Sea Act 1992, the lawful holder of the bill acquires contractual rights against the carrier. 'Clean' bills (no clauses noting defects) are essential for letters of credit. Types: shipped bill, received-for-shipment bill, through bill. Electronic bills of lading are gaining acceptance.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-letter-of-credit",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "letter of credit",
      "autonomy principle",
      "UCP 600",
      "payment"
    ],
    "crossCutting": false,
    "front": "What is the 'autonomy principle' in documentary credits?",
    "back": "The autonomy (or independence) principle means that a letter of credit is independent of the underlying sale contract. The bank's obligation to pay is determined solely by whether conforming documents are presented — the bank must not look behind the documents to the goods themselves or to disputes between buyer and seller. This ensures the seller has certainty of payment.",
    "details": "Governed by UCP 600 (ICC Uniform Customs and Practice for Documentary Credits). The fraud exception is the only recognised exception to the autonomy principle: if the seller presents documents they know to be forged or fraudulent, the bank may refuse payment (United City Merchants v Royal Bank of Canada [1983]). The letter of credit involves at least three contracts: sale contract, issuing bank's engagement, and confirming bank's engagement. 'Strict compliance' — documents must strictly conform to the credit terms.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-insurance-insurable-interest",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "insurance",
      "insurable interest",
      "indemnity",
      "utmost good faith"
    ],
    "crossCutting": false,
    "front": "What is insurable interest and why is it required?",
    "back": "Insurable interest is a legal or equitable relationship to the subject matter of the insurance such that the insured would suffer financial loss from its damage or destruction. It is required to prevent insurance from becoming a mere wagering contract. Under the Marine Insurance Act 1906 s.5, a person has an insurable interest where they stand in a legal or equitable relation to the adventure, at risk of being prejudiced by its loss.",
    "details": "Life insurance: insurable interest must exist at the time the policy is taken out (not at the time of death). Property insurance: must exist at the time of loss. Lucena v Craufurd (1806) — mere expectation of benefit is insufficient. The Insurance Act 2015 reformed the duty of disclosure: the insured must make a 'fair presentation' of the risk (replacing the duty of utmost good faith under MIA 1906 s.17). Breach allows proportionate remedies rather than automatic avoidance.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-retention-of-title",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "retention of title",
      "Romalpa",
      "reservation of title",
      "insolvency"
    ],
    "crossCutting": false,
    "front": "What is a retention of title (Romalpa) clause and when is it effective?",
    "back": "A retention of title clause provides that the seller retains ownership of goods until the buyer has paid for them in full. If the buyer becomes insolvent before payment, the seller can recover their goods rather than ranking as an unsecured creditor. A 'simple' Romalpa clause (retaining title to the specific goods sold) is generally effective without registration.",
    "details": "Aluminium Industrie Vaassen v Romalpa Aluminium [1976]: the clause allowed the seller to recover unmixed aluminium foil. However, 'all monies' clauses (retention until all debts are paid) and clauses covering mixed goods or proceeds of sub-sales are more problematic — they may be recharacterised as charges requiring registration under the Companies Act 2006. Clough Mill v Martin [1985]: a simple clause was effective. Borden v Scottish Timber [1981]: clause failed for mixed goods.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-sga-description-s13",
    "type": "case",
    "module": "Commercial Law",
    "tags": [
      "sale by description",
      "s13 SGA",
      "implied term"
    ],
    "crossCutting": false,
    "front": "What does the implied term of correspondence with description under s.13 SGA 1979 require?",
    "back": "Under s.13, where goods are sold by description, they must correspond with the description. This is a condition — breach entitles rejection. The description includes words identifying the kind or type of goods (Re Moore & Co v Landauer [1921] — cans of fruit packed in cases of 24 instead of 30 were rejectable). Specific goods can also be sold by description if the buyer relies on the description (Grant v Australian Knitting Mills [1936]).",
    "details": "The strictness of s.13 has been tempered: Ashington Piggeries v Christopher Hill [1972] — not every descriptive word is part of the contractual description; the test is whether the description was influential in the sale. S.15A SGA (inserted by Sale and Supply of Goods Act 1994): in non-consumer contracts, a slight breach of ss.13-15 may be treated as a breach of warranty rather than condition if the breach is so slight that rejection would be unreasonable.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-nemo-dat-exceptions",
    "type": "principle",
    "module": "Commercial Law",
    "tags": [
      "nemo dat",
      "exception",
      "buyer in possession",
      "s25 SGA"
    ],
    "crossCutting": false,
    "front": "What are the main exceptions to the nemo dat quod non habet rule?",
    "back": "The nemo dat rule (s.21 SGA): a buyer acquires no better title than the seller had. Exceptions: (1) estoppel (s.21(1)) — owner's conduct precluded from denying seller's authority; (2) sale by agent with apparent authority; (3) s.23 — sale under voidable title (before avoidance); (4) s.24 — seller in possession after sale; (5) s.25 — buyer in possession before title passes; (6) Hire Purchase Act 1964 Part III — bona fide private purchaser of a motor vehicle on HP.",
    "details": "S.25: the buyer in possession must have possession with the seller's consent and must deliver or transfer to a good faith purchaser who takes without notice. Newtons of Wembley v Williams [1965]: s.25 applies where the buyer in possession sells in the ordinary course of business. The HP Act 1964 Part III protects only private purchasers, not trade buyers. These exceptions balance the original owner's rights against commercial certainty for innocent buyers.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-fitness-purpose-s14-3",
    "type": "application",
    "module": "Commercial Law",
    "tags": [
      "fitness for purpose",
      "s14(3) SGA",
      "particular purpose",
      "reliance"
    ],
    "crossCutting": false,
    "front": "A buyer tells a paint supplier they need paint suitable for coating a swimming pool. The supplier sells standard exterior paint, which peels off within weeks of contact with water. Can the buyer rely on s.14(3) SGA 1979?",
    "back": "Yes. Under s.14(3), where the buyer makes known a particular purpose for the goods (expressly or by implication), there is an implied condition that the goods are reasonably fit for that purpose, provided the buyer reasonably relied on the seller's skill and judgment. Here, the buyer expressly communicated the particular purpose (pool coating), and it was reasonable to rely on the supplier's expertise in recommending suitable paint.",
    "details": "Ashington Piggeries v Christopher Hill [1972]: where the purpose is made known, the seller is liable even if the unfitness is due to a latent defect they could not have discovered. Jewson v Boyhan [2003]: there must be reliance — if the buyer specifies an exact product, there may be no room for reliance on the seller's skill and judgment. The term under s.14(3) is a condition, so breach gives the right to reject (subject to s.15A in non-consumer sales).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-ucta-1977",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["UCTA 1977", "exclusion clauses", "reasonableness"],
    "crossCutting": false,
    "front": "How does the Unfair Contract Terms Act 1977 regulate exclusion and limitation clauses in commercial contracts?",
    "back": "UCTA 1977 controls exclusion clauses in business-to-business and business-to-consumer contracts. S.2(1): liability for death/personal injury caused by negligence cannot be excluded. S.2(2): liability for other loss from negligence can only be excluded if reasonable. S.3: in contracts on written standard terms, the party cannot exclude liability for breach or claim to render a substantially different performance unless reasonable. S.6: implied terms under SGA 1979 (ss.13-15) cannot be excluded in consumer contracts; in B2B contracts, only if reasonable.",
    "details": "The 'reasonableness test' (s.11 and Schedule 2): was the term fair and reasonable having regard to circumstances known or contemplated at the time of contracting. Factors: bargaining strength, inducements, whether the customer knew or ought to have known of the term, whether goods were specially manufactured. George Mitchell v Finney Lock Seeds [1983]: a £63 limitation clause for defective seed causing £61,000 crop loss was unreasonable. Photo Production v Securicor [1980]: the HL held exclusion clauses are valid where freely negotiated between commercial parties of equal bargaining power.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-rowland-v-divall",
    "type": "case",
    "module": "Commercial Law",
    "tags": ["s12 SGA", "title", "total failure of consideration"],
    "crossCutting": false,
    "front": "What did Rowland v Divall [1923] establish about breach of the implied term as to title?",
    "back": "A buyer who purchased a stolen car could recover the full purchase price despite having used the car for several months. The seller had no right to sell (breach of s.12(1) SGA 1979), constituting a total failure of consideration — the buyer had never received what they bargained for (ownership), only temporary possession.",
    "details": "The decision is commercially significant: even where the buyer has had extensive use of goods, if the seller lacked title the buyer can recover the entire price without any deduction for use. This is because the buyer's bargain was for ownership, not mere possession. The right to reject for breach of s.12 is not lost by acceptance (unlike ss.13-15). Niblett v Confectioners' Materials [1921]: labels infringing a third party's trademark also breached s.12.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-factors-act-1889",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["mercantile agent", "Factors Act 1889", "nemo dat exception"],
    "crossCutting": false,
    "front": "How does the Factors Act 1889 s.2 create an exception to the nemo dat rule?",
    "back": "Under s.2 Factors Act 1889, where a mercantile agent is in possession of goods or documents of title with the owner's consent, any sale, pledge, or disposition made by the agent in the ordinary course of business to a bona fide third party is as valid as if authorised by the owner. The third party acquires good title even though the agent acted without the owner's authority for that particular transaction.",
    "details": "Requirements: (1) the person must be a 'mercantile agent' — one who in the customary course of business has authority to sell, consign, or raise money on goods; (2) possession must be with the owner's consent; (3) the disposition must be in the ordinary course of business (Oppenheimer v Attenborough [1908]); (4) the third party must act in good faith without notice. Pearson v Rose & Young [1951]: consent to possession for a limited purpose (e.g. obtaining offers) is still consent under the Act.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-acceptance-s35",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["acceptance", "s35 SGA", "right to reject", "loss of right"],
    "crossCutting": false,
    "front": "When does a buyer lose the right to reject goods under s.35 SGA 1979?",
    "back": "A buyer is deemed to have accepted goods when: (1) they intimate acceptance to the seller (s.35(1)(a)); (2) they do an act inconsistent with the seller's ownership after delivery (s.35(1)(b)) — but only after a reasonable opportunity to examine (s.35(2)); or (3) they retain the goods beyond a reasonable time without rejecting (s.35(4)). Once accepted, the buyer loses the right to reject for breach of condition (ss.13-15) but retains a claim for damages.",
    "details": "The Sale and Supply of Goods Act 1994 reformed s.35 to give buyers a better chance to examine goods before acceptance is deemed. 'Reasonable time' depends on circumstances — Bernstein v Pamson Motors [1987] (3 weeks for a new car — criticised as too short). In consumer contracts, the CRA 2015 s.22 provides a 30-day short-term right to reject. S.15A SGA: in non-consumer contracts, a slight breach of ss.13-15 may be treated as a breach of warranty only, preventing rejection.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-united-city-merchants",
    "type": "case",
    "module": "Commercial Law",
    "tags": ["letter of credit", "fraud exception", "autonomy principle"],
    "crossCutting": false,
    "front": "What fraud exception to the autonomy principle did United City Merchants v Royal Bank of Canada [1983] establish?",
    "back": "Lord Diplock held that the only basis on which a bank may refuse to pay against conforming documents under a letter of credit is if the seller, to the bank's knowledge, is presenting documents that contain material misrepresentations of fact that the seller knows to be untrue (fraud). If the fraud is by a third party (e.g. the loading broker misdated the bill of lading) and the seller is innocent, the bank must still pay.",
    "details": "The autonomy principle means the bank deals in documents, not goods — it pays if the documents conform, regardless of disputes between buyer and seller about the underlying goods. The fraud exception is narrowly confined: the bank must have clear evidence of the beneficiary's fraud before the documents are presented. Mere suspicion is insufficient. Czarnikow-Rionda Sugar Trading v Standard Bank London [1999]: the threshold for invoking the fraud exception is high.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-hague-visby-rules",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["Hague-Visby Rules", "carriage of goods by sea", "carrier liability"],
    "crossCutting": false,
    "front": "What are the key obligations and defences of a carrier under the Hague-Visby Rules?",
    "back": "Under the Hague-Visby Rules (Carriage of Goods by Sea Act 1971): the carrier must (1) before and at the beginning of the voyage, exercise due diligence to make the ship seaworthy (Art III r.1); (2) properly and carefully load, handle, stow, carry, and discharge the goods (Art III r.2). Art IV r.2 provides a catalogue of defences including: (a) act or neglect of the master in navigation/management of the ship, (b) fire, (c) perils of the sea, (d) act of God, and others. Liability is limited per package or per kilogram.",
    "details": "The Rules apply compulsorily to outward shipments from contracting states involving a bill of lading (Art X). The carrier cannot contract out of the minimum obligations — any clause lessening liability below the Rules is null and void (Art III r.8). The time limit for suit is one year from delivery (Art III r.6). The navigation/management defence (Art IV r.2(a)) is unique to maritime law — it excuses the carrier for negligent navigation by the crew. The Maxine Footwear v Canadian Government Merchant Marine [1959] illustrates the seaworthiness duty.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-voidable-title-s23",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["voidable title", "s23 SGA", "void vs voidable"],
    "crossCutting": false,
    "front": "Distinguish void and voidable title and explain the operation of s.23 SGA 1979.",
    "back": "A void title (e.g. from a fundamental mistake as to identity — Cundy v Lindsay [1878]) transfers nothing: no subsequent buyer can obtain title. A voidable title (e.g. from fraudulent misrepresentation) is valid until avoided: under s.23 SGA 1979, a buyer who obtains goods under a voidable title can pass good title to a bona fide purchaser for value without notice, provided the original owner has not avoided the contract before the resale.",
    "details": "The distinction is critical where a rogue obtains goods by fraud and resells to an innocent third party. If the contract is void (mistake as to identity), the rogue never had title and the third party gets nothing. If merely voidable (fraud), the third party may get good title under s.23 if the contract was not yet avoided. Lewis v Averay [1972]: a face-to-face sale is voidable, not void — the seller intended to deal with the person present. Shogun Finance v Hudson [2004] (HL, 3-2): a hire-purchase agreement made by correspondence was void for mistake as to identity.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-cra-2015-consumer",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["Consumer Rights Act 2015", "consumer contracts", "remedies"],
    "crossCutting": false,
    "front": "What implied terms and remedies does the Consumer Rights Act 2015 provide for consumer sales contracts?",
    "back": "The CRA 2015 implies terms that goods must be: of satisfactory quality (s.9), fit for particular purpose (s.10), and as described (s.11). Consumer remedies: (1) short-term right to reject within 30 days (s.22); (2) right to repair or replacement (s.23); (3) if repair/replacement fails, right to a price reduction or final right to reject (s.24). These terms cannot be excluded or restricted (s.31).",
    "details": "The CRA 2015 replaced consumer provisions previously in the SGA 1979 and UCTA 1977 for consumer contracts. 'Consumer' = an individual acting for purposes wholly or mainly outside their business (s.2(3)). 'Trader' = a person acting for purposes relating to their business (s.2(2)). Digital content is separately covered (ss.33-47). Unfair terms in consumer contracts are assessed under Part 2 of the CRA (replacing the Unfair Terms in Consumer Contracts Regulations 1999). S.62: a term is unfair if it causes a significant imbalance to the consumer's detriment.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-directors-duties",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["directors duties", "Companies Act 2006", "fiduciary"],
    "crossCutting": false,
    "front": "What are the statutory duties of directors under the Companies Act 2006?",
    "back": "Directors owe duties to the company (s.170): s.171 — act within powers; s.172 — promote the success of the company for the benefit of members as a whole; s.173 — exercise independent judgment; s.174 — exercise reasonable care, skill and diligence; s.175 — avoid conflicts of interest; s.176 — not accept benefits from third parties; s.177 — declare interest in proposed transactions.",
    "details": "S.172 codifies the 'enlightened shareholder value' approach — directors must have regard to factors including long-term consequences, employee interests, business relationships, community and environment, maintaining reputation, and fairness between members. S.175 (conflicts) can be authorised by the board in private companies (s.175(5)). Remedies for breach: account of profits, equitable compensation, rescission of voidable contracts, injunction. These duties replaced the previous equitable fiduciary duties and are to be interpreted in accordance with the common law rules they replace (s.170(4)).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-piercing-veil",
    "type": "case",
    "module": "Commercial Law",
    "tags": ["corporate veil", "piercing", "Prest v Petrodel"],
    "crossCutting": false,
    "front": "When will the courts pierce the corporate veil after Prest v Petrodel Resources Ltd [2013]?",
    "back": "Lord Sumption held the corporate veil may be pierced only where a person is under an existing legal obligation or liability which they deliberately evade or frustrate by interposing a company under their control (the 'evasion principle'). The 'concealment principle' — where a company is used to conceal the true facts — does not require piercing; the court simply looks behind the corporate form to identify the real position. Piercing is a remedy of last resort.",
    "details": "In Prest, the husband owned properties through companies to defeat his wife's ancillary relief claim. The SC did not pierce the veil but held the properties were held on resulting trust for the husband. Adams v Cape Industries [1990] (CA): the veil will not be pierced merely because a subsidiary is used to minimise liability — the corporate group structure is legitimate. VTB Capital v Nutritek [2013]: the SC confirmed the narrow scope of piercing. The evasion principle requires: (1) a pre-existing obligation, (2) deliberate evasion by interposing the company, and (3) no other remedy available.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-minority-shareholder-s994",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["unfair prejudice", "s994 CA 2006", "minority shareholder"],
    "crossCutting": false,
    "front": "What remedy is available to a minority shareholder under s.994 Companies Act 2006?",
    "back": "S.994 allows a member to petition the court on the ground that the company's affairs are being or have been conducted in a manner that is unfairly prejudicial to the interests of members generally or some part of the members. The court has wide discretion under s.996 to grant relief, most commonly ordering the majority to buy the petitioner's shares at a fair value.",
    "details": "O'Neill v Phillips [1999] (HL): Lord Hoffmann held unfairness requires either breach of the terms on which the shareholder agreed to be associated with the company, or use of the rules in a manner that equity would regard as contrary to good faith. Re Saul D Harrison [1995]: the petition must identify conduct that is both unfair and prejudicial. Quasi-partnerships (small private companies based on mutual trust) attract wider protection — exclusion from management without justification may be unfairly prejudicial. The buy-out order is the standard remedy; the court usually values shares on a pro-rata basis without a minority discount.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-insurance-act-2015",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["Insurance Act 2015", "fair presentation", "disclosure"],
    "crossCutting": false,
    "front": "How did the Insurance Act 2015 reform the insured's duty of disclosure?",
    "back": "The Insurance Act 2015 replaced the duty of utmost good faith (s.17 Marine Insurance Act 1906) with a duty to make a 'fair presentation of the risk' (s.3). The insured must disclose every material circumstance they know or ought to know, or give the insurer sufficient information to put a prudent insurer on notice. If breached, the insurer's remedies are proportionate: if deliberate/reckless, the insurer may avoid and retain premiums; if neither, the remedy reflects what the insurer would have done had a fair presentation been made.",
    "details": "Under the old law (MIA 1906), any material non-disclosure entitled the insurer to avoid the contract entirely. The 2015 Act introduced proportionate remedies (Schedule 1): if the insurer would not have entered the contract at all, it may avoid and return premiums; if it would have entered on different terms, those terms are treated as applying; if it would have charged a higher premium, the claim is reduced proportionately. S.10 abolishes 'basis of the contract' clauses which converted all pre-contractual representations into warranties. S.11: breach of warranty suspends the insurer's liability but does not discharge it permanently if remedied.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-personal-property-security",
    "type": "distinction",
    "module": "Commercial Law",
    "tags": ["pledge", "lien", "charge", "security interest"],
    "crossCutting": false,
    "front": "Distinguish the main forms of security over personal property: pledge, lien, and charge.",
    "back": "Pledge: the debtor delivers possession of goods to the creditor as security; the creditor has a special property in the goods and a power of sale on default (Re Hardwick [1886]). Lien: the right to retain possession of goods until a debt is paid — possessory liens arise by operation of law (common law or statute). Charge: a security interest that does not require transfer of possession or title — the chargor retains the property but grants the chargee a right over it; charges over company property must be registered (s.859A CA 2006) or be void against liquidators and creditors.",
    "details": "Fixed charge: attaches to specific identified property — the chargor cannot deal with it without consent. Floating charge: attaches to a class of present and future assets — the chargor can deal with the assets in the ordinary course of business until crystallisation (Re Yorkshire Woolcombers [1903]). On crystallisation, a floating charge becomes fixed and attaches to the assets then owned. Priority: fixed charges rank ahead of floating charges. Re Spectrum Plus [2005]: an account described as fixed charge was recharacterised as floating because the company could freely draw on it.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-incoterms-trade",
    "type": "principle",
    "module": "Commercial Law",
    "tags": ["Incoterms", "international trade", "risk allocation"],
    "crossCutting": false,
    "front": "What are Incoterms and how do they allocate risk and cost in international sales?",
    "back": "Incoterms (International Commercial Terms, published by the ICC, latest edition 2020) are standardised trade terms that define the obligations, risks, and costs between buyer and seller in international sale contracts. They specify: when risk of loss/damage passes, who arranges and pays for transport, insurance, customs clearance, and delivery. Examples: EXW (Ex Works — buyer bears all risk from seller's premises), FOB (Free on Board — risk passes when goods are on the vessel), CIF (Cost, Insurance, Freight — seller arranges carriage and insurance to destination port, but risk passes on shipment).",
    "details": "Incoterms are incorporated by reference in the sale contract (e.g. 'CIF Shanghai Incoterms 2020'). They do not constitute a complete contract — they do not deal with transfer of property, price, or payment terms. 11 rules in Incoterms 2020, divided into rules for any mode of transport (EXW, FCA, CPT, CIP, DAP, DPU, DDP) and rules for sea/inland waterway only (FAS, FOB, CFR, CIF). CIF and FOB remain the most commonly used in commodity trading. Incoterms are not law — they are contractual terms that apply only if incorporated by the parties.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "comm-re-spectrum-plus",
    "type": "case",
    "module": "Commercial Law",
    "tags": ["fixed charge", "floating charge", "recharacterisation", "book debts"],
    "crossCutting": false,
    "front": "What did Re Spectrum Plus Ltd [2005] decide about the characterisation of charges over book debts?",
    "back": "The House of Lords held that a charge over book debts described as 'fixed' was in reality a floating charge because the company was free to use the proceeds of collected debts in the ordinary course of business without the bank's consent. The label attached by the parties is not determinative — the court examines the substance of the arrangement, particularly the degree of control the chargee exercises over the charged assets.",
    "details": "The key indicator distinguishing fixed from floating charges is control: if the chargor can deal with the assets without the chargee's permission, the charge is floating regardless of its label. Agnew v Commissioner of Inland Revenue [2001] (PC): Lord Millett — a charge over uncollected book debts can be fixed, but once collected and paid into an account the chargor can freely draw on, the charge over the proceeds is floating. Re Yorkshire Woolcombers [1903]: Romer LJ's three characteristics of a floating charge — (1) class of assets present and future, (2) changing from time to time, (3) freedom to deal until crystallisation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
