// Auto-generated from cards.js split. Module: Contract Law
export const contractLawCards = [
  {
    "id": "3",
    "type": "application",
    "module": "Contract Law",
    "tags": [
      "offer",
      "invitation to treat"
    ],
    "crossCutting": false,
    "front": "A hospital gift shop displays hand sanitiser with a price tag of $10. A visitor picks one up and takes it to the counter. The cashier says 'Sorry, we're not selling those anymore.' Has a contract been formed?",
    "back": "No contract formed. Under Pharmaceutical Society of GB v Boots Cash Chemists [1953], a display of goods with a price tag is an invitation to treat, not an offer. The customer makes the offer at the counter; the cashier is free to accept or reject.",
    "details": "Fisher v Bell [1961] confirms for shop window displays. Rationale: shopkeepers must retain control over whom they contract with and in what quantities.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "8",
    "type": "distinction",
    "module": "Contract Law",
    "tags": [
      "misrepresentation",
      "terms vs representations"
    ],
    "crossCutting": false,
    "front": "Distinguish a term from a representation in contract law. Why does it matter?",
    "back": "A term is a contractual promise — breach gives contractual remedies. A representation is a pre-contractual statement inducing entry — if false, remedy lies in misrepresentation. The distinction determines which legal regime and remedies apply.",
    "details": "Factors: timing, importance, whether followed up in writing, relative expertise. Bannerman v White (1861) — term. Oscar Chess v Williams [1957] — representation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-postal-rule",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "offer",
      "acceptance",
      "postal rule",
      "Adams v Lindsell",
      "instantaneous communications"
    ],
    "crossCutting": false,
    "front": "State the postal rule for acceptance and its limitations.",
    "back": "Acceptance takes effect when a letter is posted (Adams v Lindsell [1818]), not when received by the offeror. The rule applies to reasonably anticipated use of post. It does not apply to instantaneous communications (telex — Entores v Miles Far East Corp [1955]; fax/email — the offeror's system governs receipt time).",
    "details": "The postal rule is an exception to the general principle that acceptance must be communicated to the offeror. Rationale: protect offerees from offerors who revoke while the letter is in transit. Limits: (1) the offeror can exclude it expressly ('acceptance effective only on receipt'); (2) it requires posting to be the expected or contemplated means; (3) a crossed or wrongly addressed letter may not activate it (Re London & Northern Bank [1900]). Revocation of an offer must be communicated before acceptance is posted; once posted, the offeree can enforce the contract even if the revocation arrives before the letter of acceptance (Byrne v Van Tienhoven [1880]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-consideration-past",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "consideration",
      "past consideration",
      "Re McArdle",
      "Lampleigh v Brathwait",
      "sufficiency"
    ],
    "crossCutting": false,
    "front": "What is the rule on past consideration and what is the exception?",
    "back": "Past consideration is no consideration — an act already performed before a promise is made cannot support that promise (Re McArdle [1951]). Exception (Lampleigh v Brathwait principle): past acts may constitute good consideration if (1) done at the promisor's request; (2) payment was understood to be forthcoming; and (3) the subsequent promise merely fixes the amount (Pao On v Lau Yiu Long [1980]).",
    "details": "Re McArdle: improvements to a house made before a promise to pay for them was made — the promise was unenforceable (past consideration). Lampleigh v Brathwait [1615]: the defendant asked the claimant to obtain a royal pardon; after the claimant succeeded, the defendant promised £100 — enforceable because the original act was done at request with implied promise of remuneration. Pao On v Lau Yiu Long confirmed this 'implied assumpsit' exception. Consideration must also be sufficient (must have value in the eyes of the law) but need not be adequate (the law does not police the fairness of bargains: Chappell v Nestlé [1960] — wrappers as consideration).",
    "related": [
      "contract-consideration-def",
      "contract-promissory-estoppel",
      "contract-williams-roffey"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-promissory-estoppel",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "promissory estoppel",
      "High Trees",
      "Central London Property Trust",
      "waiver",
      "shield not sword"
    ],
    "crossCutting": false,
    "front": "What is the doctrine of promissory estoppel and what are its requirements?",
    "back": "Promissory estoppel prevents a promisee from enforcing strict legal rights where they made a clear and unequivocal promise not to do so, the promisee relied on that promise, and it would be inequitable to allow the promisor to resile. Established in Central London Property Trust v High Trees House [1947] (Denning J).",
    "details": "High Trees: landlord reduced rent during WWII; Denning held the promise was binding for the wartime period via estoppel, even without consideration. Requirements: (1) pre-existing legal relationship; (2) clear promise or representation; (3) reliance (need not be detrimental — WJ Alan v El Nasr [1972]); (4) inequitable to resile. Critically: promissory estoppel operates as a shield not a sword (Combe v Combe [1951]) — it is a defence against enforcing strict rights, not an independent cause of action. The promise is generally suspensory (rights revive on reasonable notice): Tool Metal Manufacturing v Tungsten Electric [1955]. In contrast, Australian courts (Waltons Stores v Maher [1988]) have developed estoppel as a sword.",
    "related": [
      "contract-consideration-def",
      "contract-consideration-past",
      "contract-promissory-estoppel-requirements",
      "property-proprietary-estoppel"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-privity-crtpa1999",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "privity",
      "third party",
      "Contracts (Rights of Third Parties) Act 1999",
      "Tweddle v Atkinson"
    ],
    "crossCutting": false,
    "front": "What is the doctrine of privity of contract and how has it been modified by statute?",
    "back": "Only a party to a contract can sue or be sued on it (Tweddle v Atkinson [1861]; Dunlop Pneumatic Tyre Co v Selfridge [1915]). The Contracts (Rights of Third Parties) Act 1999 (CRTPA) allows a third party to enforce a contractual term if (a) the contract expressly provides so, or (b) the term purports to confer a benefit on the third party (unless the parties did not intend it to be enforceable by them).",
    "details": "Before 1999, common law had developed circumvention devices: agency, assignment, collateral contracts, tort duties (Donoghue). The CRTPA s1 allows the third party to enforce a term if identified by name, class, or description. The promisor can raise defences against the third party that it could have raised against the promisee. The third party's right is not dependent on being named in the contract — Beswick v Beswick [1968] (widow had no personal contract right but could enforce in her capacity as administratrix) would now be resolved under the Act. The Act does not allow the third party to impose obligations on a contract they are not party to.",
    "related": [
      "2",
      "contract-privity-exception",
      "contract-consideration-def"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-misrepresentation-types",
    "type": "distinction",
    "module": "Contract Law",
    "tags": [
      "misrepresentation",
      "fraudulent",
      "negligent",
      "innocent",
      "Misrepresentation Act 1967",
      "rescission"
    ],
    "crossCutting": false,
    "front": "Distinguish the three types of misrepresentation and the remedies available for each.",
    "back": "Fraudulent misrepresentation (Derry v Peek [1889]): knowingly false, or without belief in truth, or recklessly — remedies: rescission + tortious damages (all loss). Negligent misrepresentation (s2(1) Misrepresentation Act 1967): no reasonable grounds for belief — same remedies as fraud, burden on representor to disprove negligence. Innocent misrepresentation (s2(2) MA 1967): reasonable grounds for belief — rescission only, or court discretion to award damages in lieu.",
    "details": "Rescission is the primary remedy: it unwinds the contract as if it had never been made. It may be barred by: lapse of time; affirmation; impossibility of restitution; third party rights. Under s2(1) MA 1967, the defendant is liable in damages unless they prove they had reasonable grounds to believe the statement was true (a reverse burden). Negligent misrepresentation under s2(1) awards damages on the fraudulent misrepresentation measure (all consequential loss) even though the conduct is only negligent (Royscot Trust v Rogerson [1991] — controversial). Contractual exclusion of liability for misrepresentation is subject to the reasonableness test under UCTA 1977 / UTCCR (now CRA 2015 for consumers).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-frustration-davis-contractors",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "frustration",
      "Davis Contractors",
      "construction",
      "radically different",
      "force majeure"
    ],
    "crossCutting": false,
    "front": "What is the test for frustration of a contract under Davis Contractors Ltd v Fareham UDC [1956]?",
    "back": "A contract is frustrated when, without either party's fault, there occurs a change in circumstances so radical that performance of the contract would be a thing radically different from that which was undertaken at the time of contracting (Lord Radcliffe, Davis Contractors). The contract automatically discharges and the Law Reform (Frustrated Contracts) Act 1943 governs the financial consequences.",
    "details": "Davis Contractors: a contract to build 78 houses in 8 months took 22 months due to labour shortages. The contractor argued frustration to claim on a quantum meruit basis. HL held no frustration — building houses in difficult conditions, however extended, was not radically different from the contracted obligation. Key frustrating events: destruction of subject matter (Taylor v Caldwell [1863] — music hall burned down); illegality; cancellation of expected events (Krell v Henry [1903] — coronation cancelled, room hire frustrated). Frustration is construed narrowly — mere hardship or increased costs are insufficient (The Eugenia [1964]). The 1943 Act allows recovery of money paid and a just sum for partial performance.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-penalty-clauses-cavendish",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "penalty clauses",
      "liquidated damages",
      "Cavendish Square",
      "Parking Eye",
      "genuine pre-estimate"
    ],
    "crossCutting": false,
    "front": "What is the current test for distinguishing a legitimate liquidated damages clause from an unenforceable penalty?",
    "back": "A clause is penal and unenforceable if it imposes a detriment on the breach of contract out of all proportion to any legitimate interest of the innocent party in enforcing the primary obligation (Cavendish Square Holding BV v Makdessi; ParkingEye Ltd v Beavis [2015] SC). The old 'genuine pre-estimate of loss' test (Dunlop v New Garage [1915]) is no longer the exclusive test.",
    "details": "Cavendish and ParkingEye were decided together. Cavendish: a large-sum clause in a share purchase agreement was not penal because the buyer had a legitimate business interest in the goodwill restrictions going beyond mere compensation for breach. ParkingEye: an £85 parking fine for overstaying was not penal because ParkingEye had a legitimate interest in managing car parks beyond financial loss. The SC replaced the Dunlop test with a broader enquiry: (1) What is the innocent party's legitimate interest? (2) Is the clause proportionate to it? This allows commercially sophisticated parties greater freedom. Consumer contracts remain subject to the CRA 2015 (unfair terms).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-consideration-def",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "consideration",
      "bargain",
      "benefit and detriment"
    ],
    "crossCutting": false,
    "front": "What is consideration and why is it required for a binding contract?",
    "back": "Consideration is something of value given in exchange for a promise — it is the price of the promise. It can be a benefit to the promisor or a detriment to the promisee (Currie v Misa [1875]). English law requires consideration for all simple contracts (as distinct from deeds) because it marks the boundary between enforceable bargains and gratuitous promises.",
    "details": "Rules: consideration must be sufficient but need not be adequate (Chappell & Co v Nestle [1960] — chocolate wrappers were sufficient); must not be past (Re McArdle [1951] — exception: Lampleigh v Brathwait [1615] where previous service was at the promisor's request); must move from the promisee (Tweddle v Atkinson [1861]).",
    "related": [
      "contract-consideration-past",
      "contract-williams-roffey",
      "contract-promissory-estoppel",
      "contract-privity-crtpa1999"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-promissory-estoppel-requirements",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "promissory estoppel",
      "equitable",
      "shield not sword"
    ],
    "crossCutting": true,
    "front": "What is promissory estoppel and when can it be invoked?",
    "back": "Where a party makes a clear and unequivocal promise that they will not insist on their strict legal rights, and the other party relies on that promise, equity may prevent (estop) the promisor from going back on the promise. Requirements: (1) clear promise, (2) reliance by the promisee, (3) inequitable to allow the promisor to resile. It is a 'shield not a sword' — it cannot found a cause of action (Combe v Combe [1951]).",
    "details": "Central London Property Trust v High Trees House [1947] — Denning J: a landlord who promised reduced rent during wartime could not reclaim full rent for the war years. It is suspensory, not extinctive — rights are suspended and may revive on reasonable notice (Tool Metal v Tungsten Electric [1955]). Cross-cuts with Equity (equitable estoppel).",
    "related": [
      "contract-promissory-estoppel",
      "contract-consideration-def",
      "property-proprietary-estoppel",
      "prop-proprietary-estoppel"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-intention-clr",
    "type": "distinction",
    "module": "Contract Law",
    "tags": [
      "intention to create legal relations",
      "domestic",
      "commercial"
    ],
    "crossCutting": false,
    "front": "How does the law determine whether parties intended to create legal relations?",
    "back": "Two rebuttable presumptions: (1) In domestic and social agreements, the presumption is that there is NO intention to create legal relations (Balfour v Balfour [1919]). (2) In commercial agreements, the presumption IS that there is intention to create legal relations (Edwards v Skyways [1964]). Either presumption can be rebutted by evidence to the contrary.",
    "details": "Balfour v Balfour: husband's promise to pay wife maintenance was unenforceable — domestic arrangement. Contrast Merritt v Merritt [1970]: separated spouses — the agreement was enforceable because the relationship had broken down. Commercial presumption rebutted: Rose & Frank Co v Crompton [1925] — 'honourable pledge clause' negated legal intent.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-terms-conditions-warranties",
    "type": "distinction",
    "module": "Contract Law",
    "tags": [
      "terms",
      "conditions",
      "warranties",
      "innominate terms"
    ],
    "crossCutting": false,
    "front": "Distinguish conditions, warranties, and innominate terms in contract law.",
    "back": "A condition is a fundamental term — breach entitles the innocent party to terminate and claim damages. A warranty is a less important term — breach gives rise to damages only, not a right to terminate. An innominate term (Hong Kong Fir Shipping v Kawasaki Kisen Kaisha [1962]) is classified by the seriousness of the breach: if it deprives the innocent party of substantially the whole benefit of the contract, it is treated as a condition; otherwise as a warranty.",
    "details": "Classification is determined by: the intention of the parties, statutory classification (e.g. SGA 1979 s.12-15), or the courts' assessment. Poussard v Spiers (1876) — performer missing opening night = condition. Bettini v Gye (1876) — missing rehearsals = warranty. The innominate approach gives flexibility but less certainty than fixed classification.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-exclusion-ucta",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "exclusion clauses",
      "UCTA 1977",
      "reasonableness test"
    ],
    "crossCutting": true,
    "front": "How does the Unfair Contract Terms Act 1977 regulate exclusion clauses?",
    "back": "UCTA applies to business liability. Key provisions: s.2(1) — liability for death or personal injury caused by negligence cannot be excluded at all. S.2(2) — liability for other loss caused by negligence can be excluded only if reasonable. S.3 — where one party deals on the other's written standard terms, exclusion of liability for breach requires reasonableness. S.6 — implied terms under SGA s.12 cannot be excluded; s.13-15 terms can be excluded only if reasonable in non-consumer contracts.",
    "details": "The reasonableness test (s.11): the clause must be fair and reasonable having regard to circumstances known or contemplated at the time of contracting. Schedule 2 guidelines include: bargaining power, inducements, knowledge, custom. Smith v Eric S Bush [1990]: disclaimer by surveyor failed reasonableness test. Now supplemented by Consumer Rights Act 2015 for consumer contracts (unfair terms unenforceable). Cross-cuts with Commercial Law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-misrep-types",
    "type": "distinction",
    "module": "Contract Law",
    "tags": [
      "misrepresentation",
      "fraudulent",
      "negligent",
      "innocent"
    ],
    "crossCutting": false,
    "front": "Distinguish the three types of actionable misrepresentation.",
    "back": "Fraudulent (Derry v Peek [1889]): D made the statement knowing it was false, without belief in its truth, or recklessly as to its truth. Remedy: rescission + damages in tort of deceit. Negligent (s.2(1) Misrepresentation Act 1967): the burden is on the representor to prove reasonable grounds for believing the statement true. Remedy: rescission + damages (assessed as if fraudulent per Royscot Trust v Rogerson [1991]). Innocent: the representor had reasonable grounds for belief. Remedy: rescission, or damages in lieu of rescission under s.2(2).",
    "details": "Misrepresentation requires: (1) a false statement of fact (not opinion, unless Esso v Mardon [1976] applies — opinion of someone with special knowledge), (2) made to the claimant, (3) which induced them to enter the contract. Silence generally is not misrepresentation, but half-truths and changes of circumstances can be (With v O'Flanagan [1936]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-frustration",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "frustration",
      "impossibility",
      "radical change",
      "discharge"
    ],
    "crossCutting": false,
    "front": "When is a contract discharged by frustration?",
    "back": "A contract is frustrated when, without fault of either party, a supervening event renders performance impossible, illegal, or radically different from what was contemplated at the time of contracting (Davis Contractors v Fareham UDC [1956]). The event must not have been provided for in the contract and must not be self-induced.",
    "details": "Taylor v Caldwell (1863) — music hall destroyed by fire. Krell v Henry [1903] — coronation procession cancelled. Herne Bay Steamboat v Hutton [1903] — contract NOT frustrated because the purpose of seeing the fleet remained partly achievable. Self-induced frustration: Maritime National Fish v Ocean Trawlers [1935]. Consequences: Law Reform (Frustrated Contracts) Act 1943 — money paid is recoverable, money payable ceases.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-duress-economic",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "economic duress",
      "illegitimate pressure",
      "vitiation"
    ],
    "crossCutting": false,
    "front": "What is economic duress and when does it vitiate a contract?",
    "back": "Economic duress arises where one party exerts illegitimate pressure (typically a threat to breach a contract) that leaves the other with no practical alternative but to agree to revised terms. The victim must show: (1) illegitimate pressure or threat, (2) it was a significant cause of entering the agreement, and (3) there was no reasonable alternative. The contract is voidable.",
    "details": "DSND Subsea v Petroleum Geo-Services [2000]: Dyson J summarised the requirements. Universe Tankships of Monrovia v ITWF [1983]: the HL confirmed economic duress as a vitiating factor. Pao On v Lau Yiu Long [1980]: commercial pressure alone is not duress — the pressure must be illegitimate. Carillion Construction v Felix (UK) [2001]: the threat must be a significant cause, not necessarily the only cause.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-privity-exception",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "privity",
      "third party rights",
      "Contracts Act 1999"
    ],
    "crossCutting": false,
    "front": "How does the Contracts (Rights of Third Parties) Act 1999 modify the privity doctrine?",
    "back": "Under s.1, a third party may enforce a contractual term if: (a) the contract expressly provides that they may, or (b) the term purports to confer a benefit on them — unless the parties did not intend the term to be enforceable by the third party. The third party must be expressly identified in the contract by name, as a member of a class, or by description (s.1(3)).",
    "details": "The common law privity rule (Tweddle v Atkinson [1861]; Dunlop v Selfridge [1915]) remains — the 1999 Act creates a statutory exception. S.2 protects the third party: the contracting parties cannot rescind or vary the contract to the third party's detriment once the third party has assented, relied on the promise, or the promisor knows of their reliance. The Act does not affect other common law exceptions (agency, assignment, trust of a promise).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-remoteness-hadley",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "remoteness",
      "damages",
      "Hadley v Baxendale",
      "reasonable contemplation"
    ],
    "crossCutting": false,
    "front": "What is the test for remoteness of damage in contract?",
    "back": "Hadley v Baxendale (1854): damages are recoverable only for losses that (1) arise naturally from the breach in the usual course of things (first limb), or (2) may reasonably be supposed to have been in the contemplation of both parties at the time of contracting as the probable result of the breach, given special knowledge communicated (second limb).",
    "details": "Victoria Laundry v Newman Industries [1949] refined this to 'reasonable contemplation' of the type of loss. The Heron II [1969]: the degree of probability must be not unlikely (not merely foreseeable as in tort). Transfield Shipping v Mercator Shipping (The Achilleas) [2009] introduced an assumption of responsibility qualification — controversial and its scope remains debated.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-breach-anticipatory",
    "type": "application",
    "module": "Contract Law",
    "tags": [
      "anticipatory breach",
      "repudiation",
      "election"
    ],
    "crossCutting": false,
    "front": "A builder tells the homeowner two weeks before the start date: 'I'm not going to do the work.' Can the homeowner immediately sue for breach, or must they wait until the start date passes?",
    "back": "The homeowner can immediately sue. This is an anticipatory breach — a clear and unequivocal indication by one party that they will not perform. Under Hochster v De La Tour (1853), the innocent party has an election: (1) accept the repudiation, terminate the contract, and sue immediately for damages, or (2) affirm the contract and wait for the performance date, then sue if performance is not rendered.",
    "details": "If the innocent party affirms, the contract remains alive for both parties — the repudiating party could still perform, and the innocent party remains bound (White & Carter (Councils) v McGregor [1962], though subject to a 'legitimate interest' qualification). Avocet Industrial Electronics v CLTE [2023] affirmed the duty to mitigate applies once repudiation is accepted.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-undue-influence",
    "type": "principle",
    "module": "Contract Law",
    "tags": [
      "undue influence",
      "presumed",
      "actual",
      "vitiation"
    ],
    "crossCutting": true,
    "front": "What are the two classes of undue influence?",
    "back": "Class 1 (actual undue influence): the claimant proves the defendant actually exerted undue influence over a specific transaction. Class 2 (presumed undue influence): the claimant proves (a) a relationship of trust and confidence (either Category 2A — automatically presumed relationships like solicitor-client, parent-child, or Category 2B — proved on the facts), AND (b) the transaction 'calls for explanation' (is not readily explicable). The burden then shifts to the defendant to prove no undue influence.",
    "details": "Royal Bank of Scotland v Etridge (No 2) [2002] — the HL restated the law. In surety cases (wife guarantees husband's debts), the bank is 'put on inquiry' and must ensure the wife received independent legal advice. The transaction is voidable, not void. Cross-cuts with Equity (unconscionability).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-williams-roffey",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "consideration",
      "practical benefit",
      "Williams v Roffey",
      "existing duty"
    ],
    "crossCutting": false,
    "front": "What principle did Williams v Roffey Bros [1991] establish regarding consideration and existing contractual duties?",
    "back": "Where a party promises extra payment for performance of an existing contractual duty owed to them, the promise is supported by consideration if the promisor obtains a 'practical benefit' (e.g. avoiding a penalty clause, ensuring timely completion) and the promise was not obtained by economic duress. This modified the rule in Stilk v Myrick (1809) that performance of an existing duty owed to the promisor is not good consideration.",
    "details": "The builders were subcontracted to do carpentry. When they fell behind, the main contractor promised extra money. The CA held the practical benefit (avoiding a penalty clause in the main contract and not having to find new carpenters) was sufficient consideration. Stilk v Myrick was distinguished rather than overruled. MWB Business Exchange v Rock Advertising [2018] — oral variation of a no-oral-modification clause was ineffective, but the SC did not address whether Roffey applies to reductions in payment.",
    "related": [
      "contract-consideration-def",
      "contract-consideration-past",
      "contract-promissory-estoppel"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-penalty-clause",
    "type": "case",
    "module": "Contract Law",
    "tags": [
      "penalty clause",
      "liquidated damages",
      "Cavendish v Makdessi"
    ],
    "crossCutting": false,
    "front": "When is a contractual damages clause unenforceable as a penalty?",
    "back": "Under Cavendish Square Holding v Makdessi [2015], the test is whether the clause imposes a detriment on the contract-breaker that is out of all proportion to any legitimate interest of the innocent party in the enforcement of the primary obligation. The old 'genuine pre-estimate of loss' test (Dunlop Pneumatic Tyre v New Garage [1915]) was reformulated — the clause need not be a pre-estimate, but it must protect a legitimate business interest and not be extravagant or unconscionable.",
    "details": "The Supreme Court in Cavendish/ParkingEye [2015] held: legitimate interests can include deterrence, not just compensation. A parking charge of £85 was enforceable because ParkingEye had a legitimate interest in managing the car park efficiently. The doctrine applies only to secondary obligations (payable on breach), not primary obligations.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-specific-performance",
    "type": "distinction",
    "module": "Contract Law",
    "tags": [
      "specific performance",
      "injunction",
      "equitable remedy",
      "damages"
    ],
    "crossCutting": true,
    "front": "When will a court grant specific performance instead of damages?",
    "back": "Specific performance is an equitable remedy ordering the defendant to perform their contractual obligation. It is only granted where: (1) damages are inadequate (e.g. for unique goods or land — Beswick v Beswick [1968]), (2) the contract terms are sufficiently certain, (3) the court can supervise the order, and (4) it would not cause undue hardship. It is never available for contracts of personal service (employment).",
    "details": "Co-operative Insurance v Argyll Stores [1998]: the HL refused to order specific performance of a covenant to keep a store open — too difficult to supervise a running business. Sky Petroleum v VIP Petroleum [1974]: specific performance was granted for a fuel supply contract during an oil crisis because damages would be inadequate. The remedy is discretionary — equitable bars (laches, clean hands) apply. Cross-cuts with Equity.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-acceptance-postal-rule",
    "type": "application",
    "module": "Contract Law",
    "tags": [
      "acceptance",
      "postal rule",
      "instantaneous communication"
    ],
    "crossCutting": false,
    "front": "A sends a letter offering to sell goods to B. B posts a letter of acceptance on Monday; it arrives on Wednesday. A, not having heard from B, sells the goods to C on Tuesday. Is there a binding contract between A and B?",
    "back": "Yes. Under the postal rule (Adams v Lindsell (1818)), acceptance takes effect when properly posted, not when received. B's acceptance was effective on Monday when posted. A's sale to C on Tuesday was a breach of the already-formed contract with B. The postal rule applies where post is a reasonable and contemplated method of communication.",
    "details": "The postal rule does not apply to instantaneous communications (Entores v Miles Far East [1955] — telex; Brinkibon v Stahag Stahl [1983]). The offeror can exclude the postal rule by requiring actual receipt. Holwell Securities v Hughes [1974]: words 'notice in writing to' required actual communication, so the postal rule did not apply. For electronic communications, the position remains governed by Brinkibon principles.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-carlill-carbolic",
    "type": "case",
    "module": "Contract Law",
    "tags": ["unilateral contract", "offer", "Carlill", "advertisement"],
    "crossCutting": false,
    "front": "Carlill v Carbolic Smoke Ball Co [1893] — what principles did it establish about unilateral offers and advertisements?",
    "back": "(1) An advertisement can constitute an offer, not merely an invitation to treat, where it demonstrates clear intention to be bound (evidenced here by the £1,000 deposited in the bank). (2) A unilateral contract is formed when a party performs the stipulated act in reliance on the offer — no separate communication of acceptance is needed. (3) General offers to the world are valid; anyone who fulfils the conditions can accept.",
    "details": "CA: Lindley, Bowen, AL Smith LJJ. The company advertised £100 reward to anyone who caught flu after using the smoke ball as directed. Mrs Carlill used it, caught flu, and sued. The company's arguments (no offer, no notification of acceptance, no consideration, too vague) all failed. Consideration = the inconvenience of using the ball. This case remains the foundation of unilateral contract analysis and demonstrates the objective test of intention.",
    "related": ["contract-consideration-def"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-hyde-wrench",
    "type": "case",
    "module": "Contract Law",
    "tags": ["counter-offer", "offer", "Hyde v Wrench"],
    "crossCutting": false,
    "front": "Hyde v Wrench (1840) — what rule did it establish about counter-offers?",
    "back": "A counter-offer destroys the original offer and cannot subsequently be accepted. Once the offeree proposes different terms, the original offer is extinguished and the offeror is free to refuse.",
    "details": "Wrench offered to sell his farm for £1,000. Hyde replied offering £950. Wrench refused. Hyde then purported to accept the original £1,000 offer. Held: no contract. Lord Langdale MR: the counter-offer was a rejection of the original. Distinguish mere requests for information (Stevenson Jaques v McLean [1880]) — asking about terms does not kill the offer.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-dickinson-dodds",
    "type": "case",
    "module": "Contract Law",
    "tags": ["revocation", "offer", "Dickinson v Dodds"],
    "crossCutting": false,
    "front": "Dickinson v Dodds (1876) — how can an offer be revoked, and must revocation come from the offeror directly?",
    "back": "An offer can be revoked at any time before acceptance. Revocation need not be communicated by the offeror personally — it is effective if the offeree learns of it from a reliable third party. Revocation must, however, actually reach the offeree's mind before acceptance.",
    "details": "Dodds offered to sell property to Dickinson, leaving the offer 'open until Friday 9am'. On Thursday, Dickinson learned from a third party that Dodds had sold to someone else. Dickinson still purported to accept. CA: no contract — the offer had been effectively revoked because Dickinson knew it was no longer open. Absent consideration, a promise to keep an offer open is not binding (no 'option' contract).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-entores",
    "type": "case",
    "module": "Contract Law",
    "tags": ["acceptance", "instantaneous communication", "Entores", "place of contract"],
    "crossCutting": false,
    "front": "Entores Ltd v Miles Far East Corp [1955] — what rule applies to acceptance by instantaneous communications?",
    "back": "For instantaneous communications (telex, telephone, fax, email), acceptance takes effect where and when it is received by the offeror, not when sent. The postal rule does not apply. The contract is formed at the place where acceptance is received.",
    "details": "Denning LJ: if the line goes dead mid-sentence, or the telex fails to print at the receiving end, there is no acceptance until the offeree resends successfully. Confirmed by the HL in Brinkibon v Stahag Stahl [1983] for telex during business hours, though Lord Wilberforce noted more complex situations (out-of-hours messages, intermediaries) require a case-by-case approach based on the parties' intentions and sound business practice.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-chappell-nestle",
    "type": "case",
    "module": "Contract Law",
    "tags": ["consideration", "sufficiency", "adequacy", "Chappell"],
    "crossCutting": false,
    "front": "Chappell & Co Ltd v Nestlé Co Ltd [1960] — what did the House of Lords establish about the adequacy of consideration?",
    "back": "Consideration must be sufficient (have some value in the eyes of the law) but need not be adequate (need not match the value of what is received). Even a trivial thing can amount to consideration if the parties treat it as part of the bargain. 'A peppercorn does not cease to be good consideration if it is established that the promisee does not like pepper and will throw away the corn.' (Lord Somervell)",
    "back_short": "",
    "details": "Nestlé offered a record for 1s 6d + three chocolate wrappers. Chappell, the copyright holder, argued the wrappers were part of the consideration (which mattered for royalty calculation under the Copyright Act 1956). HL held (3-2) the wrappers were consideration even though Nestlé threw them away — they had induced sales. The case illustrates the courts' refusal to police the fairness of bargains.",
    "related": ["contract-consideration-def", "contract-consideration-past"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-foakes-beer",
    "type": "case",
    "module": "Contract Law",
    "tags": ["part payment", "Pinnel's rule", "Foakes v Beer", "consideration"],
    "crossCutting": false,
    "front": "Foakes v Beer (1884) — what is the rule on part payment of a debt?",
    "back": "Payment of a lesser sum on the due date cannot satisfy a creditor's claim for the whole (the rule in Pinnel's Case (1602) affirmed). A promise by the creditor to accept less is unenforceable for want of consideration, because the debtor is already bound to pay the full sum.",
    "details": "Mrs Beer obtained judgment against Dr Foakes. She agreed not to enforce the judgment if he paid by instalments. He did, then she sued for interest. HL: the agreement was unenforceable — Foakes had given no fresh consideration. Exceptions: (1) payment early / in different form / at different place (Pinnel's Case); (2) accord and satisfaction by third party (Hirachand Punamchand v Temple [1911]); (3) promissory estoppel (High Trees); (4) composition with creditors. Williams v Roffey (practical benefit) has NOT been extended to part payment: Re Selectmove [1995]; MWB v Rock Advertising [2018] left the point open.",
    "related": ["contract-consideration-def", "contract-williams-roffey", "contract-promissory-estoppel"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-hadley-baxendale-case",
    "type": "case",
    "module": "Contract Law",
    "tags": ["remoteness", "damages", "Hadley v Baxendale", "two limbs"],
    "crossCutting": false,
    "front": "Hadley v Baxendale (1854) — state the two-limb rule on remoteness of damage in contract.",
    "back": "Damages are recoverable if the loss is either: (1) such as may fairly and reasonably be considered as arising naturally, i.e. according to the usual course of things, from the breach itself (imputed knowledge); OR (2) such as may reasonably be supposed to have been in the contemplation of both parties at the time they made the contract, as the probable result of breach (actual knowledge of special circumstances).",
    "details": "Alderson B. Mill owners' crankshaft broke; they gave the broken shaft to a carrier to take for repair. The carrier delayed delivery and the mill remained idle. Held: lost profits were NOT recoverable because the carrier was not told the mill was idle without the shaft. Modernised in Victoria Laundry v Newman [1949] (reasonably foreseeable / 'serious possibility') and The Heron II [1969] ('not unlikely' standard). Transfield Shipping v Mercator (The Achilleas) [2008] added an 'assumption of responsibility' gloss — whether the type of loss was one the defendant can fairly be taken to have accepted liability for.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-taylor-caldwell",
    "type": "case",
    "module": "Contract Law",
    "tags": ["frustration", "impossibility", "Taylor v Caldwell"],
    "crossCutting": false,
    "front": "Taylor v Caldwell (1863) — how did it introduce the doctrine of frustration into English law?",
    "back": "Where a contract's performance depends on the continued existence of a specific thing, and that thing perishes without fault of either party before performance, the contract is discharged. An implied condition that the thing will continue to exist is read into the agreement. This established frustration by impossibility.",
    "details": "Blackburn J. The Surrey Gardens and Music Hall was hired for concerts; it burned down before the first concert. The plaintiff sued for wasted advertising expenses. Held: the contract was discharged — neither party was liable. Departed from the absolute contracts rule in Paradine v Jane (1647). The theoretical basis has shifted from 'implied term' (Taylor) to a more objective 'radical change in the obligation' test: Davis Contractors v Fareham UDC [1956]; National Carriers v Panalpina [1981].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-krell-henry",
    "type": "case",
    "module": "Contract Law",
    "tags": ["frustration", "frustration of purpose", "Krell v Henry", "coronation cases"],
    "crossCutting": false,
    "front": "Krell v Henry [1903] — what is 'frustration of purpose' and how does it differ from impossibility?",
    "back": "Frustration of purpose arises where performance is still physically possible but the common foundation of the contract — the shared purpose both parties contemplated — has been destroyed by the supervening event, rendering performance radically different from what was agreed.",
    "details": "Henry hired a room in Pall Mall for two days to view Edward VII's coronation procession. The coronation was postponed due to the King's illness. Held: contract frustrated — viewing the procession was the foundation of the contract, known to both parties. Contrast Herne Bay Steam Boat v Hutton [1903] (boat hired to see the royal fleet review AND cruise the fleet): not frustrated — cruising remained possible and was part of the purpose. Frustration of purpose is narrowly construed: the event must destroy the entire common basis, not just make the contract less valuable for one party.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-bell-lever-bros",
    "type": "case",
    "module": "Contract Law",
    "tags": ["mistake", "common mistake", "Bell v Lever Bros"],
    "crossCutting": false,
    "front": "Bell v Lever Bros Ltd [1932] — what is the test for common mistake as to quality?",
    "back": "A common mistake as to the quality of the subject matter will void a contract only if it makes the thing contracted for essentially different from what the parties believed it to be. Mere mistake as to value or attributes is insufficient; the mistake must go to a fundamental assumption shared by both parties.",
    "details": "HL. Lever Bros terminated Bell's employment contract with a generous severance payment, unaware that Bell had committed breaches entitling them to dismiss him without compensation. They sued to recover the payment as paid under mistake. Held (3-2): contract not void — the mistake was not sufficiently fundamental. Great Peace Shipping v Tsavliris Salvage [2002] (CA) confirmed the strict test and held there is no separate equitable jurisdiction to set aside for common mistake on wider grounds (overruling Solle v Butcher [1950]).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-lestrange-graucob",
    "type": "case",
    "module": "Contract Law",
    "tags": ["signature rule", "exclusion clauses", "L'Estrange", "incorporation"],
    "crossCutting": false,
    "front": "L'Estrange v F Graucob Ltd [1934] — what is the signature rule?",
    "back": "A person who signs a contractual document is bound by its terms, whether or not they have read it, in the absence of fraud or misrepresentation. Signature alone is sufficient incorporation — no separate notice is required.",
    "details": "Scrutton LJ. Mrs L'Estrange bought a cigarette machine, signing a sales agreement that contained a clause excluding all implied warranties in small print. The machine was defective. Held: she was bound. Exceptions: (1) misrepresentation as to the document's effect (Curtis v Chemical Cleaning [1951]); (2) non est factum (document fundamentally different from what was believed: Saunders v Anglia Building Society [1971]); (3) the document was not contractual in nature (Grogan v Robin Meredith Plant Hire [1996]). The rule has been doubted but remains the law: contrast Lord Denning's dissent-in-effect in Tilden Rent-A-Car v Clendenning (Canada).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-photo-production",
    "type": "case",
    "module": "Contract Law",
    "tags": ["exclusion clauses", "fundamental breach", "Photo Production", "Securicor"],
    "crossCutting": false,
    "front": "Photo Production Ltd v Securicor Transport Ltd [1980] — what did the HL decide about exclusion clauses and fundamental breach?",
    "back": "There is no rule of law that an exclusion clause cannot protect a party from liability for a fundamental breach. Whether an exclusion clause covers a particular breach is a pure question of construction of the contract. The doctrine of 'fundamental breach' as a rule of law (espoused by Lord Denning in the CA) was rejected by the HL.",
    "details": "Lord Wilberforce, Lord Diplock. A Securicor patrolman deliberately set fire to Photo Production's factory. The contract contained a wide exclusion clause. HL: the clause, on its natural construction, covered this breach. The case marks the HL's second rejection of the Denning doctrine (after Suisse Atlantique [1967]). After UCTA 1977, the statutory reasonableness test now provides protection; construction remains the starting point. Lord Diplock distinguished 'primary' and 'secondary' obligations — exclusion clauses modify secondary obligations (to pay damages) that arise on breach.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-hong-kong-fir",
    "type": "case",
    "module": "Contract Law",
    "tags": ["innominate terms", "Hong Kong Fir", "conditions", "warranties", "classification"],
    "crossCutting": false,
    "front": "Hong Kong Fir Shipping Co Ltd v Kawasaki Kisen Kaisha Ltd [1962] — what category of terms did it recognise and on what basis is breach assessed?",
    "back": "The CA recognised 'innominate' (or 'intermediate') terms — terms that are neither conditions nor warranties. Whether breach of such a term permits termination depends not on the classification of the term in advance, but on whether the breach in fact deprives the innocent party of substantially the whole benefit intended under the contract.",
    "details": "Diplock LJ. A two-year charterparty required the ship to be 'seaworthy'. It needed extensive repairs taking about 20 weeks, leaving 17 months of performance. Held: the breach did not deprive the charterers of substantially the whole benefit — only a warranty-type response (damages) was available, not termination. The innominate term approach is now the default where the contract does not clearly classify terms and no statute does so. Contrast Bunge v Tradax [1981] (time clauses in commercial contracts usually conditions) and The Mihalis Angelos [1971] ('expected ready to load' held a condition).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "contract-ruxley-forsyth",
    "type": "case",
    "module": "Contract Law",
    "tags": ["damages", "cost of cure", "loss of amenity", "Ruxley"],
    "crossCutting": false,
    "front": "Ruxley Electronics & Construction Ltd v Forsyth [1996] — what measure of damages did the HL adopt where cost of cure is disproportionate?",
    "back": "Where the cost of cure (reinstatement) is wholly disproportionate to the benefit to be obtained, damages will be measured by loss of amenity rather than cost of cure. The claimant is not entitled to cost of cure where it would be unreasonable to insist on reinstatement. Nor is diminution in value always appropriate — a modest sum for loss of amenity can fill the gap.",
    "details": "Forsyth contracted for a swimming pool with a diving area 7'6\" deep; it was built only 6'9\" deep, still safe for diving. Cost of rebuilding: £21,560. Diminution in market value: nil. HL awarded £2,500 for loss of amenity. Lord Mustill, Lord Lloyd. The case shows English law accepting non-pecuniary 'consumer surplus' damages in limited circumstances, supplementing the expectation measure. Compare Farley v Skinner [2001] — damages for distress where a major object of the contract was to provide peace of mind.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
