// Auto-generated from cards.js split. Module: Criminal Law
export const criminalLawCards = [
  {
    "id": "6",
    "type": "application",
    "module": "Criminal Law",
    "tags": [
      "self-defence",
      "reasonable force"
    ],
    "crossCutting": false,
    "front": "D is a 70-year-old shop owner. A young man grabs cash from the till and runs. D strikes the fleeing thief on the head from behind with a cricket bat. Can D rely on self-defence?",
    "back": "Unlikely. Self-defence requires (1) genuine belief in need to use force, and (2) reasonable force in the circumstances as D believed them to be. The threat had passed — striking a retreating person from behind is likely disproportionate.",
    "details": "S.76 CJIA 2008. Palmer v R [1971]. Cf. R v Clegg [1995] — soldier's final shot at fleeing joyrider was excessive.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-actus-reus-omissions",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "actus reus",
      "omission",
      "duty to act",
      "gibbins v proctor",
      "stone dobinson"
    ],
    "crossCutting": false,
    "front": "When can a criminal omission give rise to liability? What recognised duty categories exist?",
    "back": "Criminal liability ordinarily requires a positive act. Omissions are only criminal where there is a legal duty to act. Recognised duty categories: (1) statutory duty; (2) contractual duty; (3) duty arising from assumption of care (R v Stone and Dobinson [1977]); (4) duty arising from a special relationship (Gibbins v Proctor [1918] — parent/child); (5) duty from creation of a dangerous situation (R v Miller [1983]).",
    "details": "Gibbins v Proctor: a father and his partner deliberately withheld food from his child causing death — omission amounted to murder. Stone and Dobinson: defendants assumed care of an infirm relative who later died from neglect — their voluntary assumption created a duty. Miller: squatter fell asleep with a cigarette, woke to find mattress smouldering and did nothing — held liable for arson because he created the danger (duty to act once aware). The 'no liability for omissions' rule reflects autonomy and the difficulty of specifying who must rescue, in contrast to civil law (French law imposes a general duty to rescue).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-mens-rea-intention-woollin",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "mens rea",
      "intention",
      "woollin",
      "virtual certainty",
      "oblique intent"
    ],
    "crossCutting": false,
    "front": "Explain direct and oblique intention in criminal law, and the Woollin direction.",
    "back": "Direct intent: the defendant's purpose or aim is to bring about the prohibited consequence. Oblique (indirect) intent: the defendant did not aim at the consequence but it was a virtually certain result of their actions and they foresaw it as virtually certain (R v Woollin [1998] — the jury may find intention in such circumstances).",
    "details": "Woollin: the defendant threw his baby son onto a hard surface, causing skull fracture and death. The HL confirmed that where the consequence is a virtually certain result of the defendant's acts, and the defendant appreciates that this is so, the jury are entitled (not bound) to find the necessary intention. This is a direction to a jury, not a complete definition of intention. The test replaces earlier uncertainty from Moloney [1985] (natural consequence) and Hancock [1986] (degree of probability). Oblique intent is relevant mainly in murder and GBH where the specific intent requirement would otherwise be unsatisfied.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-recklessness-r-v-g",
    "type": "case",
    "module": "Criminal Law",
    "tags": [
      "recklessness",
      "R v G",
      "subjective recklessness",
      "caldwell",
      "criminal damage"
    ],
    "crossCutting": false,
    "front": "What is the current test for recklessness in criminal law after R v G [2003]?",
    "back": "After R v G the test for recklessness is subjective: a person acts recklessly when they are aware of a risk that a result will occur or a circumstance exists, and it is, in the circumstances known to them, unreasonable to take the risk (restoring the Cunningham [1957] test). This overruled the objective Caldwell recklessness test.",
    "details": "Caldwell v Metropolitan Police Commissioner [1982] had introduced an objective test: a person was reckless if an obvious risk existed, whether or not they had thought about it. This was harshly applied in Elliott v C [1983] — a girl with learning difficulties set a shed alight, convicted despite being incapable of appreciating the risk. R v G involved two boys aged 11 and 12 who lit newspapers and left them burning, causing £1m damage; the HL held the objective Caldwell test was incompatible with the presumption of subjective fault and overruled it. Cunningham recklessness now applies across all offences unless statute requires otherwise.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-murder-elements",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "murder",
      "malice aforethought",
      "intention to kill",
      "intention to cause GBH",
      "unlawful killing"
    ],
    "crossCutting": false,
    "front": "What are the elements of murder in English law?",
    "back": "Murder is the unlawful killing of a human being under the Queen's/King's Peace with malice aforethought expressed or implied. Malice aforethought means an intention to kill or an intention to cause grievous bodily harm (GBH) (R v Vickers [1957]; R v Cunningham [1982] — intent to cause GBH suffices). The mandatory sentence is life imprisonment.",
    "details": "Key points: 'unlawful' excludes killing in self-defence, execution, or war. 'Human being' — the victim must have been born alive (a foetus is not a human being for murder purposes: Attorney-General's Reference (No 3 of 1994) [1998]). 'Queen's Peace' — historically excludes enemies in wartime. The GBH intention as sufficient mens rea was confirmed in Cunningham and is controversial — the Law Commission has recommended intent to kill or cause serious injury with awareness of serious injury risk as the test. Partial defences (loss of control — Coroners and Justice Act 2009; diminished responsibility — s2 Homicide Act 1957) reduce murder to voluntary manslaughter.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-gross-negligence-manslaughter",
    "type": "case",
    "module": "Criminal Law",
    "tags": [
      "gross negligence manslaughter",
      "adomako",
      "duty of care",
      "gross negligence"
    ],
    "crossCutting": false,
    "front": "What is the test for gross negligence manslaughter following R v Adomako [1994]?",
    "back": "Gross negligence manslaughter (GNM) requires: (1) D owed V a duty of care; (2) D breached that duty; (3) the breach caused death; (4) the breach was so grossly negligent that the jury considers it criminal — a risk of death must have been obvious to a reasonable person in D's position (R v Adomako [1994] HL; confirmed R v Misra [2004]).",
    "details": "Adomako: an anaesthetist failed to notice a disconnected breathing tube during an operation; the patient died. The HL held the civil negligence test (Caparo) applies to establish duty and breach, but the jury determines whether the negligence was 'gross' enough to be criminal. The circular nature of the test (is it criminal enough to be criminal?) was criticised as vague, but upheld under Art 7 ECHR in Misra. Corporate manslaughter is now governed by the Corporate Manslaughter and Corporate Homicide Act 2007. GNM is distinguished from constructive (unlawful act) manslaughter, which requires an unlawful dangerous act.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-theft-appropriation",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "theft",
      "appropriation",
      "Theft Act 1968",
      "dishonesty",
      "Ghosh",
      "Ivey v Genting"
    ],
    "crossCutting": false,
    "front": "What are the elements of theft under the Theft Act 1968 s1 and what is the test for dishonesty?",
    "back": "Theft (s1 TA 1968): dishonestly appropriates property belonging to another with intention permanently to deprive. (1) Appropriation — any assumption of an owner's rights (s3); can occur even with consent (R v Gomez [1993]). (2) Property — s4 (excludes land generally). (3) Belonging to another — s5. (4) Dishonesty — objective test: would reasonable/honest people consider it dishonest? (Ivey v Genting Casinos [2017], overruling Ghosh). (5) Intention permanently to deprive — s6.",
    "details": "Gomez: D obtained goods by deception with the manager's consent — still an appropriation. Lawrence v MPC [1972]: taxi passenger allowed cabbie to take more than correct fare — still an appropriation. Dishonesty: Ivey (SC, obiter in a civil case) replaced the two-stage Ghosh test (objective + subjective) with a single objective standard: (1) establish what D actually knew, believed or intended, then (2) ask whether their conduct was dishonest by the standards of ordinary decent people. S2 TA 1968 provides specific honest belief defences (e.g. belief in legal right). Intention permanently to deprive includes treating property as your own to dispose of regardless of the other's rights (s6(1)).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "criminal-transferred-malice",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "transferred malice",
      "mens rea",
      "R v Latimer",
      "intended victim",
      "actual victim"
    ],
    "crossCutting": false,
    "front": "What is the doctrine of transferred malice in criminal law?",
    "back": "Where D intends to commit an offence against one person but accidentally commits the same offence against a different person, the mens rea transfers to the unintended victim. D is guilty of the offence against the actual victim (R v Latimer [1886]).",
    "details": "Latimer: D aimed a belt at X but hit Y, seriously injuring her. Held: the malice (intention) transferred from the intended to the actual victim. The doctrine requires the same type of offence — R v Pembliton [1874]: D threw a stone intending to hit people but hit a window; the mens rea for assault could not transfer to criminal damage (different offences). The transfer is within species: you cannot transfer malice across offence types. AG's Reference (No 3 of 1994): murder mens rea cannot transfer to a foetus subsequently born alive who dies — HL held not guilty of murder but potentially manslaughter.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-actus-reus-omission",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "actus reus",
      "omission",
      "duty to act"
    ],
    "crossCutting": false,
    "front": "When can a failure to act (omission) constitute the actus reus of a criminal offence?",
    "back": "Generally there is no criminal liability for omissions — the common law does not impose a duty to rescue. Exceptions arise where there is a duty to act: (1) statute (e.g. failing to report a road accident), (2) special relationship (parent-child — Gibbins & Proctor), (3) voluntary assumption of responsibility (Stone & Dobinson), (4) contractual duty (Pittwood), (5) creation of a dangerous situation (Miller).",
    "details": "R v Miller [1983]: D fell asleep with a lit cigarette, awoke to find the mattress on fire, and simply moved to another room. He was convicted of arson — having created the danger, he was under a duty to take reasonable steps to counteract it. R v Stone & Dobinson [1977]: D's elderly relative died of neglect after they assumed her care.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-causation-legal",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "causation",
      "factual",
      "legal",
      "but-for",
      "operative and substantial"
    ],
    "crossCutting": false,
    "front": "Explain the two stages of causation in criminal law.",
    "back": "Stage 1 — Factual causation ('but for' test): but for D's act, would V have suffered the harm? If V would have died anyway, D did not cause the death (R v White [1910]). Stage 2 — Legal causation: D's act must be an 'operative and substantial' cause of the result. It need not be the sole or even the main cause, but must be more than de minimis (R v Pagett [1983]).",
    "details": "R v White: D poisoned his mother's drink, but she died of a heart attack before drinking enough. Factual causation not established. R v Smith [1959]: original wound was still an 'operating and substantial cause' of death despite poor medical treatment. The thin skull rule applies in criminal law too — take the victim as you find them (R v Blaue [1975]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-mens-rea-intention",
    "type": "distinction",
    "module": "Criminal Law",
    "tags": [
      "mens rea",
      "intention",
      "direct intent",
      "oblique intent",
      "woollin"
    ],
    "crossCutting": false,
    "front": "Distinguish direct intention from oblique (indirect) intention in criminal law.",
    "back": "Direct intention: D acts with the purpose or aim of bringing about a consequence — it is their desire. Oblique intention: D does not desire the consequence but foresees it as a virtual certainty of their actions (R v Woollin [1999]). Under Woollin, the jury may 'find' intention where death or serious harm was a virtual certainty and D appreciated this.",
    "details": "Woollin arose from D throwing his baby at a hard surface. The HL held that the jury should be directed that they are not entitled to find intention unless they feel sure the consequence was a virtual certainty and D appreciated that. Note: 'find' not 'infer' — this is an evidential rule, not substantive (debated). Moloney [1985] and Hancock & Shankland [1986] preceded Woollin.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-recklessness-cunningham",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "recklessness",
      "subjective",
      "cunningham",
      "mens rea"
    ],
    "crossCutting": false,
    "front": "What is the current test for recklessness in criminal law?",
    "back": "Subjective recklessness (the Cunningham test): D is reckless if (1) D is aware of a risk that a particular consequence will occur or circumstance exists, and (2) in the circumstances known to D, it is unreasonable to take that risk. Since R v G [2004] overruled Caldwell, subjective recklessness is the standard test across criminal law.",
    "details": "R v G [2004]: two boys aged 11 and 12 set fire to newspapers under a bin, causing damage to a shop. HL overruled Caldwell — objective recklessness was unjust, especially for defendants who lack capacity to foresee the risk. Cunningham [1957]: D tore a gas meter from the wall to steal money; gas leaked and poisoned his mother-in-law. Convicted because he was aware of the risk of gas escape.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-murder-definition",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "murder",
      "homicide",
      "malice aforethought",
      "intention"
    ],
    "crossCutting": false,
    "front": "What are the elements of murder?",
    "back": "Murder is a common law offence. The actus reus is the unlawful killing of a human being under the Queen's/King's peace. The mens rea is 'malice aforethought' — intention to kill or intention to cause grievous bodily harm (R v Vickers [1957]). There is no need to prove premeditation. The mandatory sentence is life imprisonment.",
    "details": "Lord Coke's classic definition. 'Year and a day' rule was abolished by the Law Reform (Year and a Day Rule) Act 1996. The GBH rule (intention to cause GBH suffices for murder) has been criticised — D may intend only to break an arm but if V dies, D is guilty of murder. R v Cunningham [1982] confirmed the GBH rule stands.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-voluntary-manslaughter-lr",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "voluntary manslaughter",
      "loss of control",
      "diminished responsibility"
    ],
    "crossCutting": false,
    "front": "What are the two partial defences that reduce murder to voluntary manslaughter?",
    "back": "Under the Coroners and Justice Act 2009: (1) Loss of control (ss.54-56) — D must have lost self-control due to a qualifying trigger (fear of serious violence, or circumstances of an extremely grave character causing D to have a justifiable sense of being seriously wronged), and a person of D's sex and age with a normal degree of tolerance might have reacted in the same way. (2) Diminished responsibility (s.52, amending s.2 Homicide Act 1957) — D's ability to understand conduct, form rational judgment, or exercise self-control was substantially impaired by an abnormality of mental functioning arising from a recognised medical condition.",
    "details": "Loss of control replaced the old provocation defence. Sexual infidelity is excluded as a qualifying trigger on its own (s.55(6)(c)), but can be part of a wider context (R v Clinton [2012]). Diminished responsibility: the burden of proof is on D (balance of probabilities). R v Byrne [1960] under the old law; R v Golds [2016] on the meaning of 'substantial'.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-involuntary-manslaughter-ua",
    "type": "distinction",
    "module": "Criminal Law",
    "tags": [
      "involuntary manslaughter",
      "unlawful act",
      "gross negligence"
    ],
    "crossCutting": false,
    "front": "Distinguish unlawful act manslaughter from gross negligence manslaughter.",
    "back": "Unlawful act manslaughter (constructive): D commits an intentional criminal act that is dangerous (risk of some physical harm — Church [1966]) and that act causes death. No need to foresee death. Gross negligence manslaughter (Adomako [1995]): D owes a duty of care, breaches it, the breach causes death, and the breach is so gross as to justify criminal conviction — judged by the standards of a reasonable person.",
    "details": "Unlawful act must be a crime, not merely a tort (Franklin [1883]). The act must be 'dangerous' in the eyes of a sober and reasonable person (Church). It must be intentional (Lamb [1967] — no mens rea for assault, so no unlawful act). Adomako: an anaesthetist failed to notice a disconnected oxygen tube for 6 minutes. Rose v R [2017] restricted the scope of duty-based liability.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-insanity-mnaghten",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "insanity",
      "M'Naghten",
      "defence",
      "disease of the mind"
    ],
    "crossCutting": false,
    "front": "What are the M'Naghten Rules for the defence of insanity?",
    "back": "D must prove on the balance of probabilities that at the time of the act, they were labouring under such a defect of reason, from disease of the mind, as not to know (1) the nature and quality of the act, or (2) that what they were doing was wrong ('wrong' meaning legally wrong — R v Windle [1952]). The verdict is 'not guilty by reason of insanity'.",
    "details": "M'Naghten's Case (1843). 'Disease of the mind' is a legal, not medical, concept — it includes epilepsy (Sullivan [1984]), arteriosclerosis (Kemp [1957]), diabetes causing hyperglycaemia (Hennessy [1989]), and sleepwalking (Burgess [1991]). External causes (e.g. insulin causing hypoglycaemia — Quick [1973]) fall under automatism instead.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-intoxication-basic-specific",
    "type": "distinction",
    "module": "Criminal Law",
    "tags": [
      "intoxication",
      "basic intent",
      "specific intent",
      "majewski"
    ],
    "crossCutting": false,
    "front": "How does voluntary intoxication affect criminal liability?",
    "back": "DPP v Majewski [1977]: voluntary intoxication is no defence to crimes of basic intent (where recklessness suffices as mens rea, e.g. assault, s.20 GBH, manslaughter, criminal damage). It may be a defence to crimes of specific intent (requiring intention, e.g. murder, s.18 GBH, theft, burglary) if it prevented D from forming the required intention. If so, D may still be convicted of a lesser basic intent offence.",
    "details": "The basic/specific intent distinction is much criticised — the rationale being that voluntarily becoming intoxicated is itself reckless. Involuntary intoxication is a defence to any crime if it prevents formation of the required mens rea (R v Kingston [1995] — but if D still formed the intent despite involuntary intoxication, no defence). Dutch courage: if D forms intent before becoming intoxicated, intoxication is no defence (AG for NI v Gallagher [1963]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-duress-requirements",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "duress",
      "defence",
      "threats",
      "reasonable firmness"
    ],
    "crossCutting": false,
    "front": "What are the requirements for the defence of duress by threats?",
    "back": "D must show: (1) a threat of death or serious injury to D or a close associate, (2) the threat was operative at the time of the offence (imminent and effective), (3) a reasonable person of similar characteristics would have responded similarly (an objective test with some subjective elements — Graham [1982], Hasan [2005]). Duress is NOT available as a defence to murder (Howe [1987]) or attempted murder (Gotts [1992]).",
    "details": "R v Hasan [2005]: the defence is unavailable if D voluntarily associated with criminals and should have foreseen that they might be subjected to compulsion. The two-part Graham test: (1) was D compelled because they reasonably feared death/serious injury? (2) would a sober person of reasonable firmness have responded similarly? The jury can take into account age, pregnancy, and recognised mental illness, but not self-induced vulnerability.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-consent-brown",
    "type": "case",
    "module": "Criminal Law",
    "tags": [
      "consent",
      "non-fatal offences",
      "public policy",
      "ABH"
    ],
    "crossCutting": false,
    "front": "What did R v Brown [1994] establish about consent as a defence to non-fatal offences?",
    "back": "Consent is generally no defence where the harm amounts to actual bodily harm (ABH) or above, subject to recognised exceptions. The House of Lords held that consensual sadomasochistic activities causing ABH were not covered by any recognised exception. Public policy demanded that consent should not extend to activities whose only purpose was the infliction of injury.",
    "details": "Recognised exceptions where consent is a valid defence to ABH+: surgery, lawful sports, tattooing, ritual circumcision, body piercing, and horseplay (Jones [1986]). Contrast R v Wilson [1997] — branding with hot knife during consensual activity between spouses was analogised to tattooing. The Brown principle has been criticised as overly paternalistic.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-s47-abh",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "ABH",
      "s47",
      "OAPA 1861",
      "non-fatal offences"
    ],
    "crossCutting": false,
    "front": "What are the elements of assault occasioning actual bodily harm (s.47 OAPA 1861)?",
    "back": "Actus reus: an assault or battery that causes actual bodily harm. ABH means any hurt or injury calculated to interfere with the health or comfort of the victim — it need not be serious (R v Miller [1954]) and includes psychiatric injury (R v Chan-Fook [1994]). Mens rea: only the mens rea for the underlying assault or battery is required; no need to intend or foresee the ABH (R v Savage [1992]).",
    "details": "R v Savage [1992]: D threw beer over V, the glass slipped and cut V's wrist. D was convicted of s.47 — she intended the assault (throwing the beer) and ABH resulted; no need to prove she foresaw the ABH. Maximum sentence: 5 years. DPP v Smith [2006] — cutting hair can constitute ABH. T v DPP [2003] — momentary unconsciousness from a kick was ABH.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-s18-s20-gbh",
    "type": "distinction",
    "module": "Criminal Law",
    "tags": [
      "GBH",
      "s18",
      "s20",
      "OAPA 1861",
      "wounding"
    ],
    "crossCutting": false,
    "front": "Distinguish s.18 and s.20 of the Offences Against the Person Act 1861.",
    "back": "Both require 'grievous bodily harm' (really serious harm — DPP v Smith [1961]) or wounding (a break in both layers of skin — JCC v Eisenhower [1984]). S.20: unlawfully and maliciously wounding or inflicting GBH — mens rea is intention or recklessness as to some physical harm (Mowatt [1968]). S.18: unlawfully and maliciously wounding or causing GBH with intent — requires specific intent to cause GBH (or to resist arrest). S.18 carries a maximum of life imprisonment; s.20 a maximum of 5 years.",
    "details": "Key distinction is the mens rea: s.20 requires only foresight of some harm, while s.18 requires intention to cause GBH. S.20 uses 'inflict' while s.18 uses 'cause' — but R v Ireland/Burstow [1998] held there is no practical difference. S.18 is a specific intent offence (intoxication may be relevant); s.20 is a basic intent offence.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-theft-elements",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "theft",
      "Theft Act 1968",
      "dishonesty",
      "appropriation"
    ],
    "crossCutting": false,
    "front": "What are the five elements of theft under s.1 Theft Act 1968?",
    "back": "D must (1) dishonestly (2) appropriate (3) property (4) belonging to another (5) with the intention of permanently depriving the other of it. Appropriation (s.3): any assumption of the rights of an owner — including with consent (Gomez [1993], Hinks [2001]). 'Belonging to another' (s.5) includes anyone with possession, control, or a proprietary right or interest. Dishonesty: the Ivey v Genting Casinos [2017] test now applies.",
    "details": "Ivey test for dishonesty: (1) what was D's actual state of knowledge or belief as to the facts? (2) Was D's conduct dishonest by the standards of ordinary decent people? (This replaced the Ghosh two-stage test.) S.6: D is treated as intending to permanently deprive if they intend to treat the property as their own to dispose of regardless of the other's rights (Lloyd [1985] — borrowing is not enough unless all goodness, virtue, or practical value is taken).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-burglary-s9",
    "type": "distinction",
    "module": "Criminal Law",
    "tags": [
      "burglary",
      "s9(1)(a)",
      "s9(1)(b)",
      "Theft Act 1968",
      "entry"
    ],
    "crossCutting": false,
    "front": "Distinguish the two forms of burglary under s.9 Theft Act 1968.",
    "back": "S.9(1)(a): D enters a building (or part of a building) as a trespasser with intent to commit theft, GBH, or criminal damage therein. The intent must exist at the time of entry. S.9(1)(b): having entered a building as a trespasser, D steals or attempts to steal, or inflicts or attempts to inflict GBH. The key difference is timing: s.9(1)(a) is about intent at entry; s.9(1)(b) is about conduct after entry.",
    "details": "D must know or be reckless as to whether they are trespassing (Collins [1973]). 'Building' includes inhabited vehicles or vessels (s.9(4)). Entry need not involve the whole body — partial entry suffices (Brown [1985]: leaning through a window). Ryan [1996]: D trapped in a window was still 'entering'. S.9(1)(a) is a specific intent offence; s.9(1)(b) is hybrid.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-fraud-act",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "fraud",
      "Fraud Act 2006",
      "false representation",
      "dishonesty"
    ],
    "crossCutting": false,
    "front": "What is the offence of fraud by false representation under s.2 Fraud Act 2006?",
    "back": "D commits fraud if they (1) dishonestly make a false representation, (2) intending thereby to make a gain for themselves or another, or to cause loss to another or expose another to a risk of loss. A representation is false if it is untrue or misleading (s.2(2)). D must know the representation is or might be false (s.2(1)(b)). It is a conduct crime — no need to prove actual gain, loss, or that anyone was deceived.",
    "details": "The Fraud Act 2006 replaced the old deception offences under the Theft Acts. Three forms: fraud by false representation (s.2), fraud by failing to disclose information (s.3), and fraud by abuse of position (s.4). Representation can be express or implied, and can be made to a machine (s.2(5)). Maximum sentence: 10 years. Ivey v Genting Casinos [2017] test for dishonesty applies.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-attempt-s1",
    "type": "principle",
    "module": "Criminal Law",
    "tags": [
      "attempt",
      "Criminal Attempts Act 1981",
      "more than merely preparatory",
      "inchoate"
    ],
    "crossCutting": false,
    "front": "What are the elements of criminal attempt under s.1 Criminal Attempts Act 1981?",
    "back": "D must (1) do an act which is more than merely preparatory to the commission of the offence, (2) with the intention to commit the full offence. Recklessness as to consequences is insufficient — D must intend the substantive offence (R v Mohan [1976]). Whether the act is 'more than merely preparatory' is a question for the jury (R v Gullefer [1990]).",
    "details": "R v Geddes [1996]: D found in school toilets with a knife and rope — merely preparatory, no attempt. R v Tosti [1997]: examining a padlock with cutting equipment was more than merely preparatory. Conditional intent suffices: intending to steal 'if there is anything worth stealing' is sufficient intent (AG's References Nos 1 and 2 of 1979). Impossibility is no defence after s.1(2) CAA 1981 (R v Shivpuri [1987]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-white",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["causation", "but-for test", "R v White", "attempt"],
    "crossCutting": false,
    "front": "R v White [1910] — what did it establish about the but-for test in criminal causation?",
    "back": "The defendant must be a factual cause of the prohibited result: 'but for' the defendant's act, would the result have occurred? If the result would have occurred anyway regardless of the defendant's conduct, factual causation is not established. White was convicted of attempt only, because the victim died of natural causes before the poison could take effect.",
    "details": "D put potassium cyanide in his mother's drink. She was found dead but had died of a heart attack unrelated to the poison. Since the poison did not cause her death, the but-for test was not satisfied for murder. D was convicted of attempted murder. The case illustrates the essential first step in the two-stage causation inquiry: factual causation (but-for) followed by legal causation (was the act a substantial and operating cause?).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-pagett",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["causation", "third party", "Pagett", "involuntary act"],
    "crossCutting": false,
    "front": "R v Pagett (1983) — when does a third party's act break the chain of causation?",
    "back": "A reasonable and foreseeable act by a third party responding to the defendant's conduct does not break the chain of causation. The chain is broken only if the third party's act is 'free, deliberate and informed' (i.e. a voluntary independent choice). A reflexive, instinctive, or compelled response — such as police returning fire — is not a novus actus interveniens.",
    "details": "D used his pregnant girlfriend as a human shield while firing at police. Police returned fire and killed the girl. CA: D caused her death — the police response was a reasonably foreseeable consequence of his actions and was not a free, deliberate act. Robert Goff LJ adopted the 'reasonable response' principle from Hart & Honoré. Contrast R v Latimer (1886) (transferred malice) and R v Kennedy (No 2) [2007] (victim's free and voluntary act of self-injection broke the chain).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-cheshire",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["causation", "medical negligence", "Cheshire", "operating cause"],
    "crossCutting": false,
    "front": "R v Cheshire [1991] — when does negligent medical treatment break the chain of causation?",
    "back": "Negligent medical treatment will only break the chain of causation if it is 'so independent of the defendant's acts and in itself so potent in causing death' that the contribution of the defendant's acts is rendered insignificant. It is not necessary that the defendant's act remain the sole or even the main cause — only that it is a significant (more than negligible) cause of death.",
    "details": "D shot the victim in the leg and stomach. The victim developed respiratory problems and died from a tracheotomy complication that the hospital negligently failed to diagnose. CA: D's conviction upheld — the shooting was still a significant contributory cause even though the medical negligence was the immediate cause of death. The threshold for breaking the chain by medical treatment is very high. Compare R v Jordan [1956] where 'palpably wrong' treatment on a virtually healed wound did break the chain — described in Cheshire as a very exceptional case.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-cunningham",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["recklessness", "subjective", "Cunningham", "mens rea"],
    "crossCutting": false,
    "front": "R v Cunningham [1957] — what test for recklessness did it establish?",
    "back": "Recklessness means the defendant actually foresaw that their conduct might cause the prohibited harm, and went ahead unreasonably to take that risk ('subjective' recklessness). It is not enough that a reasonable person would have foreseen the risk — the defendant personally must have adverted to it.",
    "details": "D tore a gas meter from the wall to steal money, causing gas to leak into the neighbouring house and endanger his future mother-in-law. CCA quashed his conviction under s.23 OAPA 1861 ('maliciously administering a noxious thing') because the trial judge directed the jury that 'malicious' simply meant 'wicked', rather than requiring foresight of the risk. 'Maliciously' requires either intention or Cunningham recklessness. This subjective approach was later challenged by R v Caldwell [1982] (objective recklessness for criminal damage) but restored as the general test by R v G [2003].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-dudley-stephens",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["necessity", "murder", "Dudley and Stephens", "cannibalism"],
    "crossCutting": false,
    "front": "R v Dudley and Stephens (1884) — is necessity a defence to murder?",
    "back": "Necessity is not a defence to murder. No person has the right to preserve their own life by taking the life of an innocent person, regardless of the extremity of the circumstances. The court refused to accept that killing the weakest to save the majority could be lawfully justified.",
    "details": "Lord Coleridge CJ. Shipwrecked sailors, starving on a lifeboat, killed and ate the cabin boy (Parker) to survive. Convicted of murder. The death sentence was commuted to six months' imprisonment. The case established the absolute rule against necessity as a defence to murder, which was confirmed by the HL in R v Howe [1987] (duress also unavailable for murder). The only judicial relaxation is Re A (Conjoined Twins) [2001], where the CA allowed necessity to justify separation surgery that would kill one twin to save the other — a highly exceptional case.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-howe",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["duress", "murder", "Howe", "no defence"],
    "crossCutting": false,
    "front": "R v Howe [1987] — is duress by threats available as a defence to murder?",
    "back": "Duress is not a defence to murder, whether the defendant is a principal or a secondary party. The HL held that no threat, however extreme, can justify taking an innocent life. This overruled DPP for NI v Lynch [1975], which had allowed duress for secondary parties to murder.",
    "details": "D participated in two killings under threats from a gang leader. HL: duress is no defence. Lord Hailsham: the ordinary person of reasonable fortitude is expected to sacrifice their own life rather than kill an innocent. Confirmed in R v Gotts [1992] for attempted murder. The harshness of the rule has been criticised by the Law Commission, which recommended a partial defence reducing murder to manslaughter, but Parliament has not acted. The defence remains available for all other offences, including conspiracy to murder (controversially).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-kingston",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["intoxication", "involuntary", "Kingston", "intent"],
    "crossCutting": false,
    "front": "R v Kingston [1995] — does involuntary intoxication provide a defence if the defendant still formed the mens rea?",
    "back": "Involuntary intoxication is a defence only if it prevents the defendant from forming the required mens rea. If the defendant, despite being involuntarily intoxicated, still formed the intent for the offence, they are guilty. A drugged intent is still an intent.",
    "details": "Lord Mustill. D, a paedophile, was secretly drugged by a blackmailer and then photographed indecently assaulting a boy. D argued that he would not have committed the offence but for being drugged. HL: irrelevant — D formed the necessary intent (even if disinhibited). The law does not excuse those whose inhibitions are lowered if they still form mens rea. Contrast voluntary intoxication: for specific intent crimes, evidence of intoxication may negate mens rea (DPP v Majewski [1977]).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-gomez",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["theft", "appropriation", "Gomez", "consent"],
    "crossCutting": false,
    "front": "R v Gomez [1993] — can there be an 'appropriation' for the purposes of theft even where the owner consents?",
    "back": "Yes. An appropriation occurs whenever the defendant assumes any of the rights of an owner, regardless of whether the owner consented to the taking. Consent of the owner is irrelevant to the question of appropriation — dishonesty and intention to permanently deprive are what distinguish theft from an innocent transaction.",
    "details": "Lord Keith, following R v Lawrence [1972]. D, an assistant manager, induced the manager to accept stolen cheques in payment for goods. HL: there was an appropriation even though the manager had authorised the transaction. This very wide definition of appropriation was confirmed and extended in R v Hinks [2001]. The effect is to shift the practical inquiry almost entirely to the mens rea elements — especially dishonesty (Ivey v Genting Casinos [2017]).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-hinks",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["theft", "appropriation", "Hinks", "gifts"],
    "crossCutting": false,
    "front": "R v Hinks [2001] — can a valid gift amount to an appropriation for the purposes of theft?",
    "back": "Yes. Even a valid gift, perfected by delivery with full consent, can constitute an appropriation. An appropriation is any assumption of the rights of an owner — it is a neutral concept. Guilt depends on dishonesty and intention to permanently deprive, not on whether property was validly transferred.",
    "details": "D befriended a naive man of limited intelligence and over several months persuaded him to withdraw £60,000 from his building society and deposit it in her account. HL (3-2): the gifts were appropriations. Lord Steyn: there is no requirement that the appropriation be adverse or unauthorised. Lord Hobhouse (dissenting): the decision conflates criminal and civil law — a valid transfer of property under civil law should not be theft. The majority prioritised the deterrent function of the Theft Act.",
    "related": ["crim-gomez"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-church",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["unlawful act manslaughter", "dangerousness", "Church"],
    "crossCutting": false,
    "front": "R v Church [1966] — what is the 'dangerousness' requirement for unlawful act (constructive) manslaughter?",
    "back": "For unlawful act manslaughter, the unlawful act must be one that all sober and reasonable people would inevitably recognise as carrying a risk of some (not serious) harm to another person. This is an objective test — the defendant's own appreciation of the risk is irrelevant.",
    "details": "Edmund-Davies J. D knocked a woman unconscious during a fight, thought she was dead, and threw her body in a river where she drowned. Held: conviction upheld — the unlawful act was dangerous as judged by the reasonable person. The four elements of UAM are: (1) an intentional unlawful act; (2) that is dangerous by the Church test; (3) that causes death; (4) with the mens rea for the base offence (not murder). Refined in DPP v Newbury [1977] and R v Kennedy (No 2) [2007].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-dica",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["consent", "HIV", "Dica", "s.20 OAPA"],
    "crossCutting": false,
    "front": "R v Dica [2004] — can a person consent to the risk of contracting a serious sexual disease?",
    "back": "A person can give valid consent to the risk of contracting a serious sexual disease (such as HIV) provided they are informed of the risk. Where the complainant knows of the defendant's condition and freely consents to sexual intercourse, the defendant is not guilty of inflicting GBH under s.20 OAPA 1861. But where the defendant conceals their condition, the complainant cannot consent to a risk of which they are unaware.",
    "details": "CA (Judge LJ). D had unprotected sex with two women knowing he was HIV-positive, without telling them. Both contracted HIV. Conviction under s.20 upheld on the basis that the women had not consented to the risk. Dica distinguished R v Brown [1994] (consent to deliberate infliction of harm) from consent to the risk of harm as an incident of otherwise lawful sexual activity. Confirmed in R v Konzani [2005]: consent must be informed and willing.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-fagan",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["continuing act", "Fagan", "actus reus", "coincidence"],
    "crossCutting": false,
    "front": "Fagan v Metropolitan Police Commissioner [1969] — what is the 'continuing act' doctrine?",
    "back": "Where the actus reus is a continuing act, the mens rea need not exist at the moment the act begins — it is sufficient if the defendant forms mens rea at any point while the actus reus is still continuing. The coincidence of actus reus and mens rea is satisfied even if they do not arise simultaneously.",
    "details": "D accidentally drove onto a police officer's foot. When asked to move, D refused and turned off the engine. The Divisional Court held that driving onto the foot was a continuing act (not a completed event), so when D formed the intention to remain on the foot, the actus reus was still in progress and coincided with the mens rea for battery. Alternative to the 'transaction' principle in Thabo Meli v R [1954] and R v Church [1966], which treat a sequence of acts as one transaction.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-miller",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["Miller", "duty", "creating danger", "omission", "arson"],
    "crossCutting": false,
    "front": "R v Miller [1983] — what duty arises where a defendant accidentally creates a dangerous situation?",
    "back": "Where a defendant inadvertently creates a dangerous situation and later becomes aware of it, they are under a duty to take reasonable steps to counteract the danger. A failure to act at that point, with the requisite mens rea, satisfies the actus reus through the 'Miller principle' (sometimes called the duty from creating a dangerous situation).",
    "details": "Lord Diplock. D, a squatter, fell asleep while smoking a cigarette, which set fire to his mattress. He woke, saw the fire, but simply moved to another room and went back to sleep. The house was seriously damaged. HL: D was guilty of arson — his initial (inadvertent) act created the danger, and his subsequent failure to act when he became aware constituted the actus reus. The Miller principle is now a recognised category of duty to act alongside statutory duties, contractual duties, familial duties, and voluntary assumption of care.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-re-a-conjoined-twins",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["necessity", "conjoined twins", "Re A", "murder"],
    "crossCutting": false,
    "front": "Re A (Conjoined Twins) [2001] — how did the Court of Appeal justify the separation operation?",
    "back": "The CA permitted separation surgery that would inevitably kill the weaker twin (Mary) to save the stronger twin (Jodie), despite the general rule that necessity is no defence to murder. The three judges reached the same conclusion by different routes: Brooke LJ relied on necessity of choosing the lesser evil; Ward LJ found that Mary's continued parasitic existence constituted an unlawful threat to Jodie; Robert Walker LJ held the surgery was analogous to withdrawing life support.",
    "details": "The case has not created a general necessity defence to murder and is regarded as highly exceptional — confined to its unique facts. Brooke LJ drew on the writings of Sir James Stephen and the Canadian case of R v Perka [1984]. The decision sits uneasily alongside Dudley and Stephens [1884] and Howe [1987], which deny both necessity and duress as defences to murder. Academic commentary treats Re A as a compassionate anomaly rather than a doctrinal shift.",
    "related": ["crim-dudley-stephens", "crim-howe"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "crim-jogee",
    "type": "case",
    "module": "Criminal Law",
    "tags": ["joint enterprise", "Jogee", "parasitic accessory", "secondary liability"],
    "crossCutting": false,
    "front": "R v Jogee [2016] — how did the Supreme Court change the law on joint enterprise (parasitic accessory liability)?",
    "back": "The UKSC held that R v Chan Wing-Siu [1985] had taken a 'wrong turn': mere foresight that the principal might commit the further offence is not sufficient for secondary liability. The correct test is intention: the secondary party must intend to assist or encourage the principal to commit the offence. Foresight is evidence from which intention may be inferred, but it is not a substitute for it.",
    "details": "Lord Hughes and Lord Toulson. D and another went to a house with a knife; the other fatally stabbed the victim. Under Chan Wing-Siu / R v Powell and English [1999], D would be guilty of murder if he foresaw that stabbing was a possibility. The UKSC overruled this: the accessory must intend to encourage or assist the offence. The decision applies to all secondary liability, not only murder. Its practical impact has been debated — foresight remains powerful evidence of intent, and relatively few convictions have been overturned on appeal.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
