// Auto-generated from cards.js split. Module: Evidence
export const evidenceCards = [
  {
    "id": "11",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "hearsay",
      "exclusionary rule"
    ],
    "crossCutting": false,
    "front": "What is the hearsay rule and what is its rationale?",
    "back": "A statement made out of court is inadmissible to prove the truth of its contents. Rationale: the maker of the statement was not on oath, not subject to cross-examination, and the tribunal cannot assess demeanour. Numerous statutory and common law exceptions exist.",
    "details": "Criminal Justice Act 2003, ss.114-136 provides a statutory framework for hearsay exceptions in criminal cases. Civil Evidence Act 1995 largely abolished the hearsay rule in civil proceedings.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "15",
    "type": "application",
    "module": "Evidence",
    "tags": [
      "bad character",
      "gateway",
      "propensity"
    ],
    "crossCutting": true,
    "front": "D is charged with burglary. The prosecution wants to adduce evidence of D's three previous burglary convictions. Through which gateway(s) might this evidence be admitted?",
    "back": "CJA 2003 s.101(1)(d): relevant to an important matter in issue — here, propensity to commit offences of the kind charged (s.103(1)(a)). The court must consider whether the convictions are of the same description/category, and whether admission would have an adverse effect on fairness (s.101(3)).",
    "details": "R v Hanson [2005] — propensity can be established by a single conviction if of sufficient similarity. The fewer the convictions, the weaker the evidence of propensity. Cross-cuts Evidence with Criminal Law procedure.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "evidence-burden-standard-proof",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "burden of proof",
      "standard of proof",
      "woolmington",
      "legal burden",
      "evidential burden"
    ],
    "crossCutting": false,
    "front": "What is the general rule as to the burden and standard of proof in criminal proceedings?",
    "back": "The prosecution bears the legal burden of proving every element of the offence beyond a reasonable doubt (Woolmington v DPP [1935] — 'the golden thread'). The defendant bears only an evidential burden to raise a defence (e.g. self-defence, duress); once raised, the prosecution must disprove it beyond reasonable doubt.",
    "details": "Woolmington overruled a long-standing rule that defendants had to prove their defences. Exceptions to the golden thread exist: (a) insanity (defence has legal burden on balance of probabilities — M'Naghten's rules); (b) express statutory reverse burdens (e.g. s2 Homicide Act 1957 — diminished responsibility); (c) implied reverse burdens. Under the Human Rights Act 1998, reverse burdens are read compatibly with Art 6 ECHR (right to fair trial): a legal reverse burden may violate the presumption of innocence unless justified by proportionality (R v Johnstone [2003]; Sheldrake v DPP [2004]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "evidence-legal-vs-evidential-burden",
    "type": "distinction",
    "module": "Evidence",
    "tags": [
      "legal burden",
      "evidential burden",
      "persuasive burden",
      "discharge"
    ],
    "crossCutting": false,
    "front": "Distinguish the legal (persuasive) burden from the evidential burden in evidence law.",
    "back": "The legal burden (persuasive burden) is the obligation to prove a fact to the required standard; failure to discharge it results in losing on that issue. The evidential burden (burden of production) is merely the obligation to adduce sufficient evidence to raise an issue for the fact-finder to consider — once met, the opposing party's legal burden to disprove is engaged.",
    "details": "The distinction is practically important for defences. A defendant raising duress has only an evidential burden — they must adduce sufficient evidence that duress existed; if they do, the prosecution must then disprove it to the criminal standard. In civil proceedings, both parties may bear legal burdens on different issues (claimant — breach; defendant — contributory negligence). The standard for discharging the evidential burden is relatively low: sufficient evidence for a reasonable jury to find the fact — it goes to whether the issue should be left to the jury at all.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "evidence-competence-compellability",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "competence",
      "compellability",
      "witness",
      "spouse",
      "YJCEA 1999"
    ],
    "crossCutting": false,
    "front": "Explain the concepts of competence and compellability of witnesses in criminal trials.",
    "back": "A witness is competent if they are permitted in law to give evidence. A witness is compellable if they can be legally required to do so. All witnesses are competent (s53 YJCEA 1999) unless they cannot understand questions and give intelligible answers. Compellability differs: the accused is not compellable for the prosecution; the accused's spouse is generally compellable in cases of violence or sexual offences against them or a child (s80 PACE 1984).",
    "details": "S53 Youth Justice and Criminal Evidence Act 1999 makes all persons competent unless they fail the intelligibility test, which the judge determines on a voir dire. A child is competent if s53 is satisfied — they need not understand the nature of an oath (s55 YJCEA allows unsworn evidence). The accused: competent but not compellable for the prosecution; competent and compellable for a co-accused's defence. Failure of a competent witness to testify may attract adverse comment (s35 CJPOA 1994 — failure to give evidence). The old common law rule excluding the accused's spouse has been largely abolished.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "evidence-legal-professional-privilege",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "privilege",
      "legal professional privilege",
      "legal advice",
      "litigation",
      "without prejudice"
    ],
    "crossCutting": false,
    "front": "What is legal professional privilege and what are its two limbs?",
    "back": "Legal professional privilege (LPP) is the absolute right not to disclose confidential communications. It has two limbs: (1) Legal advice privilege — confidential communications between client and lawyer for the purpose of giving or receiving legal advice; (2) Litigation privilege — communications (including with third parties) made for the dominant purpose of anticipated or actual litigation.",
    "details": "LPP is absolute: it cannot be overridden even by court order or statute (R (Morgan Grenfell) v Special Commissioner [2002]; Three Rivers DC (No 6) [2004]). It belongs to the client, not the lawyer. Exceptions: crime-fraud exception — privilege does not attach to communications made to facilitate crime or fraud (R v Cox & Railton [1884]). Legal advice privilege covers only lawyers in their capacity as legal advisers (not accountants, even for tax advice). Litigation privilege is broader (covers communications with third parties like expert witnesses) but requires contemplated litigation. 'Without prejudice' communications in settlement negotiations are similarly protected but under a different rule.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "cross-human-rights-criminal-evidence",
    "type": "application",
    "module": "Evidence",
    "tags": [
      "ECHR",
      "Art 6",
      "fair trial",
      "reverse burden",
      "HRA 1998",
      "criminal",
      "public law"
    ],
    "crossCutting": true,
    "front": "How has Article 6 ECHR (right to a fair trial) affected the allocation of the burden of proof in criminal proceedings?",
    "back": "Art 6(2) ECHR provides a presumption of innocence. Statutory reverse burdens imposing a legal burden on the accused to prove a defence may violate Art 6(2). Courts must read such provisions compatibly under s3 HRA 1998 — usually by treating a legal burden as merely evidential (Sheldrake v DPP [2004]; R v Johnstone [2003]).",
    "details": "The ECtHR in Salabiaku v France [1988] held that presumptions of fact or law in criminal proceedings are not absolutely prohibited but must be confined within reasonable limits taking into account the importance of what is at stake and maintaining the rights of the defence. Johnstone (drug counterfeiting) — the HL held a legal burden on the accused to prove authorisation under the Trade Marks Act was compatible with Art 6 given the regulatory context. Sheldrake (terrorist offences) — a legal burden under the Terrorism Act 2000 was read down to evidential burden. The key question: is the burden proportionate and within reasonable limits? This is a cross-cutting issue between Evidence, Criminal Law, and Public Law/HRA.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-burden-proof-woolmington",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "burden of proof",
      "presumption of innocence",
      "Woolmington",
      "standard of proof"
    ],
    "crossCutting": true,
    "front": "What is the general rule on burden and standard of proof in criminal cases?",
    "back": "The prosecution bears the legal (persuasive) burden of proving the defendant's guilt beyond reasonable doubt (Woolmington v DPP [1935]). The 'golden thread' running through English criminal law is that it is for the prosecution to prove the prisoner's guilt. Exceptions: insanity (on the defendant, balance of probabilities — M'Naghten), diminished responsibility, and express statutory reverse burdens.",
    "details": "Viscount Sankey in Woolmington. The evidential burden (burden of raising an issue) may fall on the defendant for some defences — D must adduce sufficient evidence to make the issue 'live' before the prosecution must disprove it beyond reasonable doubt (e.g. self-defence). Under HRA s.6, reverse legal burdens may be 'read down' as merely evidential burdens if a legal burden would violate the presumption of innocence under Art 6(2) — R v Lambert [2002]. Cross-cuts with Criminal Law and Public Law (HRA).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-confessions-s76",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "confessions",
      "s76 PACE",
      "oppression",
      "unreliability"
    ],
    "crossCutting": false,
    "front": "Under what circumstances must a confession be excluded under s.76 PACE 1984?",
    "back": "A confession must be excluded if it was or may have been obtained (a) by oppression (s.76(2)(a)), or (b) in consequence of anything said or done which was likely to render it unreliable (s.76(2)(b)). Once the defence raises the issue, the burden is on the prosecution to prove beyond reasonable doubt that the confession was not obtained in these ways. Exclusion is mandatory if the prosecution cannot discharge this burden.",
    "details": "Oppression (s.76(8)) includes torture, inhuman or degrading treatment, and the use or threat of violence. R v Fulling [1987]: oppression requires some impropriety by the police. S.76(2)(b) is broader: R v Harvey [1988] — a confession by a woman of low intelligence influenced by hearing her lover confess was excluded. The test is objective — would the thing said or done be likely to render unreliable any confession the defendant might make?",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-s78-pace-discretion",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "s78 PACE",
      "exclusionary discretion",
      "fairness",
      "improperly obtained evidence"
    ],
    "crossCutting": false,
    "front": "What is the scope of the court's discretion to exclude evidence under s.78 PACE 1984?",
    "back": "Under s.78, the court may refuse to allow evidence on which the prosecution proposes to rely if, having regard to all the circumstances including the circumstances in which the evidence was obtained, its admission would have such an adverse effect on the fairness of the proceedings that the court ought not to admit it. This is a broad discretion applied to all types of prosecution evidence.",
    "details": "Unlike s.76 (mandatory exclusion), s.78 is discretionary. Commonly applied to: breaches of PACE Codes of Practice (failure to caution, denial of legal advice — Samuel [1988]), identification evidence obtained improperly, undercover operations, and entrapment (Looseley [2001]). The court balances the probative value of the evidence against the unfairness of admitting it. The test focuses on the fairness of the proceedings, not punishment of police misconduct.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-silence-s34-cjpoa",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "silence",
      "s34 CJPOA 1994",
      "adverse inference",
      "no comment"
    ],
    "crossCutting": false,
    "front": "When can adverse inferences be drawn from a defendant's silence under s.34 CJPOA 1994?",
    "back": "Under s.34, where a defendant relies at trial on a fact which they could reasonably have been expected to mention when questioned under caution but failed to do so, the court or jury may draw such inferences as appear proper. Conditions: (1) the defendant was questioned under caution, (2) they failed to mention a fact, (3) they later relied on that fact in their defence, (4) the fact is one they could reasonably have been expected to mention. A defendant cannot be convicted solely on an adverse inference.",
    "details": "The special caution must be given. Legal privilege is not affected — but if D relies on legal advice to remain silent, the reason for the advice may become relevant (R v Beckles [2005]). R v Hasan [2005] — the reasonableness of the failure depends on all circumstances. Condron v UK (2000) ECtHR — the jury must be directed that silence may be attributable to innocent reasons. S.35: inferences from failure to testify at trial. S.36/37: inferences from failure to account for objects/presence.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-hearsay-exceptions",
    "type": "distinction",
    "module": "Evidence",
    "tags": [
      "hearsay",
      "CJA 2003",
      "exceptions",
      "statutory gateways"
    ],
    "crossCutting": false,
    "front": "What are the main statutory exceptions to the hearsay rule under the Criminal Justice Act 2003?",
    "back": "Hearsay is admissible under CJA 2003 if: (1) s.114(1)(a) — a statutory provision makes it admissible; (2) s.114(1)(b) — a preserved common law rule (e.g. res gestae, confessions); (3) s.114(1)(c) — all parties agree; (4) s.114(1)(d) — the 'safety valve' — the court is satisfied it is in the interests of justice. Key statutory routes: s.116 — witness unavailable (dead, unfit, abroad, afraid, cannot be found); s.117 — business documents; s.119 — previous inconsistent statements; s.120 — previous consistent statements.",
    "details": "S.116 requires the maker to be identified and unavailable for a specified reason. S.114(1)(d) — the interests of justice 'safety valve' — the court considers factors including probative value, reliability, importance of the evidence, prejudice, and whether the maker can be called (s.114(2)). S.126 gives the court discretion to exclude hearsay if its admission would waste time given its value. Multiple hearsay is only admissible under s.121 in limited circumstances.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-turnbull-identification",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "identification",
      "Turnbull",
      "guidelines",
      "visual identification"
    ],
    "crossCutting": false,
    "front": "What are the Turnbull guidelines for identification evidence?",
    "back": "R v Turnbull [1977]: where the case depends wholly or substantially on visual identification evidence, the judge must warn the jury of the special need for caution. The jury should examine the circumstances of the identification using the mnemonic ADVOKATE: Amount of time, Distance, Visibility, Obstruction, Known or seen before, Any reason to remember, Time lapse, Errors or discrepancies. If the identification is of poor quality and unsupported, the judge should withdraw the case from the jury.",
    "details": "ADVOKATE: A = Amount of time under observation; D = Distance; V = Visibility (lighting, weather); O = Obstruction (anything blocking the view); K = Known (had the witness seen D before?); A = Any reason to remember; T = Time lapse since observation; E = Errors in description. Supporting evidence can include: forensic evidence, alibi evidence that fails, or another witness identifying D. The guidelines apply in both jury and bench trials.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-opinion-evidence",
    "type": "distinction",
    "module": "Evidence",
    "tags": [
      "opinion evidence",
      "expert",
      "lay witness",
      "admissibility"
    ],
    "crossCutting": false,
    "front": "Distinguish the admissibility of expert opinion evidence from lay opinion evidence.",
    "back": "Expert opinion is admissible where the issue requires expertise beyond the knowledge of the jury and the witness has the relevant expertise. The expert must provide their opinion with reasons and the underlying data. Lay opinion is generally inadmissible, but exceptions exist for matters of common perception: identification, age estimation, handwriting, speed of vehicles, and whether someone appeared drunk or emotionally distressed.",
    "details": "Expert evidence: the expert's duty is to the court, not the party instructing them (CrimPR Part 19). R v Turner [1975]: no expert evidence on how an ordinary person would react to provocation — that is within the jury's experience. But expert evidence is admissible on abnormal mental states. R v Bonython [1984]: the field must be a recognised body of expertise. The court retains a gatekeeping function — s.30 CJA 1988; common law reliability assessments.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-bad-character-defendant",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "bad character",
      "CJA 2003",
      "s101",
      "gateways"
    ],
    "crossCutting": false,
    "front": "Through which gateways can evidence of a defendant's bad character be admitted under s.101 CJA 2003?",
    "back": "Seven gateways: (a) all parties agree; (b) the defendant adduces it; (c) it is important explanatory evidence; (d) it is relevant to an important matter in issue between D and prosecution (e.g. propensity — s.103); (e) it has substantial probative value in relation to an important matter between D and a co-defendant; (f) it corrects a false impression given by D; (g) D has attacked another person's character. The court must not admit under gateways (d) or (g) if the adverse effect on fairness would be too great (s.101(3)).",
    "details": "Gateway (d) is the most commonly used. S.103(1)(a): propensity to commit offences of the kind charged. S.103(1)(b): propensity to be untruthful. R v Hanson [2005]: propensity may be established by previous convictions of the same description or category, but few convictions may not establish propensity. The judge must give a clear direction on the limited purpose for which bad character evidence may be used.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-competence-compellability",
    "type": "distinction",
    "module": "Evidence",
    "tags": [
      "competence",
      "compellability",
      "witness",
      "spouse",
      "accused"
    ],
    "crossCutting": false,
    "front": "Distinguish competence from compellability of witnesses.",
    "back": "Competence is the legal capacity to give evidence — all persons are competent unless they cannot understand questions or give intelligible answers (s.53 YJCEA 1999). Compellability is the obligation to give evidence if called — a compellable witness can be summoned and punished for refusing to testify. The accused is always competent for the defence but never compellable (s.53(1) and s.53(4)). The accused is not competent for the prosecution.",
    "details": "Spouse/civil partner: competent for all parties (s.53(1)). Compellable for the prosecution only for specified offences under s.80 PACE (assault/injury to spouse or person under 16, or sexual offence against person under 16). Children: competent if they can understand questions and give intelligible answers (s.53(3) YJCEA 1999). Expert witnesses are always competent and compellable.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-privilege-self-incrimination",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "privilege",
      "self-incrimination",
      "legal professional privilege"
    ],
    "crossCutting": false,
    "front": "What is the privilege against self-incrimination and how does legal professional privilege differ?",
    "back": "The privilege against self-incrimination allows a witness to refuse to answer a question if the answer might expose them to criminal proceedings. It does not apply to the accused (who has the separate right to silence). Legal professional privilege (LPP) is distinct: it protects (a) communications between lawyer and client for the purpose of giving/receiving legal advice (legal advice privilege), and (b) communications made for the dominant purpose of litigation (litigation privilege). LPP belongs to the client and cannot be overridden except in the crime/fraud exception.",
    "details": "LPP is a fundamental right — R v Derby Magistrates' Court, ex p B [1996]: no balancing exercise; the privilege is absolute once established. The crime/fraud exception: if the communication is made to facilitate crime or fraud, it is not privileged (R v Cox and Railton [1884]). 'Without prejudice' communications are also privileged from disclosure in subsequent proceedings.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-public-interest-immunity",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "PII",
      "public interest immunity",
      "disclosure",
      "balancing"
    ],
    "crossCutting": true,
    "front": "What is public interest immunity (PII) and how does it apply to disclosure?",
    "back": "PII allows the Crown to withhold relevant evidence from disclosure where the public interest in non-disclosure outweighs the public interest in the administration of justice. The court conducts a balancing exercise. Categories include: national security, police informant identity, diplomatic communications, and sensitive investigation techniques. The decision is ultimately for the judge, not the minister.",
    "details": "R v H and C [2004]: the HL set out principles for handling PII in criminal cases — the material must be reviewed by the judge; alternatives to full disclosure should be considered (redaction, summaries, special counsel). Conway v Rimmer [1968]: the HL rejected the Crown's claim to absolute immunity and established the judicial balancing test. The prosecution has a continuing duty of disclosure under CPIA 1996. Cross-cuts with Public Law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-cross-examination-purpose",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "cross-examination",
      "credit",
      "hostile witness",
      "previous inconsistent"
    ],
    "crossCutting": false,
    "front": "What are the purposes and limits of cross-examination?",
    "back": "Cross-examination serves two purposes: (1) to elicit evidence favourable to the cross-examiner's case, and (2) to undermine the witness's credibility. The rule in Browne v Dunn (1893) requires that a party who intends to contradict a witness must put their version of events to the witness in cross-examination. Leading questions are permitted. The court has discretion to disallow questions that are oppressive, repetitive, or irrelevant.",
    "details": "S.100/101 CJA 2003: cross-examination about a non-defendant's bad character requires leave. S.41 YJCEA 1999: restricts cross-examination of complainants about sexual history — only admissible with leave and if exclusion would render the verdict unsafe. Previous inconsistent statements can be put to a witness under ss.4-5 Criminal Procedure Act 1865. If proved, the prior statement is admissible as evidence of the truth of its contents (s.119 CJA 2003).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-res-gestae",
    "type": "case",
    "module": "Evidence",
    "tags": [
      "res gestae",
      "hearsay exception",
      "spontaneous statement",
      "Andrews"
    ],
    "crossCutting": false,
    "front": "When is a statement admissible as part of the res gestae?",
    "back": "Under the preserved common law exception (s.118(1) CJA 2003, rule 4), a statement is admissible as part of the res gestae if it was made by a person so emotionally overpowered by an event that the possibility of concoction or distortion can be disregarded. The statement must be so closely associated with the event that the mind of the declarant was still dominated by it (R v Andrews [1987]).",
    "details": "R v Andrews [1987]: the HL set out the test — the trial judge must consider whether the circumstances were such that the declarant's mind was still dominated by the event and the possibility of error or fabrication can be disregarded. Factors: time elapsed, whether there was an opportunity for fabrication, the emotional state of the declarant. Also covers statements of physical or mental state, and statements accompanying an act.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-special-measures",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "special measures",
      "vulnerable witness",
      "YJCEA 1999"
    ],
    "crossCutting": false,
    "front": "What special measures are available for vulnerable witnesses under the Youth Justice and Criminal Evidence Act 1999?",
    "back": "Special measures include: (1) screens (s.23), (2) live TV link (s.24), (3) evidence given in private (s.25), (4) removal of wigs and gowns (s.26), (5) video-recorded evidence-in-chief (s.27), (6) video-recorded cross-examination (s.28), (7) examination through an intermediary (s.29), (8) aids to communication (s.30). Eligible witnesses include children under 18, those with mental or physical disorders, and witnesses in fear or distress about testifying.",
    "details": "S.16: witnesses eligible by reason of age or incapacity. S.17: witnesses eligible by reason of fear or distress. For child witnesses in sexual offence and violence cases, primary rule: evidence-in-chief by video recording and cross-examination by live link. S.28 (video-recorded cross-examination pre-trial) has been rolled out nationally. The accused is not eligible for special measures when giving evidence (with limited exceptions for live link under s.33A).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-character-non-defendant",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "bad character",
      "non-defendant",
      "s100 CJA 2003",
      "witness"
    ],
    "crossCutting": false,
    "front": "When can evidence of a non-defendant's bad character be admitted under s.100 CJA 2003?",
    "back": "Evidence of a non-defendant's bad character (e.g. a prosecution witness) is admissible only if: (a) it is important explanatory evidence, (b) it has substantial probative value in relation to a matter in issue and is of substantial importance in the context of the case as a whole, or (c) all parties agree. Leave of the court is required unless all parties agree.",
    "details": "S.100 provides greater protection for non-defendants than s.101 provides for defendants — the threshold is 'substantial probative value' rather than just relevance. R v Brewster [2010]: the CA emphasised that s.100 applications must identify precisely which 'matter in issue' the evidence is relevant to. 'Bad character' is defined in s.98 as evidence of, or a disposition towards, misconduct — excluding evidence related to the offence charged or connected offences.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-disclosure-prosecution",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "disclosure",
      "CPIA 1996",
      "unused material",
      "fair trial"
    ],
    "crossCutting": true,
    "front": "What is the prosecution's duty of disclosure under the Criminal Procedure and Investigations Act 1996?",
    "back": "Under s.3 CPIA 1996 (as amended), the prosecution must disclose to the defence any material which has not been previously disclosed and which might reasonably be considered capable of undermining the prosecution case or assisting the defence case. This is a continuing duty (s.7A). The disclosure officer reviews all material gathered in the investigation and schedules it for the prosecutor's consideration.",
    "details": "The Attorney General's Guidelines on Disclosure (2020) supplement the statute. The defence must then provide a defence statement (s.5/6) setting out the nature of the defence and issues of fact. Failure to comply may lead to adverse inferences (s.11). R v H and C [2004]: PII claims must be scrutinised carefully. Miscarriages of justice have occurred due to disclosure failures — the R v Liam Allan (2017) case led to major reforms. Cross-cuts with Criminal Law procedure and Evidence.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-examination-chief-rules",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "examination-in-chief",
      "leading questions",
      "previous consistent statements"
    ],
    "crossCutting": false,
    "front": "What are the key rules governing examination-in-chief?",
    "back": "In examination-in-chief: (1) leading questions are generally not permitted on matters in dispute — the witness must give evidence in their own words. (2) A party may not impeach the credit of their own witness unless the witness is declared hostile (s.3 Criminal Procedure Act 1865). (3) Previous consistent statements (self-serving statements) are generally inadmissible, subject to exceptions under s.120 CJA 2003: recent complaint, statements rebutting fabrication, and statements used to refresh memory.",
    "details": "S.120(4)-(7) CJA 2003: previous consistent statements are admissible as evidence of truth if: (a) the witness identifies or describes a person/object (s.120(5)); (b) the statement was made when fresh in memory and the witness cannot now remember the matter well enough to give oral evidence (s.120(6)); (c) a complaint was made about the offence as soon as could reasonably be expected (s.120(4)(7)). Memory refreshing: ss.139 CJA 2003 — a witness may refresh memory from a document made or verified contemporaneously.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-corroboration-warning",
    "type": "principle",
    "module": "Evidence",
    "tags": [
      "corroboration",
      "Makanjuola",
      "judicial warning",
      "lies"
    ],
    "crossCutting": false,
    "front": "Is corroboration required in criminal cases and when should the judge give a warning?",
    "back": "Since s.32 CJPEA 1994 abolished the mandatory corroboration warning for accomplices and complainants in sexual cases, corroboration is not generally required. However, under R v Makanjuola [1995], the judge retains discretion to give a warning about the reliability of a particular witness where there is an evidential basis for doing so. The nature and strength of the warning is at the judge's discretion.",
    "details": "A 'Lucas direction' is required when the prosecution relies on lies by the defendant as evidence of guilt: R v Lucas [1981] — the jury must be warned that people lie for many reasons (shame, panic, to protect others) and that a lie does not necessarily indicate guilt. The judge should identify the specific lie and the evidence that proves it is a lie. A Turnbull warning (identification) remains mandatory where appropriate.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-confessions-s76-detail",
    "type": "application",
    "module": "Evidence",
    "tags": ["confession", "s76 PACE", "oppression", "unreliability", "exclusion"],
    "crossCutting": false,
    "front": "D confesses to robbery after being questioned for 14 hours without food, water, or access to a solicitor. The prosecution seeks to rely on the confession. Should it be excluded?",
    "back": "Likely yes, under s.76(2)(a) and/or (b) PACE 1984. The prolonged questioning without basic needs and denial of legal advice may constitute oppression (s.76(2)(a)) or, alternatively, something said or done likely to render the confession unreliable (s.76(2)(b)). Once the defence raises the issue, the prosecution must prove beyond reasonable doubt that the confession was not so obtained. The court may also exercise discretion under s.78 to exclude if admission would adversely affect the fairness of proceedings.",
    "details": "S.76(8) defines oppression to include torture, inhuman or degrading treatment, and the use or threat of violence. R v Fulling [1987]: oppression requires some impropriety — it bears its ordinary dictionary meaning (exercise of authority in a burdensome, harsh, or wrongful manner). PACE Code C requires: adequate breaks, refreshments, and access to legal advice (s.58 PACE). Breach of Code C does not automatically exclude the confession but is a significant factor under s.78. R v Samuel [1988]: denial of access to a solicitor led to exclusion under s.78.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-entrapment-looseley",
    "type": "case",
    "module": "Evidence",
    "tags": ["entrapment", "abuse of process", "s78 PACE", "Looseley"],
    "crossCutting": false,
    "front": "How does English law deal with evidence obtained through entrapment?",
    "back": "Entrapment is not a substantive defence in English law, but evidence obtained through entrapment may be excluded under s.78 PACE 1984, or the proceedings may be stayed as an abuse of process. R v Looseley [2001] (HL): the court must ask whether the police did no more than present the defendant with an unexceptional opportunity to commit a crime, or whether they instigated the offence by luring the defendant into conduct they would not otherwise have engaged in. If the latter, a stay of proceedings is the appropriate remedy.",
    "details": "Lord Hoffmann: the police may use covert techniques (test purchases, undercover officers) to detect crime, but they must not cause crime that would not otherwise have occurred. Factors: was the defendant predisposed? Was the police conduct proportionate and authorised? Did the officer go beyond providing an opportunity? Teixeira de Castro v Portugal (1998) ECtHR: entrapment may violate Art 6 ECHR (right to a fair trial). The distinction is between 'unexceptional opportunity' (legitimate) and 'active instigation' (abuse of process). A stay of proceedings is a stronger remedy than exclusion of evidence — it halts the prosecution entirely.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-lucas-direction-lies",
    "type": "principle",
    "module": "Evidence",
    "tags": ["Lucas direction", "lies", "consciousness of guilt", "jury direction"],
    "crossCutting": false,
    "front": "When must a Lucas direction be given regarding a defendant's lies?",
    "back": "Under R v Lucas [1981], where the prosecution relies on the defendant's lies as evidence of guilt (indicating 'consciousness of guilt'), the judge must direct the jury that: (1) the lie must be deliberate; (2) it must relate to a material issue; (3) there must be a reason to reject the defendant's explanation for the lie; and (4) people lie for many innocent reasons (shame, panic, to protect others, confusion) — a lie does not necessarily indicate guilt of the offence charged.",
    "details": "The direction prevents the jury from reasoning: 'D lied, therefore D is guilty.' The prosecution must identify the specific lie and prove it is a lie (usually by independent evidence). A Lucas direction is required only where the prosecution specifically relies on the lie as probative of guilt — not where the lie is merely part of the general case. R v Burge and Pegg [1996]: the CA set out the circumstances where a Lucas direction is needed. If the lie is trivial or peripheral, no direction is required. The direction is also relevant where D's alibi is rejected — the jury must be told that a false alibi does not prove guilt.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-dock-identification",
    "type": "principle",
    "module": "Evidence",
    "tags": ["identification", "dock identification", "PACE Code D", "identification procedure"],
    "crossCutting": false,
    "front": "What identification procedures are required under PACE Code D and why is dock identification problematic?",
    "back": "PACE Code D requires that where identification is disputed, the police should hold an identification procedure: (1) video identification (preferred — Code D para 3.14); (2) identification parade; (3) group identification; (4) confrontation (only where the suspect refuses others). A 'dock identification' — where the witness identifies the defendant for the first time in the dock at trial — is highly unreliable and generally inadmissible without a prior Code D procedure, because the defendant is obviously the person in the dock.",
    "details": "R v Forbes [2001]: the HL held that a breach of Code D (failure to hold an identification parade) does not automatically render the identification evidence inadmissible, but the court must consider exclusion under s.78 PACE. The reliability of the identification is assessed using the Turnbull guidelines. Video identification has become the standard method — it is less confrontational and less prone to suggestion. Code D para 3.12: if the suspect is 'known' (the witness claims to know them), an identification procedure may still be required if the suspect disputes being the person the witness saw.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-similar-fact-dpp-v-p",
    "type": "case",
    "module": "Evidence",
    "tags": ["similar fact", "DPP v P", "propensity", "pre-CJA 2003"],
    "crossCutting": false,
    "front": "How did the common law approach to similar fact evidence develop before the CJA 2003?",
    "back": "At common law, evidence of the defendant's other misconduct was generally inadmissible because its prejudicial effect outweighed its probative value. The leading case DPP v P [1991] (HL) held that similar fact evidence is admissible if its probative value is sufficiently great to make it just to admit it despite its prejudicial effect. No special category of 'striking similarity' is required — the question is simply whether the evidence is more probative than prejudicial. The CJA 2003 ss.98-113 replaced this common law framework with a statutory scheme.",
    "details": "Makin v AG for New South Wales [1894] (PC) established the basic rule: evidence of other misconduct is inadmissible to show propensity/bad disposition, but admissible if relevant to a specific issue (identity, system, rebuttal of defence). DPP v Boardman [1975]: required 'striking similarity' for admissibility. DPP v P relaxed this — Lord Mackay held that Boardman's 'striking similarity' was just one way evidence might be sufficiently probative; it was not an essential requirement. The CJA 2003 now governs: s.101 provides seven gateways for admitting bad character evidence, with s.101(1)(d) (propensity) being the most commonly used.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-propensity-hanson",
    "type": "case",
    "module": "Evidence",
    "tags": ["propensity", "R v Hanson", "gateway d", "s101(1)(d)", "bad character"],
    "crossCutting": false,
    "front": "What guidance did R v Hanson [2005] give on establishing propensity under s.101(1)(d) CJA 2003?",
    "back": "The Court of Appeal held that when considering whether to admit bad character evidence to show propensity under s.101(1)(d)/s.103(1)(a): (1) propensity to commit offences of the kind charged can be established by previous convictions of the same description or category, but few previous convictions may not establish propensity; (2) a single previous conviction will rarely be sufficient unless it shows a significant degree of similarity; (3) the court must consider the overriding obligation of fairness (s.101(3)) — admission must not have such an adverse effect on the fairness of proceedings that it ought not to be admitted.",
    "details": "Rose LJ set out three questions: (1) Does the defendant's history establish a propensity to commit offences of the kind charged? (2) If so, does that propensity make it more likely that the defendant committed the offence charged? (3) Would it be unjust to rely on the convictions, and would proceedings be unfair if they were admitted? Old or single convictions may have less weight. The judge must give clear directions to the jury about the limited purpose for which propensity evidence may be used — it does not prove guilt but is one factor to consider. R v Tully [2006]: even where propensity is established, the evidence may still be excluded under s.101(3) if unfair.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-hearsay-definition-s114",
    "type": "principle",
    "module": "Evidence",
    "tags": ["hearsay", "definition", "s114 CJA 2003", "purpose", "implied assertion"],
    "crossCutting": false,
    "front": "How is hearsay defined under the CJA 2003 and does it cover implied assertions?",
    "back": "S.114(1) CJA 2003: a statement not made in oral evidence in the proceedings is admissible as evidence of any matter stated only if it falls within a statutory exception. S.115(3): a 'matter stated' is one that the maker of the statement intended to cause the hearer to believe or to act on. This means implied assertions (where the maker did not intend to communicate the fact in question) are not hearsay under the CJA 2003 — reversing the common law position in Wright v Tatham (1837).",
    "details": "Wright v Tatham (1837): letters written to a testator, offered to show the writers believed him competent, were hearsay — the common law treated implied assertions as hearsay. The CJA 2003 changed this by focusing on the maker's purpose: if the maker did not intend to assert the matter, it is not hearsay. Example: a text message saying 'meet me at the warehouse at 9' is hearsay if offered to prove the meeting occurred, but the fact that the sender knew the warehouse location is an implied assertion — not hearsay under the CJA 2003 because the sender did not intend to assert that fact to the recipient. R v Singh [2006]: the CA confirmed the purposive definition.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-s116-unavailable-witness",
    "type": "principle",
    "module": "Evidence",
    "tags": ["s116 CJA 2003", "absent witness", "hearsay exception", "fear"],
    "crossCutting": false,
    "front": "When is a hearsay statement admissible under s.116 CJA 2003 because the witness is unavailable?",
    "back": "Under s.116, a statement by an identified person is admissible if: (1) the person would have been a competent witness; and (2) they are unavailable for one of five specified reasons: (a) dead; (b) unfit due to bodily or mental condition; (c) outside the UK and it is not reasonably practicable to secure attendance; (d) cannot be found despite reasonable steps; (e) does not give evidence through fear and the court gives leave. For fear (s.116(2)(e)), the court must consider the statement's importance and whether special measures could enable the witness to testify.",
    "details": "S.116(2)(e) — fear: broadly defined to include fear of death, injury, financial loss, or any other fear (s.116(3)). R v Horncastle [2009] (SC): the SC upheld the admissibility of statements by frightened or deceased witnesses under s.116, holding it was compatible with Art 6 ECHR even where the statement was the 'sole or decisive' evidence — the CJA 2003's counterbalancing safeguards (s.124 credibility, s.125 stopping the case, s.126 discretion) were sufficient. Al-Khawaja v UK (2011) ECtHR Grand Chamber: agreed that the sole/decisive rule was not absolute if there were sufficient counterbalancing factors.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-right-to-silence-history",
    "type": "principle",
    "module": "Evidence",
    "tags": ["right to silence", "privilege against self-incrimination", "CJPOA 1994", "ECHR"],
    "crossCutting": false,
    "front": "What is the scope of the right to silence in English criminal proceedings?",
    "back": "The right to silence has several aspects: (1) the privilege against self-incrimination — no one is obliged to answer questions or provide information that may incriminate them; (2) the right not to testify at trial — the defendant is competent but not compellable (s.35 CJPOA 1994 allows adverse inferences from failure to testify); (3) the right to remain silent during police questioning — but ss.34, 36, 37 CJPOA 1994 allow adverse inferences from silence in specified circumstances. The right is not absolute — it is balanced against the interests of justice.",
    "details": "Pre-1994, no adverse inferences could be drawn from silence (the common law right). The CJPOA 1994 curtailed this significantly. S.34: inferences from failure to mention facts later relied on at trial. S.35: inferences from failure to testify. S.36: inferences from failure to account for objects/substances/marks. S.37: inferences from failure to account for presence at a particular place. Murray v UK (1996) ECtHR: drawing adverse inferences from silence does not per se violate Art 6 ECHR, but the right to silence is at the 'heart' of the notion of a fair trial. A conviction cannot be based solely or mainly on silence (s.38(3) CJPOA 1994).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-exclusion-illegally-obtained",
    "type": "principle",
    "module": "Evidence",
    "tags": ["illegally obtained evidence", "s78 PACE", "real evidence", "reliability"],
    "crossCutting": false,
    "front": "Is evidence that was obtained illegally automatically inadmissible in English criminal proceedings?",
    "back": "No. English law does not have an automatic exclusionary rule for illegally or improperly obtained evidence. The general rule is that relevant evidence is admissible regardless of how it was obtained (R v Sang [1980]). However, the court has discretion under s.78 PACE 1984 to exclude evidence if its admission would have such an adverse effect on the fairness of proceedings that it ought not to be admitted. For confessions, the mandatory exclusion under s.76 PACE applies. Real (physical) evidence is rarely excluded even if illegally obtained, because its reliability is not affected by the manner of obtaining it.",
    "details": "R v Sang [1980] (HL): a judge has no discretion to exclude admissible evidence merely because it was obtained improperly — the discretion is limited to ensuring a fair trial. S.78 PACE broadened this discretion significantly. R v Khan [1997]: secretly recorded conversations obtained by police trespass and in breach of Art 8 ECHR were admissible — the breach went to admissibility weight, not exclusion. The ECtHR approach (Schenk v Switzerland [1988]): the Convention does not require exclusion of illegally obtained evidence provided the proceedings as a whole are fair. Contrast the US 'fruit of the poisonous tree' doctrine — English law prioritises reliability and trial fairness over deterring police misconduct.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-sexual-history-s41",
    "type": "principle",
    "module": "Evidence",
    "tags": ["s41 YJCEA 1999", "sexual history", "rape shield", "R v A"],
    "crossCutting": false,
    "front": "How does s.41 YJCEA 1999 restrict cross-examination about a complainant's sexual history?",
    "back": "S.41 provides that in sexual offence trials, no evidence or question about the complainant's sexual behaviour may be adduced or asked except with leave of the court. Leave may only be granted if: (1) the evidence relates to a specific instance of sexual behaviour; and (2) it falls within one of the statutory gateways: (a) the issue is not consent; (b) it is relevant to consent and the behaviour took place at or about the same time as the alleged offence; (c) it is so similar that it cannot reasonably be explained as a coincidence; or (d) it rebuts prosecution evidence. A refusal of leave must not render the verdict unsafe.",
    "details": "R v A (No 2) [2001] (HL): the HL used s.3 HRA 1998 to read s.41 compatibly with Art 6 — evidence of a prior sexual relationship between the defendant and complainant that is so relevant to consent that excluding it would endanger the fairness of the trial must be admitted. Lord Steyn: s.41 must be construed to allow evidence where it is 'so relevant to the issue of consent that to exclude it would endanger the fairness of the trial.' This represented a significant judicial modification of Parliament's restrictive intention. The 'rape shield' aims to prevent 'twin myths' reasoning: that a sexually experienced complainant is more likely to have consented or is less credible.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-hostile-witness",
    "type": "principle",
    "module": "Evidence",
    "tags": ["hostile witness", "unfavourable witness", "s3 CPA 1865", "cross-examination"],
    "crossCutting": false,
    "front": "Distinguish a hostile witness from an unfavourable witness.",
    "back": "An unfavourable witness gives evidence that does not support the calling party's case — but they are answering honestly. The calling party cannot cross-examine their own unfavourable witness. A hostile witness is one who does not wish to tell the truth or is not making a genuine attempt to do so. If declared hostile by the judge, the calling party may cross-examine the witness (including putting leading questions and previous inconsistent statements) under s.3 Criminal Procedure Act 1865.",
    "details": "The judge has discretion to declare a witness hostile based on their demeanour, refusal to answer, or evidence contradicting their previous statement. R v Thompson (1976): the test is whether the witness is not desirous of telling the truth to the court. If a prior inconsistent statement is proved under s.3 CPA 1865, it becomes admissible as evidence of the truth of its contents under s.119 CJA 2003. This is a significant change from the old common law rule where prior inconsistent statements were only relevant to credibility, not as evidence of the facts stated.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-character-d-attacks-witness",
    "type": "application",
    "module": "Evidence",
    "tags": ["gateway g", "s101(1)(g)", "attack on character", "bad character"],
    "crossCutting": false,
    "front": "D is charged with assault. In cross-examination, D accuses the prosecution witness (the victim) of being a known liar and drug dealer. Can the prosecution now adduce D's previous convictions?",
    "back": "Yes, through gateway (g) of s.101(1) CJA 2003: the defendant has made an attack on another person's character. An 'attack' includes giving evidence imputing that another person has committed an offence or has behaved in a reprehensible way (s.106). By accusing the witness of being a liar and drug dealer, D has attacked their character, opening the gateway for the prosecution to adduce D's bad character. However, the court must not admit under gateway (g) if admission would have such an adverse effect on fairness that it ought not to be admitted (s.101(3)).",
    "details": "Gateway (g) effectively penalises defendants who attack prosecution witnesses — it allows the jury to assess D's credibility with knowledge of their own record. R v Lamaletie [2008]: the CA confirmed that the admission should usually relate to credibility (propensity to be untruthful) rather than propensity to commit the offence. The judge must give a clear direction about the limited purpose for which the evidence is admitted. Note: merely denying the offence or putting the prosecution to proof is not an 'attack' — the defendant must go further and impugn the character of a witness. Gateway (f) (correcting a false impression) is a related but distinct gateway.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "ev-hearsay-business-docs-s117",
    "type": "principle",
    "module": "Evidence",
    "tags": ["s117 CJA 2003", "business document", "hearsay exception", "reliability"],
    "crossCutting": false,
    "front": "When is a statement in a business document admissible as hearsay under s.117 CJA 2003?",
    "back": "Under s.117, a statement contained in a document is admissible if: (1) the document was created or received in the course of a trade, business, profession, or other occupation, or as the holder of a paid or unpaid office; (2) the person who supplied the information (the 'relevant person') had or may reasonably be supposed to have had personal knowledge of the matters dealt with; and (3) each person through whom the information was supplied received it in the course of a trade, business, etc. If the statement was prepared for criminal proceedings, additional conditions apply (s.117(5)).",
    "details": "S.117 is particularly important for documentary evidence: business records, medical notes, bank statements, phone records. S.117(5): where the statement was prepared for the purposes of pending or contemplated criminal proceedings, it is only admissible if: the relevant person is unavailable for a s.116 reason, or the relevant person cannot reasonably be expected to recollect the matters. This prevents the prosecution from routinely creating hearsay documents in lieu of live testimony. The court retains discretion to exclude under s.126 if admission would waste time given its value.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
