// Auto-generated from cards.js split. Module: Jurisprudence
export const jurisprudenceCards = [
  {
    "id": "12",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": [
      "positivism",
      "natural law"
    ],
    "crossCutting": false,
    "front": "Distinguish legal positivism from natural law theory.",
    "back": "Legal positivism: law is a social fact — its validity depends on its source (enacted by legitimate authority), not its moral content. Natural law: law derives authority from morality — an unjust law is no law at all (lex iniusta non est lex).",
    "details": "Positivism: Austin (command theory), Hart (rule of recognition), Kelsen (Grundnorm). Natural law: Aquinas, Fuller (inner morality of law — 8 principles), Finnis (basic goods). Hart-Fuller debate is foundational.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-austin-command-theory",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Austin",
      "command theory",
      "legal positivism",
      "sovereign",
      "sanction",
      "analytical jurisprudence"
    ],
    "crossCutting": false,
    "front": "State Austin's command theory of law and its main criticisms.",
    "back": "Austin (The Province of Jurisprudence Determined, 1832): law is the command of the sovereign — a determinate person or body habitually obeyed and who does not habitually obey others. Commands are backed by the threat of a sanction. Legal validity depends on pedigree (who commanded it), not moral merit.",
    "details": "Criticisms: (1) Hart — the command model cannot explain laws conferring powers (contract, property, will-making), constitutional rules limiting the sovereign, or customary law; it confuses being obliged (fear of sanction) with having an obligation (normative reason). (2) The idea of a single sovereign is unrealistic in federal or constitutional systems. (3) Dworkin — law includes principles, not just rules issuing from commands. (4) Hart's concept of 'habit of obedience' is too sociologically crude — it cannot explain continuity and persistence of law beyond the reigning sovereign. Austin's reductive clarity was influential in separating law from morality as a discipline.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hart-rule-of-recognition",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Hart",
      "rule of recognition",
      "primary rules",
      "secondary rules",
      "The Concept of Law",
      "internal point of view"
    ],
    "crossCutting": false,
    "front": "Explain Hart's distinction between primary and secondary rules and the role of the rule of recognition.",
    "back": "Hart (The Concept of Law, 1961): primary rules impose obligations on conduct (criminal, tort). Secondary rules are power-conferring: rules of recognition (identify valid law), rules of change (power to alter primary rules), and rules of adjudication (determine legal disputes). The rule of recognition is the ultimate criterion of legal validity, accepted from an 'internal point of view' by officials.",
    "details": "Hart developed this to overcome the deficiencies of Austin's command theory. A simple society may have only primary rules — uncertainty, static quality, and inefficiency are remedied by introducing secondary rules. The rule of recognition in the UK is typically formulated as 'what the Queen in Parliament enacts is law'. It is not itself validated by any further rule — it is presupposed as a social fact accepted by officials. The 'internal point of view' is key: officials do not merely comply with the rule; they use it as a standard of criticism ('that is not valid law'). Dworkin criticised Hart's model as a 'rule model' incapable of explaining the role of principles in adjudication (soft positivism vs Dworkin's third theory).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-fuller-inner-morality",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Fuller",
      "inner morality of law",
      "eight desiderata",
      "procedural natural law",
      "The Morality of Law"
    ],
    "crossCutting": false,
    "front": "What are Fuller's eight requirements of the inner morality of law?",
    "back": "Fuller (The Morality of Law, 1964) argued that law has an internal (procedural) morality of eight requirements: (1) generality; (2) promulgation (public); (3) non-retroactivity; (4) clarity; (5) consistency (no contradictions); (6) possibility of compliance; (7) stability; (8) congruence between rules as announced and as administered. Serious failure on any criterion produces 'not a bad legal system but no legal system at all'.",
    "details": "Fuller used his hypothetical King Rex — who violated each requirement in turn — to illustrate how each failure undermines law's claim to be law at all. His point: there is an internal connection between law and morality, not in its substantive aims (external morality) but in its formal requirements of governance. Hart's response: these are just requirements for an efficient instrument — a Nazi law published, clear, and consistent is still law even if immoral. Fuller's contribution was to show that procedural fairness is not merely instrumental: it connects to respect for human agency (persons as rational actors who can plan their conduct). Relevance today: rule of law doctrine, Constitutional Reform Act 2005.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-dworkin-principles-vs-rules",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": [
      "Dworkin",
      "principles",
      "rules",
      "hard cases",
      "rights thesis",
      "Taking Rights Seriously"
    ],
    "crossCutting": false,
    "front": "How does Dworkin distinguish rules from principles, and why does this matter for adjudication?",
    "back": "Rules apply in an all-or-nothing fashion — if the conditions are met, the legal consequence follows, or the rule is inapplicable. Principles have dimension of weight — they count in favour of a decision without conclusively determining it, and may be outweighed by other principles. In hard cases judges do not exercise discretion but are bound by pre-existing rights discoverable through principled reasoning (the rights thesis) (Dworkin, Taking Rights Seriously, 1977).",
    "details": "Dworkin's attack on positivism centred on Riggs v Palmer (1889): a murderer sought to inherit under his grandfather's will — the NY court used the principle 'no man shall profit from his own wrong' despite no rule against it. This cannot be explained by Hart's pedigree test for validity. Hercules — Dworkin's ideal judge — constructs the theory that best fits and justifies the body of law (law as integrity). The 'one right answer' thesis: in hard cases there is still one correct answer discoverable by the right interpretive method, even if human judges cannot always find it. Critics (Hart, Raz): this is too optimistic about law's coherence; many hard cases are genuinely indeterminate.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-cls-critique",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Critical Legal Studies",
      "CLS",
      "indeterminacy",
      "ideology",
      "Unger",
      "trashing"
    ],
    "crossCutting": false,
    "front": "What is the central critique offered by Critical Legal Studies (CLS) and what methods do CLS scholars employ?",
    "back": "CLS holds that law is radically indeterminate — legal doctrine cannot determine outcomes because for any legal rule, a plausible counter-rule exists. Law serves to legitimise existing power structures (hierarchies of class, race, gender) by presenting contingent political choices as objective legal necessity. Methods: 'trashing' (exposing contradictions in doctrine); 'deconstruction' (revealing suppressed alternatives); 'genealogy' (tracing the historical contingency of legal categories).",
    "details": "CLS emerged at Harvard in the late 1970s (Kennedy, Unger). Duncan Kennedy's 'The Structure of Blackstone's Commentaries' argued law is organised around an irresolvable tension between individualism and altruism. Unger argued existing legal doctrine could be reconstructed to serve more egalitarian ends (deviationist doctrine). Criticisms: (1) if law is truly indeterminate, how do CLS scholars identify its ideological effects? (2) practical reformers need some predictability. Relationship with Critical Race Theory (CRT) and Feminist Jurisprudence: both share the CLS insight about law's role in reproducing hierarchy but focus on race and gender specifically. Mari Matsuda, Angela Harris, and Catharine MacKinnon developed these fields.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hart-primary-secondary",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Hart",
      "primary rules",
      "secondary rules",
      "rule of recognition"
    ],
    "crossCutting": false,
    "front": "What is Hart's distinction between primary and secondary rules?",
    "back": "Primary rules impose duties and govern conduct (e.g. criminal law, tort). Secondary rules are 'rules about rules' — they confer powers to create, modify, or adjudicate primary rules. Three types: (1) rule of recognition — identifies which rules are valid law; (2) rules of change — authorise creation/amendment of primary rules; (3) rules of adjudication — empower officials to determine whether primary rules have been broken.",
    "details": "Hart's The Concept of Law (1961). A society governed only by primary rules suffers from uncertainty, stasis, and inefficiency. Secondary rules cure these defects. The rule of recognition is the 'ultimate rule' — in the UK, broadly: what the Queen/King in Parliament enacts is law. It is a social fact, identified by the practice of officials. Hart distinguished his account from Austin's 'command theory' by showing that law is not mere orders backed by threats.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-austin-command-theory-elements",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Austin",
      "command theory",
      "sovereign",
      "sanction"
    ],
    "crossCutting": false,
    "front": "What is Austin's command theory of law?",
    "back": "John Austin (1790-1859) defined law as the command of a sovereign backed by a sanction. Three elements: (1) a command — an expression of a wish that another do or refrain from some act; (2) issued by a sovereign — a determinate person or body habitually obeyed by the bulk of the population and not in the habit of obeying anyone else; (3) backed by a sanction — the threat of evil in the event of non-compliance.",
    "details": "Criticisms (especially by Hart): (1) not all laws are commands (power-conferring rules, e.g. contract, wills, marriage are not); (2) custom and judge-made law are not 'commanded'; (3) the sovereign cannot be identified in many legal systems (e.g. where sovereignty is divided); (4) habitual obedience does not explain why a new sovereign is obeyed; (5) law applies to the sovereign too (international law). Austin's theory is foundational but widely regarded as inadequate.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-kelsen-grundnorm",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Kelsen",
      "pure theory",
      "Grundnorm",
      "normative hierarchy"
    ],
    "crossCutting": false,
    "front": "What is Kelsen's 'pure theory of law' and the role of the Grundnorm?",
    "back": "Hans Kelsen (1881-1973) sought to create a 'pure' science of law, free from moral, political, and sociological considerations. Law is a system of norms arranged hierarchically — each norm derives its validity from a higher norm. At the apex is the Grundnorm (basic norm) — a presupposed, ultimate norm that validates the entire legal system (e.g. 'the historically first constitution ought to be obeyed'). The Grundnorm is not a positive legal norm but a transcendental-logical presupposition.",
    "details": "Kelsen distinguished his theory from both natural law (which derives validity from morality) and Austin (who grounded law in social facts). For Kelsen, law is a coercive normative order — its norms authorise sanctions. Criticisms: the Grundnorm is circular or metaphysical; it cannot explain legal revolutions (when a new Grundnorm replaces the old — e.g. Madzimbamuto v Lardner-Burke [1969]). Hart criticised Kelsen for failing to account for the social practice that underlies the rule of recognition.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hart-fuller-debate",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": [
      "Hart-Fuller debate",
      "inner morality of law",
      "Nazi Germany",
      "grudge informer"
    ],
    "crossCutting": false,
    "front": "What was the Hart-Fuller debate about?",
    "back": "The 1958 Hart-Fuller debate in the Harvard Law Review concerned whether law and morality are necessarily connected. Hart (positivist) argued that an unjust law is still law — the question of what the law IS is separate from what it OUGHT to be. Fuller (natural lawyer) argued that law has an 'inner morality' — eight principles of legality — and that grossly immoral systems (like Nazi law) fail to qualify as law because they violate these principles.",
    "details": "The catalyst was the 'grudge informer' case — a German woman who reported her husband to the Nazis under a morally repugnant statute. Hart: the statute was valid law, even if morally wrong. The correct response was retrospective legislation, not pretending it was never law. Fuller: the statute lacked the qualities of legality. His eight principles include: generality, promulgation, prospectivity, clarity, non-contradiction, possibility of compliance, stability, and congruence between rules and official action.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-fuller-eight-principles",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Fuller",
      "inner morality",
      "eight principles",
      "rule of law"
    ],
    "crossCutting": false,
    "front": "What are Fuller's eight principles of the 'inner morality of law'?",
    "back": "Laws must be: (1) general — applicable to classes, not ad hoc; (2) promulgated — publicly known; (3) prospective — not retroactive; (4) clear — intelligible to those subject to them; (5) non-contradictory; (6) possible to comply with; (7) relatively stable — not constantly changing; (8) congruent — official action must match the declared rules. These are principles of procedural natural law, not substantive morality.",
    "details": "Fuller's The Morality of Law (1964). He illustrated these through the parable of Rex, an inept king who fails in every one of these requirements. Hart criticised this as merely a checklist for effective legislation, not a moral requirement — even a tyrant benefits from clear, prospective laws. Fuller's response: these principles are internal to the enterprise of subjecting human conduct to rules and necessarily embody a respect for human agency.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-finnis-basic-goods",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Finnis",
      "natural law",
      "basic goods",
      "practical reasonableness"
    ],
    "crossCutting": false,
    "front": "What are Finnis's basic forms of human good?",
    "back": "John Finnis identifies seven basic forms of human flourishing: (1) life, (2) knowledge, (3) play, (4) aesthetic experience, (5) sociability/friendship, (6) practical reasonableness, (7) religion (concern with ultimate questions). These are self-evident, incommensurable, and equally fundamental. Law's purpose is to facilitate the common good by coordinating human activity in pursuit of these goods according to principles of practical reasonableness.",
    "details": "Finnis's Natural Law and Natural Rights (1980). Practical reasonableness includes: a coherent life plan, no arbitrary preferences among persons, detachment and commitment, limited relevance of consequences, respect for every basic value, the common good, and following one's conscience. Finnis derives the authority of law from its service of the common good — an unjust law is law in a 'focal' sense but is deficient. He distinguishes 'focal' and 'secondary' cases of law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-aquinas-natural-law",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Aquinas",
      "natural law",
      "eternal law",
      "human law",
      "lex iniusta"
    ],
    "crossCutting": false,
    "front": "What is Aquinas's hierarchy of law?",
    "back": "(1) Eternal law — God's rational plan for the universe. (2) Natural law — the participation of rational creatures in eternal law, known through reason (e.g. pursue good, avoid evil, preserve life, educate offspring, live in society). (3) Human law — specific rules derived from natural law by legislators to govern particular communities. (4) Divine law — revealed law (Scripture). Human law that contradicts natural law is lex iniusta non est lex — an unjust law is no law at all.",
    "details": "Aquinas (Summa Theologica, 13th century). Human law can be derived from natural law by (a) conclusion (directly deduced — e.g. 'do not kill' → murder is a crime) or (b) determination (filling in details — e.g. speed limits). Aquinas was more nuanced than 'unjust law is no law' — he recognised that sometimes compliance with unjust law may be necessary to avoid greater social harm. His theory influenced Finnis's modern revival.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-dworkin-interpretivism",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Dworkin",
      "interpretivism",
      "law as integrity",
      "constructive interpretation"
    ],
    "crossCutting": false,
    "front": "What is Dworkin's theory of law as integrity?",
    "back": "Ronald Dworkin argued that law is not just a system of rules (contra positivism) but also includes principles. 'Law as integrity' requires judges to interpret the law as a coherent scheme of justice — the best constructive interpretation of the community's legal practice. The judge (Dworkin's 'Hercules') should decide cases by finding the interpretation that best 'fits' existing legal materials and presents them in their best moral light.",
    "details": "Dworkin's Taking Rights Seriously (1977) and Law's Empire (1986). He attacked Hart's positivism: in hard cases, judges do not exercise discretion but discover rights that already exist in the principles underlying the law. The 'one right answer' thesis — every legal question has a correct answer, even if it is difficult to find. Critics: the one right answer thesis is too idealistic; reasonable judges can disagree about the best interpretation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-dworkin-rules-principles",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": [
      "Dworkin",
      "rules",
      "principles",
      "policies"
    ],
    "crossCutting": false,
    "front": "Distinguish Dworkin's concepts of rules, principles, and policies.",
    "back": "Rules apply in an 'all-or-nothing' fashion — if valid, they determine the outcome. Principles have weight or importance and can be balanced — they incline the decision in one direction without determining it (e.g. 'no person should profit from their own wrong'). Policies are standards that set goals for the community (e.g. reduce road accidents). Dworkin argued that judges should decide hard cases on principles (rights-based arguments), not policies (goal-based arguments).",
    "details": "Dworkin illustrated with Riggs v Palmer (1889) — a murderer could not inherit from his victim's will, even though the statute said nothing about this, because the principle that no one should profit from their wrong overrode the rule. Positivists (Hart, Raz) responded that principles can be accommodated within positivism — they are just legally valid norms with a different logical structure.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-raz-authority",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Raz",
      "authority",
      "service conception",
      "exclusionary reasons"
    ],
    "crossCutting": false,
    "front": "What is Raz's 'service conception' of authority?",
    "back": "Joseph Raz argues that law claims legitimate authority. The 'service conception' holds that an authority is legitimate if its directives help subjects better conform to reasons that already apply to them (the 'normal justification thesis'). Law's directives serve as 'exclusionary reasons' — they replace the underlying first-order reasons rather than adding to them. A subject should treat the law's directive as a reason for action that pre-empts their own deliberation about what to do.",
    "details": "Raz (The Authority of Law, 1979; The Morality of Freedom, 1986). Example: if a workplace safety regulation requires wearing helmets, the regulation replaces each worker's individual assessment of the risk. Raz criticises both natural law (law's moral content is irrelevant to its validity) and inclusive positivism (Dworkin-influenced versions of positivism). He is an 'exclusive' positivist: the existence and content of law depends entirely on social facts.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-utilitarianism-bentham",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Bentham",
      "utilitarianism",
      "greatest happiness",
      "felicific calculus"
    ],
    "crossCutting": false,
    "front": "What is Bentham's utilitarianism and how does it relate to law?",
    "back": "Jeremy Bentham (1748-1832) held that the fundamental principle of morality and legislation is the 'greatest happiness of the greatest number.' An action (or law) is right if it tends to promote happiness (pleasure) and wrong if it tends to produce unhappiness (pain). Bentham developed a 'felicific calculus' to measure pleasure and pain. Law should be designed to maximise aggregate social utility.",
    "details": "Bentham was also a legal positivist — law is what the sovereign commands, not what morality requires. He attacked natural law as 'nonsense upon stilts.' His utilitarianism was 'act utilitarian' — each act is judged by its consequences. Mill developed 'rule utilitarianism' (follow rules that generally maximise happiness). Criticisms: utilitarianism can justify sacrificing minority rights for majority benefit; the felicific calculus is impractical; it ignores distributive justice.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-rawls-justice",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Rawls",
      "justice as fairness",
      "veil of ignorance",
      "original position"
    ],
    "crossCutting": false,
    "front": "What are Rawls's two principles of justice?",
    "back": "John Rawls (A Theory of Justice, 1971): behind a 'veil of ignorance' (where no one knows their social position, talents, or conception of the good), rational persons in the 'original position' would choose: (1) the liberty principle — each person has an equal right to the most extensive basic liberties compatible with similar liberty for all; (2) the difference principle — social and economic inequalities are permissible only if they benefit the least advantaged members of society and are attached to offices open to all under fair equality of opportunity. Liberty takes priority over equality.",
    "details": "The veil of ignorance ensures impartiality — no one can tailor principles to their advantage. Rawls criticised utilitarianism for failing to take seriously the distinction between persons — it could sacrifice individuals for aggregate welfare. The difference principle is not strict egalitarianism but permits inequality that makes everyone (especially the worst off) better off than they would be under equality. Critiques: Nozick (libertarian — Anarchy, State, and Utopia), communitarians (Sandel, Walzer).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-marx-law-superstructure",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Marx",
      "historical materialism",
      "base and superstructure",
      "ideology"
    ],
    "crossCutting": false,
    "front": "How does Marxist theory characterise the role of law?",
    "back": "In Marxist theory, law is part of the 'superstructure' — it is determined by the economic 'base' (the mode of production and relations of production). Law serves the interests of the ruling class (the bourgeoisie in capitalism) by protecting private property and legitimating existing power structures. It operates as ideology — presenting class-specific interests as universal, neutral, and just. In a communist society, law (and the state) would 'wither away.'",
    "details": "Marx and Engels, The Communist Manifesto (1848); Marx, Capital. The base-superstructure model is often criticised as overly deterministic — Western Marxists (Gramsci, Althusser) developed more nuanced accounts. Gramsci's concept of 'hegemony' explains how law maintains class dominance through cultural consent, not just coercion. Pashukanis (a Soviet legal theorist) argued that the legal form is inherently bourgeois because it presupposes commodity exchange between formally equal persons.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-feminist-legal-theory",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "feminist legal theory",
      "gender",
      "patriarchy",
      "critique of neutrality"
    ],
    "crossCutting": false,
    "front": "What is the central claim of feminist legal theory?",
    "back": "Feminist legal theory argues that law is not gender-neutral but reflects and reinforces patriarchal power structures. Despite formal equality, law embodies male perspectives and experiences as the 'universal' norm, disadvantaging women. Key strands include: liberal feminism (formal equality of rights), radical feminism (MacKinnon — law perpetuates male dominance, especially through regulation of sexuality), and difference feminism (Gilligan — law privileges an 'ethic of justice' over an 'ethic of care').",
    "details": "MacKinnon: the state is male — law adopts a male standpoint while appearing objective. She critiqued the public/private divide as masking domestic violence and inequality. Smart (Feminism and the Power of Law, 1989): warns against 'juridogenic' strategies — over-reliance on law to achieve feminist goals. Intersectionality (Crenshaw): the intersection of race, gender, class, and other categories creates compound disadvantage that single-axis analysis misses.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hart-rule-recognition",
    "type": "application",
    "module": "Jurisprudence",
    "tags": [
      "Hart",
      "rule of recognition",
      "validity",
      "social fact"
    ],
    "crossCutting": false,
    "front": "In a hypothetical new country with a single written constitution, what would Hart identify as the rule of recognition?",
    "back": "Hart would identify the rule of recognition as the constitutional practice of officials — roughly, 'whatever is enacted in accordance with the procedures set out in the Constitution is valid law.' The rule of recognition is an ultimate social rule that exists as a matter of fact — it is constituted by the convergent practice of legal officials (especially judges) who accept it from the 'internal point of view' as a standard for identifying valid law.",
    "details": "The rule of recognition is not itself valid or invalid — it simply exists (or not) as a social fact. It can be simple (in a theocracy: 'whatever God commands') or complex (in the UK: Acts of Parliament, judicial precedent, custom — with Parliament at the apex). Hart distinguished the 'internal point of view' (officials who accept and use the rule) from the 'external point of view' (sociological observation of regularities). Dworkin criticised this as failing to capture the interpretive, value-laden character of legal reasoning.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-inclusive-exclusive-positivism",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": [
      "inclusive positivism",
      "exclusive positivism",
      "soft positivism",
      "Raz",
      "Hart"
    ],
    "crossCutting": false,
    "front": "Distinguish inclusive ('soft') positivism from exclusive ('hard') positivism.",
    "back": "Inclusive positivism (Hart's Postscript, Waluchow, Coleman): the rule of recognition CAN include moral criteria for legal validity — e.g. a constitution may make fundamental rights part of the test for valid law. Morality is not necessarily relevant but can be made relevant by social convention. Exclusive positivism (Raz): the existence and content of law depends ONLY on social facts, never on moral criteria. Moral tests cannot be part of the rule of recognition because law must be identifiable without moral deliberation.",
    "details": "Raz's argument: law claims authority, and authority requires that directives be identifiable without engaging in the very deliberation the authority is meant to pre-empt. If identifying law requires moral reasoning, law cannot serve its mediating function. Hart's Postscript (published posthumously, 1994) aligned with inclusive positivism. This debate is internal to positivism — both sides agree law and morality are conceptually distinct; they disagree about whether moral tests can feature in the rule of recognition.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-speluncean-explorers",
    "type": "application",
    "module": "Jurisprudence",
    "tags": [
      "Speluncean Explorers",
      "Fuller",
      "legal reasoning",
      "competing theories"
    ],
    "crossCutting": false,
    "front": "What does Fuller's 'The Case of the Speluncean Explorers' illustrate about jurisprudence?",
    "back": "In this famous 1949 hypothetical, five cave explorers are trapped. They learn by radio that survival requires killing and eating one of their number. They do so and are later charged with murder. Five fictional judges each reach different conclusions by applying different jurisprudential approaches — natural law, positivism, purposive interpretation, judicial restraint, and legal realism. The case illustrates how different theories of law lead to different outcomes on identical facts.",
    "details": "The judgments include: Truepenny CJ (statutory text requires conviction but recommends executive clemency); Foster J (acquittal — the men were in a 'state of nature' outside the law's jurisdiction, and the purpose of the murder statute is to deter); Tatting J (recuses — cannot resolve the competing arguments); Keen J (conviction — the judge's role is to apply the law, not make moral judgments); Handy J (acquittal — public opinion polls show 90% favour acquittal). The case is widely used as an introductory jurisprudence exercise.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hobbes-social-contract",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "Hobbes",
      "social contract",
      "state of nature",
      "Leviathan",
      "sovereignty"
    ],
    "crossCutting": false,
    "front": "What is Hobbes's theory of the social contract?",
    "back": "Thomas Hobbes (Leviathan, 1651): in the 'state of nature' (without government), life is a 'war of all against all' — 'solitary, poor, nasty, brutish, and short.' Rational self-interest drives people to surrender their natural liberty to an absolute sovereign (the Leviathan) in exchange for security and order. The social contract creates political obligation — subjects must obey the sovereign because the alternative is the intolerable state of nature.",
    "details": "Hobbes's sovereign can be a monarch or assembly but must have absolute, undivided authority — any limitation leads back to the state of nature. Unlike later social contract theorists (Locke, Rousseau), Hobbes's sovereign is not bound by the contract and cannot be removed. The sovereign's laws create obligations — without a sovereign, there is no right or wrong. Hobbes is often considered a precursor of legal positivism because he separates the question of what law IS from natural law morality.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-legal-realism",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": [
      "legal realism",
      "American realism",
      "indeterminacy",
      "Holmes"
    ],
    "crossCutting": false,
    "front": "What is the core claim of American legal realism?",
    "back": "American legal realism (Holmes, Llewellyn, Frank) argues that law is not what is written in books but what courts actually do. Holmes: 'the prophecies of what the courts will do in fact, and nothing more pretentious, are what I mean by the law.' Realists claimed that legal rules are indeterminate — judges decide cases based on policy, social context, and personal intuition, then rationalise their decisions with legal rules after the fact.",
    "details": "Oliver Wendell Holmes Jr. (The Path of the Law, 1897) — take the 'bad man' perspective: law is what will happen to you if you act in a certain way, not abstract moral principles. Karl Llewellyn: the 'paper rules' (stated rules) differ from 'real rules' (the patterns of judicial behaviour). Jerome Frank: judges are influenced by subconscious biases. Critics: legal realism exaggerates indeterminacy — most cases are clear, and rules do constrain. But realism influenced the Critical Legal Studies movement.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-locke-social-contract",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Locke", "social contract", "natural rights", "limited government", "consent"],
    "crossCutting": false,
    "front": "How does Locke's social contract theory differ from Hobbes's?",
    "back": "John Locke (Two Treatises of Government, 1689): individuals in the state of nature possess natural rights (life, liberty, property). The social contract creates a limited government to protect these pre-existing rights. Unlike Hobbes's absolute sovereign, Locke's government is constrained by natural law and the trust of the people — if the government violates natural rights, the people retain a right of revolution. Sovereignty remains with the people, not the ruler.",
    "details": "Locke's state of nature is relatively peaceful (unlike Hobbes's 'war of all against all') — people have reason and natural law to guide them, but lack an impartial judge to resolve disputes. Government is created by consent to remedy this. The legislature is supreme but bound by natural law. Property is a natural right arising from labour (the 'labour theory of property'). Locke's ideas profoundly influenced liberal constitutionalism, the American Declaration of Independence, and the concept of limited government under the rule of law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-nozick-entitlement",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Nozick", "libertarianism", "entitlement theory", "minimal state", "critique of Rawls"],
    "crossCutting": false,
    "front": "What is Nozick's entitlement theory of justice and how does it challenge Rawls?",
    "back": "Robert Nozick (Anarchy, State, and Utopia, 1974) argues for a minimal ('nightwatchman') state limited to protection against force, theft, and fraud. His entitlement theory holds that a distribution of holdings is just if it arose from: (1) just acquisition (original appropriation from nature); (2) just transfer (voluntary exchange or gift); and (3) rectification of past injustice. Any 'patterned' redistribution (like Rawls's difference principle) violates individual liberty — if people are entitled to their holdings, the state cannot redistribute without consent.",
    "details": "Nozick's Wilt Chamberlain argument: if a distribution is just, and people freely choose to pay Chamberlain to watch him play basketball, the resulting unequal distribution is also just — to maintain the 'patterned' distribution, the state would need to continuously interfere with free choices. Criticisms: (1) ignores structural inequality — initial holdings may themselves be unjust; (2) the rectification principle may actually require massive redistribution to correct historical injustice; (3) overlooks positive liberty and the conditions necessary for meaningful freedom. Nozick's libertarianism contrasts with Rawls's egalitarian liberalism.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hart-minimum-content",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Hart", "minimum content of natural law", "survival", "truisms"],
    "crossCutting": false,
    "front": "What is Hart's 'minimum content of natural law'?",
    "back": "Hart acknowledged that given certain truisms about human nature — human vulnerability, approximate equality, limited altruism, limited resources, and limited understanding and strength of will — any viable legal system must contain certain minimum protections (rules restricting violence, protecting property, and requiring promises to be kept). Without these, social life would be impossible. This is a 'minimum content of natural law' that any system must have to be viable, but it derives from human nature and necessity, not from moral truth.",
    "details": "Hart used this argument to build a bridge between positivism and natural law without conceding the natural lawyer's full claim. He argued that these are not moral truths but empirical necessities — 'natural necessities' arising from the human condition. If humans were radically different (invulnerable, or wholly altruistic), the rules could be different. Fuller criticised this as too minimal — it does not capture the procedural morality that law requires. Finnis argued Hart's concession goes further than Hart admits: the recognition that law must serve human survival and cooperation is a natural law insight.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-dworkin-law-as-integrity",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Dworkin", "law as integrity", "Laws Empire", "chain novel", "Hercules"],
    "crossCutting": false,
    "front": "What is Dworkin's 'chain novel' analogy and how does it illustrate law as integrity?",
    "back": "In Law's Empire (1986), Dworkin compares legal interpretation to writing a chain novel: each judge is like an author who must continue a story already begun by others. They must interpret existing chapters (past decisions and legislation) and write a new chapter that both 'fits' the story so far and makes it the best story it can be. Similarly, a judge must find the interpretation of law that best fits existing legal materials and presents them in their best moral light — this is 'law as integrity.'",
    "details": "Dworkin distinguished three conceptions of law: (1) conventionalism (law is what conventions/past decisions say — close to positivism); (2) pragmatism (judges should decide cases to produce the best consequences, unconstrained by the past); (3) law as integrity (judges must treat the law as a coherent, principled whole). Integrity requires both 'fit' (consistency with past decisions) and 'justification' (the best moral reading). The ideal judge 'Hercules' has superhuman learning and patience to construct the theory that best satisfies both dimensions. Critics argue this is unrealistic and that reasonable judges will disagree about the 'best' interpretation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-rule-of-law-dicey",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["rule of law", "Dicey", "Bingham", "formal", "substantive"],
    "crossCutting": false,
    "front": "What are the main conceptions of the rule of law?",
    "back": "Formal ('thin') conception (Dicey, Raz): (1) government must act according to law, not arbitrary power; (2) all persons are equal before the law; (3) the law must be clear, prospective, stable, and publicly promulgated. Substantive ('thick') conception (Bingham, Dworkin): the rule of law also requires that laws respect fundamental rights and substantive justice — formal legality alone is not enough. Lord Bingham (The Rule of Law, 2010) proposed eight sub-rules including access to justice, clear and accessible law, and protection of human rights.",
    "details": "Dicey (Introduction to the Study of the Law of the Constitution, 1885) identified three elements: (1) supremacy of regular law over arbitrary power; (2) equality before the law — no one is above the law; (3) the constitution is the result of the ordinary law of the land (rights derive from judicial decisions, not a constitutional document). Raz's formal conception: law must be capable of guiding behaviour — prospective, open, clear, stable. Fuller's 8 principles of legality overlap here. The formal/substantive debate matters: can an apartheid state or authoritarian regime satisfy the rule of law? Formalists say yes (if procedurally correct); substantivists say no (it must also be just).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-crt-intersectionality",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Critical Race Theory", "CRT", "intersectionality", "Crenshaw", "structural racism"],
    "crossCutting": false,
    "front": "What are the central claims of Critical Race Theory (CRT)?",
    "back": "CRT (Delgado, Crenshaw, Bell) holds that: (1) racism is not aberrational but ordinary — embedded in legal structures and institutions; (2) formal equality (treating everyone the same) fails to address structural disadvantage; (3) race is a social construct, not biological, but has real material consequences; (4) the experiences and voices of people of colour must be centred (counter-storytelling). Kimberlé Crenshaw's concept of 'intersectionality' shows that race, gender, class, and other categories interact to produce compound forms of disadvantage that single-axis analysis cannot capture.",
    "details": "CRT emerged from CLS in the late 1980s — sharing the CLS critique of law's neutrality but focusing specifically on race. Derrick Bell's 'interest convergence' thesis: advances in racial justice occur only when they also serve white interests (e.g. Brown v Board of Education served Cold War diplomacy interests). CRT critiques 'colour-blindness' as perpetuating inequality by ignoring structural racism. Intersectionality (Crenshaw, 1989): a Black woman's experience of discrimination is not simply racism plus sexism — the intersection creates distinct and compounded disadvantage that neither category alone describes. CRT has influenced UK race equality law scholarship.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-mill-harm-principle",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Mill", "harm principle", "liberty", "On Liberty", "paternalism"],
    "crossCutting": false,
    "front": "What is Mill's harm principle and how does it define the limits of legitimate legal interference?",
    "back": "John Stuart Mill (On Liberty, 1859): 'the only purpose for which power can be rightfully exercised over any member of a civilised community, against his will, is to prevent harm to others.' Self-regarding conduct — actions that affect only the individual — cannot be legitimately restricted by law. Paternalism (restricting liberty for the person's own good) and legal moralism (criminalising conduct solely because it is immoral) are both illegitimate grounds for state coercion.",
    "details": "Mill's principle underpins the liberal theory of criminal law — the state should only criminalise conduct that harms others. The Hart-Devlin debate (1960s) tested this: Lord Devlin argued society has a right to enforce its shared morality through law (legal moralism — the 'fabric of society' argument). Hart (following Mill) argued that the mere fact that conduct is immoral is insufficient to justify criminalisation. The Wolfenden Report (1957) on homosexuality reflected Mill's position. Feinberg extended the harm principle to include 'offence' as a potential ground for restriction. Critics: the definition of 'harm' is contested and potentially infinitely expandable.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-hart-devlin-debate",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": ["Hart-Devlin", "legal moralism", "Wolfenden", "enforcement of morals"],
    "crossCutting": false,
    "front": "What was the Hart-Devlin debate about the enforcement of morals?",
    "back": "Lord Devlin (The Enforcement of Morals, 1965): society has the right to use the criminal law to enforce its shared morality, because a shared morality is the cement that holds society together — any deviation that provokes 'intolerance, indignation and disgust' in the reasonable person threatens social cohesion. Hart (Law, Liberty and Morality, 1963), following Mill: the mere immorality of conduct is not a sufficient ground for criminalisation — only harm to others justifies state coercion. Criminalising private consensual conduct violates individual autonomy.",
    "details": "The debate was sparked by the Wolfenden Committee Report (1957), which recommended decriminalising private homosexual acts between consenting adults — separating sin from crime. Devlin disagreed: society has a right to protect itself from moral disintegration, just as it protects itself from treason. Hart responded: (1) Devlin confuses social morality changing with society disintegrating; (2) empirically, societies survive moral change; (3) the 'reasonable person' test conceals prejudice. The Sexual Offences Act 1967 followed Wolfenden/Hart. The debate recurs in contexts like assisted dying, drug decriminalisation, and obscenity laws.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-scandinavian-realism",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Scandinavian realism", "Olivecrona", "Hägerström", "psychological realism"],
    "crossCutting": false,
    "front": "How does Scandinavian legal realism differ from American legal realism?",
    "back": "Scandinavian realism (Hägerström, Olivecrona, Lundstedt, Ross) focuses on the psychological dimension of law: legal concepts like 'rights,' 'duties,' and 'ownership' are not descriptions of objective reality but expressions of psychological attitudes and feelings of compulsion. Law operates through the psychological pressure it exerts on citizens and officials. American realism (Holmes, Llewellyn) focuses on what courts actually do — predicting judicial behaviour. Both deny that law is a system of objective norms, but Scandinavians are more philosophically radical.",
    "details": "Hägerström: talk of rights and duties is metaphysical nonsense — like belief in magic, it projects subjective feelings onto external reality. Olivecrona (Law as Fact, 1939): law is a set of social facts — commands addressed to officials, backed by psychological habits of obedience, not by objective normativity. Alf Ross (On Law and Justice, 1958): a legal rule is 'valid' if courts are likely to apply it — validity is a prediction, not a normative fact. Criticisms: (1) cannot explain the normative force of law — why people feel bound; (2) reduces law to psychology, losing its distinctive character as a system of standards; (3) Hart's critique: the 'internal point of view' shows that officials use rules as standards, not merely feel compelled.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-waldron-dignity",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Waldron", "dignity", "human rights", "foundations"],
    "crossCutting": false,
    "front": "What role does 'dignity' play in contemporary jurisprudence?",
    "back": "Jeremy Waldron (Dignity, Rank, and Rights, 2012) argues that modern human dignity is the extension of high-ranking status (once reserved for nobles) to every human being — a 'levelling up' of rank. Dignity is the foundational value underlying human rights: it explains why rights are universal, inalienable, and cannot be traded away. Dignity features in the UDHR (Art 1), the German Basic Law (Art 1), and increasingly in common law jurisprudence as a value informing the interpretation of rights.",
    "details": "Kant's account is foundational: rational beings have dignity (Würde), not price — they must be treated as ends in themselves, never merely as means. Dworkin (Justice for Hedgehogs, 2011): dignity has two dimensions — self-respect (taking one's own life seriously) and authenticity (taking responsibility for one's values). Criticisms: dignity is vague and used to support opposing conclusions (both for and against assisted dying, for example). Macklin (2003) called it a 'useless concept' that adds nothing to autonomy and respect for persons. Supporters respond that dignity captures something irreducible — the intrinsic worth of every person — that autonomy alone cannot express.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-lon-fuller-purposive",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": ["interpretation", "purposive", "literal", "textualism", "statutory interpretation"],
    "crossCutting": false,
    "front": "How do the main theories of statutory interpretation reflect jurisprudential commitments?",
    "back": "Literal/textualist approach: the court applies the ordinary meaning of the words used — reflects positivism (law is what the legislature enacted, not what it should have said). Purposive approach: the court identifies the purpose or mischief the statute was intended to address and interprets accordingly — reflects Fuller's view that law has purpose and judges must give effect to it. The mischief rule (Heydon's Case (1584)) and Pepper v Hart [1993] (consulting Hansard) reflect purposive reasoning.",
    "details": "Hart's 'open texture' (The Concept of Law): every rule has a core of settled meaning and a penumbra of uncertainty where judicial discretion is unavoidable. This supports moderate purposivism. Dworkin's interpretivism goes further: judges must construct the best interpretation of the statute within the legal framework as a whole. Scalia's textualism (US): the only legitimate source of meaning is the enacted text — legislative history is unreliable. In UK law, the purposive approach is now dominant (especially for EU-derived legislation and HRA-compatible interpretation under s.3 HRA 1998). The choice of approach is not neutral — it embodies a view about the proper relationship between legislature and judiciary.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-rights-theories",
    "type": "distinction",
    "module": "Jurisprudence",
    "tags": ["rights", "will theory", "interest theory", "Hohfeld", "claim right"],
    "crossCutting": false,
    "front": "Distinguish the 'will' (choice) theory and the 'interest' (benefit) theory of rights.",
    "back": "Will theory (Hart): a right is a protected choice — the right-holder has the power to enforce or waive the correlative duty. Rights exist to protect individual autonomy. Interest theory (Raz, MacCormick): a right exists when an interest of the right-holder is sufficient to ground a duty on another. Rights protect important interests, not choices. The theories produce different results: will theory cannot explain rights of children or incompetent persons (who cannot exercise choice); interest theory can, but may be over-inclusive.",
    "details": "Hohfeld (Fundamental Legal Conceptions, 1919) provided the foundational analytical framework: (1) claim-right (correlative: duty); (2) liberty/privilege (correlative: no-right); (3) power (correlative: liability); (4) immunity (correlative: disability). Every legal relation can be analysed into these building blocks. Hohfeld showed that 'a right' is ambiguous — it may refer to any of these four relations. Modern rights discourse often conflates different Hohfeldian incidents. Raz's interest theory links rights to the justification of duties: X has a right if X's interest is sufficient reason to hold another under a duty.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-rousseau-general-will",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["Rousseau", "general will", "social contract", "popular sovereignty"],
    "crossCutting": false,
    "front": "What is Rousseau's concept of the 'general will'?",
    "back": "Jean-Jacques Rousseau (The Social Contract, 1762): legitimate political authority rests on a social contract in which individuals surrender their natural liberty to the community and in return receive civil liberty and equality. The sovereign power lies in the 'general will' (volonté générale) — the common good of the whole community, as opposed to the 'will of all' (mere aggregation of private interests). Law is legitimate only when it expresses the general will. Obedience to the general will is 'freedom' because it represents what rational citizens would choose for the common good.",
    "details": "Rousseau's famous paradox: a person who disobeys the general will may be 'forced to be free' — because the general will represents their true rational interests as a citizen. Critics: this is dangerously authoritarian — it can justify coercion in the name of 'real' freedom (Berlin's 'positive liberty' critique). Rousseau differed from Hobbes (sovereignty is absolute but held by the people, not a monarch) and Locke (Rousseau's emphasis on equality and the general will goes beyond Locke's natural rights framework). Rousseau influenced the French Revolution, republican theory, and participatory democracy. His ideas resonate in debates about direct democracy and citizen participation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-postmodernism-law",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["postmodernism", "Derrida", "deconstruction", "Foucault", "power"],
    "crossCutting": false,
    "front": "How have postmodern thinkers influenced jurisprudence?",
    "back": "Postmodern jurisprudence challenges the Enlightenment assumptions underlying both positivism and natural law — that law is rational, coherent, and determinate. Key influences: Derrida's 'deconstruction' reveals instabilities and contradictions in legal texts — legal meaning is never fixed but always deferred. Foucault's analysis of power/knowledge shows that law is not a neutral framework but a mechanism of disciplinary power that produces and controls subjects. Lyotard's 'incredulity toward metanarratives' questions whether any grand theory of law (positivist, natural law, or Marxist) can provide a complete account.",
    "details": "Derrida (Force of Law, 1990): justice is always 'to come' (à venir) — it can never be fully captured by any legal system. The gap between law and justice means deconstruction is always possible: every legal text can be read against itself. Foucault (Discipline and Punish, 1975): modern law operates not through sovereign command but through dispersed techniques of surveillance, normalisation, and discipline. This influenced socio-legal studies and critical approaches to criminal justice. Criticisms: postmodernism is nihilistic and offers no constructive alternative; if all meaning is unstable, legal reasoning becomes impossible. Defenders: it reveals the political choices concealed by legal formalism.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "juris-law-economics",
    "type": "principle",
    "module": "Jurisprudence",
    "tags": ["law and economics", "Posner", "efficiency", "Coase theorem"],
    "crossCutting": false,
    "front": "What is the 'law and economics' approach to legal theory?",
    "back": "Law and economics (Posner, Calabresi, Coase) analyses legal rules in terms of their economic efficiency. Richard Posner (Economic Analysis of Law, 1973) argued that the common law tends toward efficiency — legal rules should (and do) allocate resources to their highest-valued use. The Coase Theorem (1960): where transaction costs are zero, the initial allocation of legal rights does not affect the efficient outcome — parties will bargain to the optimal result regardless. When transaction costs are positive, legal rules should mimic the outcome the parties would have reached through costless bargaining.",
    "details": "Applications: tort law as efficient deterrence (Learned Hand formula: negligence where B < PL — the cost of precaution is less than the probability of harm times the magnitude of loss); contract law as facilitating efficient breach (breach is efficient if the cost of performance exceeds its value to the promisee); property law as minimising the 'tragedy of the commons.' Criticisms: (1) reduces justice to efficiency — ignores distributional concerns and rights (Dworkin); (2) wealth maximisation is not a moral value (Rawls, Sen); (3) the Coase Theorem's assumptions (zero transaction costs, perfect information) rarely hold. Despite criticisms, law and economics has profoundly influenced US legal scholarship and policy.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
