// Auto-generated from cards.js split. Module: Property Law
export const propertyLawCards = [
  {
    "id": "14",
    "type": "case",
    "module": "Property Law",
    "tags": [
      "adverse possession",
      "limitation"
    ],
    "crossCutting": false,
    "front": "What did the House of Lords decide in JA Pye (Oxford) Ltd v Graham [2003] regarding adverse possession?",
    "back": "The squatter must show (1) factual possession — a sufficient degree of exclusive physical control, and (2) intention to possess (animus possidendi) — intention to possess on one's own behalf, not necessarily to own. 12-year limitation period (unregistered land). The Grahams satisfied both limbs.",
    "details": "Lord Browne-Wilkinson: animus possidendi does not require an intention to acquire ownership, only an intention to possess. Land Registration Act 2002 later reformed adverse possession for registered land (10-year period + notification).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "property-street-v-mountford",
    "type": "case",
    "module": "Property Law",
    "tags": [
      "lease",
      "licence",
      "street v mountford",
      "exclusive possession",
      "tenancy"
    ],
    "crossCutting": false,
    "front": "What principle did Street v Mountford [1985] establish for distinguishing a lease from a licence?",
    "back": "If an occupant has (1) exclusive possession of (2) residential premises (3) for a term (4) at a rent, a lease (tenancy) exists in law regardless of how the parties label the agreement. The label 'licence' cannot prevent a tenancy arising if these four elements are present (Lord Templeman).",
    "details": "Street v Mountford was a reaction to landlords using 'licence' agreements to avoid Rent Act protection. The House of Lords held that substance prevails over form. Exclusive possession is the key determinant — a licensee may be present but cannot exclude the grantor. Subsequent cases refined the exceptions: a lodger who receives services lacks exclusive possession (AG Securities v Vaughan [1990]). The distinction matters enormously: tenants have security of tenure, repair rights, and protection from unlawful eviction; licensees have few statutory protections.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "property-easements-re-ellenborough",
    "type": "case",
    "module": "Property Law",
    "tags": [
      "easements",
      "re ellenborough park",
      "four requirements",
      "dominant tenement",
      "servient tenement"
    ],
    "crossCutting": false,
    "front": "What are the four requirements for a right to be capable of being an easement, as set out in Re Ellenborough Park [1956]?",
    "back": "Re Ellenborough Park (CA) held an easement must: (1) there must be a dominant and servient tenement; (2) an easement must accommodate and serve the dominant tenement; (3) the dominant and servient owners must be different persons; (4) the right must be capable of forming the subject matter of a grant (i.e. it must be definable and exercisable by a grantee).",
    "details": "The case concerned a right to use a communal garden: the CA upheld it as an easement satisfying all four tests. The 'accommodate and serve' test requires a nexus between the right and the use of the dominant land — a right that merely benefits the owner personally does not qualify (Hill v Tupper [1863]: right to put boats on canal was too personal). The fourth requirement excludes vague rights ('right to a view') and rights that would amount to exclusive possession. Easements can be legal or equitable and are acquired by express/implied grant or prescription (20 years' user).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "property-tulk-v-moxhay",
    "type": "case",
    "module": "Property Law",
    "tags": [
      "restrictive covenant",
      "tulk v moxhay",
      "burden",
      "equity",
      "Leicester Square"
    ],
    "crossCutting": false,
    "front": "What did Tulk v Moxhay [1848] establish about the running of restrictive covenants?",
    "back": "In equity, the burden of a restrictive covenant runs with the land and binds a subsequent purchaser who takes with notice of it, even without privity of contract. Requirements: the covenant must be negative in substance; it must benefit land retained by the covenantee; the original parties must have intended the burden to run; and the buyer must have notice.",
    "details": "Tulk owned Leicester Square and sold it subject to a covenant to keep it open. Moxhay later bought it knowing of the covenant and wished to build on it. Lord Cottenham held the covenant was enforceable in equity because it would be unconscionable for Moxhay to act contrary to a known restriction. Today restrictive covenants are registered as Land Charges (unregistered) or protected by a notice on the register (LRA 2002). The positive covenant problem remains: the burden of positive covenants (e.g. to repair) does not run at common law — methods to bind successors include long lease, chain of indemnity covenants, or estate rentcharge.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "property-overriding-interests-lra2002",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "overriding interests",
      "LRA 2002",
      "schedule 3",
      "actual occupation",
      "registration"
    ],
    "crossCutting": false,
    "front": "What are overriding interests under the Land Registration Act 2002 and why do they matter?",
    "back": "Overriding interests (LRA 2002, Schs 1 and 3) are legal rights that bind a registered proprietor or purchaser without appearing on the register. Key examples: legal easements and profits (Sch 3 para 3); interests of persons in actual occupation (Sch 3 para 2); legal leases of ≤7 years (Sch 3 para 1).",
    "details": "Sch 3 para 2 (actual occupation) is most significant in practice: it protects, for example, an unregistered beneficial interest of an occupier. Requirements: (a) the person must have a proprietary interest; (b) they must be in actual occupation at the time of the disposition. Exceptions: if inquiry was made and interest not disclosed; if occupation was not apparent on reasonable inspection (for registered dispositions). Williams & Glyn's Bank v Boland [1981] — wife with beneficial interest under trust was in actual occupation; her interest overrode the mortgage. LRA 2002 narrowed this from the earlier LRA 1925 position.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "property-proprietary-estoppel",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "proprietary estoppel",
      "assurance",
      "reliance",
      "detriment",
      "thorner v major"
    ],
    "crossCutting": false,
    "front": "What are the elements of a proprietary estoppel claim?",
    "back": "Proprietary estoppel arises where: (1) the landowner made an assurance or representation to the claimant regarding property rights; (2) the claimant reasonably relied on that assurance; (3) the claimant suffered detriment in reliance; and (4) it would be unconscionable to allow the landowner to go back on the assurance (Thorner v Major [2009]).",
    "details": "Thorner v Major: the claimant worked for 29 years on his uncle's farm in reliance on oblique assurances that the farm would be left to him. The House of Lords upheld the claim: assurances need not be explicit if they are clear enough in context. The remedy is the minimum necessary to satisfy the equity — courts have wide discretion: full transfer of land, lease, licence, or monetary compensation. Contrast constructive trust (requires common intention and contribution to the purchase price) with estoppel (no contribution needed, but may give lesser remedy).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-estates-interests",
    "type": "distinction",
    "module": "Property Law",
    "tags": [
      "freehold",
      "leasehold",
      "estate",
      "LPA 1925"
    ],
    "crossCutting": false,
    "front": "What are the two legal estates in land recognised under the Law of Property Act 1925?",
    "back": "S.1(1) LPA 1925 recognises only two legal estates: (1) the fee simple absolute in possession (freehold) — the largest estate, potentially lasting forever; and (2) the term of years absolute (leasehold) — a fixed or periodic term. All other estates or interests (e.g. life estates, fee tails) can exist only in equity behind a trust.",
    "details": "The 1925 property legislation radically simplified land law by reducing the number of legal estates from many to two, and by creating a system of registration. S.1(2) lists legal interests: easements, rentcharges, charges by way of legal mortgage, and certain other rights. S.1(3): all other interests are equitable only. This distinction matters because legal rights bind the whole world, while equitable rights may be overridden by a bona fide purchaser for value of a legal estate without notice.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-registered-land-priorities",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "registered land",
      "LRA 2002",
      "priorities",
      "overriding interests"
    ],
    "crossCutting": false,
    "front": "How are priorities determined in registered land under the Land Registration Act 2002?",
    "back": "In registered land: (1) registered dispositions for value take priority over earlier unprotected interests (s.29 LRA 2002). (2) Interests protected by notice on the register bind the purchaser. (3) Overriding interests (Schedule 3) bind the purchaser even without registration — including: short leases (under 7 years), interests of persons in actual occupation (Sch 3, para 2), and legal easements. The basic rule is that the register is conclusive (s.58).",
    "details": "Schedule 3, para 2 (actual occupation): the interest of a person in actual occupation at the time of disposition overrides unless: the occupation was not obvious on a reasonably careful inspection AND the purchaser did not have actual knowledge, or the interest-holder failed to disclose when reasonably asked. Williams & Glyn's Bank v Boland [1981] — a wife's beneficial interest under a trust was an overriding interest because she was in actual occupation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-unregistered-land",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "unregistered land",
      "land charges",
      "bona fide purchaser"
    ],
    "crossCutting": false,
    "front": "How are third-party interests protected in unregistered land?",
    "back": "In unregistered land, interests are protected by: (1) registration under the Land Charges Act 1972 (registrable interests include estate contracts (Class C(iv)), restrictive covenants (Class D(ii)), and equitable easements (Class D(iii))); or (2) the doctrine of notice — equitable interests not registrable as land charges bind everyone except a bona fide purchaser for value of a legal estate without notice (actual, constructive, or imputed).",
    "details": "If a registrable land charge is not registered, it is void against a purchaser of the legal estate for money or money's worth (s.4 LCA 1972) — even if the purchaser had actual knowledge (Midland Bank v Green [1981]). Constructive notice: the purchaser should have discovered the interest through reasonable inquiries and inspections. First registration is now triggered by specified dispositions (s.4 LRA 2002), so unregistered land is shrinking.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-lease-requirements",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "lease",
      "requirements",
      "exclusive possession",
      "term",
      "Street v Mountford"
    ],
    "crossCutting": false,
    "front": "What are the essential requirements for a lease?",
    "back": "A lease requires: (1) exclusive possession — the tenant has the right to exclude all others, including the landlord (Street v Mountford [1985]); (2) a certain term — the duration must be fixed or capable of being rendered certain (Lace v Chantler [1944]); (3) the grant must be at a rent or for consideration (though rent is not strictly essential after LPA 1925 s.205). The label the parties give the arrangement is not decisive — the court looks at the substance.",
    "details": "Street v Mountford [1985]: Lord Templeman — if exclusive possession is granted for a term at a rent, the arrangement is a lease regardless of the label. A licence grants mere permission to use, without exclusive possession. Bruton v London & Quadrant Housing Trust [2000]: a lease can be created even where the grantor has no estate in the land — the lease operates as a personal, enforceable agreement. A lease exceeding 3 years must be by deed (s.52 LPA 1925), otherwise it takes effect as an equitable lease (Walsh v Lonsdale principle).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-easement-requirements",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "easement",
      "Re Ellenborough Park",
      "dominant",
      "servient"
    ],
    "crossCutting": false,
    "front": "What are the four requirements for a valid easement (Re Ellenborough Park [1956])?",
    "back": "(1) There must be a dominant and a servient tenement. (2) The easement must accommodate (benefit) the dominant tenement — it must benefit the land, not merely the owner personally. (3) The dominant and servient tenements must be owned or occupied by different persons. (4) The right must be capable of forming the subject matter of a grant — it must be sufficiently definite, and not amount to exclusive possession of the servient land or a mere right of recreation.",
    "details": "Common easements: rights of way, rights of light, rights of drainage, rights to run services. A right of parking can be an easement (Moncrieff v Jamieson [2007]) if it does not deprive the servient owner of all reasonable use. Creation: express grant/reservation, implied grant (necessity, common intention, Wheeldon v Burrows, s.62 LPA 1925), prescription (20 years' use under the Prescription Act 1832, or at common law). Legal easements must be by deed and registered.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-covenants-freehold",
    "type": "distinction",
    "module": "Property Law",
    "tags": [
      "freehold covenants",
      "burden",
      "benefit",
      "restrictive",
      "positive"
    ],
    "crossCutting": false,
    "front": "Distinguish the rules for the running of the benefit and burden of freehold covenants.",
    "back": "The benefit of both positive and restrictive covenants can run at law (s.78 LPA 1925, P&A Swift v Combined English Stores [1989]) if the covenant touches and concerns the land and was intended to benefit successors. The burden of a restrictive covenant can run in equity (Tulk v Moxhay (1848)) if: (1) it is negative in nature, (2) it was made for the protection of land retained by the covenantee, (3) the burden was intended to run, and (4) the successor has notice. The burden of a positive covenant does NOT run with the land at common law or in equity.",
    "details": "The non-running of positive covenants' burden is a significant limitation — workarounds include: indemnity covenants, Halsall v Brizell (mutual benefit and burden), leasehold structure, commonhold (Commonhold and Leasehold Reform Act 2002), or estate rentcharge. In registered land, restrictive covenants should be protected by notice on the register (or they are overriding if the beneficiary is in actual occupation). Modification/discharge: s.84 LPA 1925 (Upper Tribunal).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-mortgage-creation",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "mortgage",
      "charge by way of legal mortgage",
      "LPA 1925"
    ],
    "crossCutting": false,
    "front": "How is a legal mortgage created over registered land?",
    "back": "A legal mortgage over registered land is created by a charge by deed expressed to be by way of legal mortgage (s.87 LPA 1925). The charge must be completed by registration at the Land Registry (s.27(2)(f) LRA 2002). Until registered, the charge operates only in equity. The mortgagee (lender) obtains a proprietary interest in the land as security for the debt, but the mortgagor (borrower) retains possession.",
    "details": "The mortgagor has an equity of redemption — the right to redeem the property by repaying the debt. Any clause that prevents or restricts this right may be struck down as a 'clog on the equity of redemption' (Fairclough v Swan Brewery [1912]). The mortgagee has remedies on default: (1) sale (s.101 LPA 1925, subject to s.103 conditions), (2) possession (Four-Maids v Dudley Marshall [1957] — the right exists from the date of the mortgage), (3) foreclosure (rare), (4) appointment of a receiver.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-mortgagee-power-sale",
    "type": "application",
    "module": "Property Law",
    "tags": [
      "mortgage",
      "power of sale",
      "duty",
      "best price"
    ],
    "crossCutting": false,
    "front": "A mortgagee exercises the power of sale and sells the property at auction without advertising the sale or obtaining a valuation. The sale price is 60% of market value. Can the mortgagor challenge the sale?",
    "back": "Yes. While the mortgagee has a power of sale (s.101 LPA), they owe a duty to the mortgagor to take reasonable care to obtain the true market value or the best price reasonably obtainable at the time (Cuckmere Brick v Mutual Finance [1971]). Selling without advertising or valuation, achieving only 60% of market value, suggests a breach of this duty. The mortgagor can claim damages for the shortfall.",
    "details": "The duty is not to get the best price — but to take reasonable steps to obtain the best price reasonably obtainable (Silven Properties v Royal Bank of Scotland [2004]). The mortgagee can choose when to sell and need not wait for market improvement (Tse Kwong Lam v Wong Chit Sen [1983]). But they must not sell at an undervalue through negligence. A sale to a connected party will be closely scrutinised. Palk v Mortgage Services Funding [1993] — the court may exercise discretion under s.91 LPA to order sale on terms.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-co-ownership-jt-tic",
    "type": "distinction",
    "module": "Property Law",
    "tags": [
      "co-ownership",
      "joint tenancy",
      "tenancy in common",
      "four unities"
    ],
    "crossCutting": false,
    "front": "Distinguish joint tenancy from tenancy in common.",
    "back": "Joint tenancy: co-owners hold as one entity. The key feature is the right of survivorship (jus accrescendi) — on death, the deceased's share passes automatically to the surviving joint tenant(s), regardless of any will. Requires four unities: possession, interest, title, and time. Tenancy in common: each co-owner has a distinct (though undivided) share that can be unequal. No right of survivorship — the share passes under the deceased's will or intestacy. Only the unity of possession is required.",
    "details": "Since 1925, the legal estate can only be held as a joint tenancy (max 4 trustees — s.34 LPA 1925), but the equitable/beneficial interest can be held as either. Words of severance ('in equal shares', 'equally') create a tenancy in common in equity. Severance of an equitable joint tenancy creates a tenancy in common: methods include (a) acting on one's share (Williams v Hensman (1861)), (b) mutual agreement, (c) mutual conduct, (d) written notice under s.36(2) LPA 1925.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-tlata-1996",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "TLATA 1996",
      "trust of land",
      "s14 application",
      "occupation rights"
    ],
    "crossCutting": true,
    "front": "What are the key provisions of the Trusts of Land and Appointment of Trustees Act 1996?",
    "back": "TLATA replaced the old trust for sale with the 'trust of land.' Key provisions: s.6 — trustees have all the powers of an absolute owner (subject to limitations). S.11 — trustees must consult adult beneficiaries in possession so far as practicable. S.12 — beneficiaries entitled to occupy trust land if the purposes of the trust include occupation. S.13 — trustees may restrict occupation. S.14 — any person with an interest may apply to the court for an order relating to the exercise of trustees' functions. S.15 — factors the court must consider on a s.14 application.",
    "details": "S.15 factors: (1) the intentions of the person(s) who created the trust, (2) the purposes for which the trust property is held, (3) the welfare of any minor who occupies or might occupy the land, (4) the interests of any secured creditor of any beneficiary. Where a trustee in bankruptcy applies: s.335A Insolvency Act 1986 overrides s.15 — after one year, the court shall assume creditors' interests outweigh all other considerations unless exceptional circumstances (Re Citro [1991]). Cross-cuts with Equity & Trusts.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-adverse-possession-lra2002",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "adverse possession",
      "LRA 2002",
      "registered land",
      "10-year rule"
    ],
    "crossCutting": false,
    "front": "How does adverse possession work for registered land under the LRA 2002?",
    "back": "Under Schedule 6 LRA 2002: (1) After 10 years of adverse possession, the squatter may apply to be registered as proprietor. (2) The registered proprietor is notified and has 65 business days to object. (3) If the proprietor objects, the application is rejected (unless an exception applies — e.g. estoppel, other entitlement, boundary dispute). (4) If rejected, the proprietor has 2 years to evict the squatter. If they fail to do so, the squatter can apply again after 2 years and must be registered.",
    "details": "This is a much harder regime than the old 12-year limitation period (which still applies to unregistered land under the Limitation Act 1980). The LRA 2002 regime gives registered proprietors the opportunity to defend their title. Pye v UK [2007] — the ECtHR (Grand Chamber) held that the old law (12-year dispossession without compensation) did not violate Article 1 Protocol 1 ECHR, but the LRA 2002 had already reformed the position. Key case on factual possession and animus possidendi: JA Pye v Graham [2003].",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-proprietary-estoppel",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "proprietary estoppel",
      "assurance",
      "reliance",
      "detriment"
    ],
    "crossCutting": true,
    "front": "What are the elements of proprietary estoppel?",
    "back": "Proprietary estoppel arises where: (1) an assurance (promise or representation) is made regarding rights in land, (2) the claimant relies on the assurance, and (3) the claimant suffers detriment in consequence. If established, the court has a broad discretion to satisfy the equity — the minimum to do justice (Jennings v Rice [2003]). The remedy is not limited to fulfilling the promise and may range from the transfer of the property to monetary compensation.",
    "details": "Thorner v Major [2009] — a sufficient assurance can be implied from conduct over many years (a farmer's cousin worked unpaid for 30 years in expectation of inheriting the farm). Cobbe v Yeoman's Row [2008] — proprietary estoppel requires an assurance about property rights, not merely commercial expectations. Guest v Guest [2022] — the SC held the starting point for the remedy is the expectation unless it would be out of all proportion to the detriment. Cross-cuts with Equity & Trusts and Contract Law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-overreaching",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "overreaching",
      "trust of land",
      "two trustees",
      "s2 LPA 1925"
    ],
    "crossCutting": true,
    "front": "What is overreaching and when does it operate?",
    "back": "Overreaching (s.2 LPA 1925) is the process by which equitable interests under a trust of land are transferred from the land to the purchase money when a purchaser pays capital money to at least two trustees (or a trust corporation). The purchaser takes free of the equitable interests, and the beneficiaries' interests attach to the proceeds of sale instead. This facilitates conveyancing by ensuring the purchaser gets clean title.",
    "details": "City of London BS v Flegg [1988]: even beneficiaries in actual occupation can be overreached if the purchase money is paid to two trustees. This overrides the overriding interest protection in the LRA. Williams & Glyn's Bank v Boland [1981]: overreaching did NOT occur because the mortgage advance was paid to only one trustee (the husband). The two-trustee requirement is a safeguard for beneficiaries. Cross-cuts with Equity & Trusts (trusts of land).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-constructive-trust-home",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "constructive trust",
      "common intention",
      "family home",
      "Lloyds Bank v Rosset"
    ],
    "crossCutting": true,
    "front": "When does a common intention constructive trust arise in the family home context?",
    "back": "Under Lloyds Bank v Rosset [1991] (as developed by Stack v Dowden [2007] and Jones v Kernott [2011]): where legal title is in one person's name, the other must show (1) a common intention that both should have a beneficial interest (express or inferred from conduct — typically direct financial contributions), and (2) detrimental reliance on that common intention. Where title is in joint names, beneficial interests are presumed equal (Stack v Dowden) but can be rebutted by evidence of contrary intention.",
    "details": "Jones v Kernott [2011]: the SC confirmed that where parties' intentions change over time, the court can impute an intention as to shares based on what is fair. The whole course of dealing is examined: financial contributions, caring for children, discussions about the property. Criticism: the law remains complex and uncertain; indirect contributions (domestic work) may be insufficient to establish a constructive trust. Cross-cuts with Equity & Trusts.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-severance-methods",
    "type": "application",
    "module": "Property Law",
    "tags": [
      "severance",
      "joint tenancy",
      "s36(2) LPA 1925",
      "Williams v Hensman"
    ],
    "crossCutting": false,
    "front": "A and B hold a flat as beneficial joint tenants. A writes to B: 'I wish to sever the joint tenancy so that we each own half.' A dies before B receives the letter. Has severance occurred?",
    "back": "Yes, likely. Under s.36(2) LPA 1925, a joint tenancy can be severed by written notice. The notice takes effect when it is 'given' — which means when it is delivered to the other joint tenant's address, not when it is read. Re 88 Berkeley Road [1971] held that a notice served by recorded delivery was effective even though the recipient had not actually read it. If the letter was properly addressed and sent, severance occurred before A's death.",
    "details": "Other methods of severance (Williams v Hensman (1861)): (1) an act operating on one's share (e.g. selling or mortgaging one's interest — the purchaser/mortgagee becomes a tenant in common); (2) mutual agreement (all joint tenants agree, even informally — Burgess v Rawnsley [1975]); (3) mutual conduct / course of dealing (the parties' behaviour shows the joint tenancy has been treated as severed). A will cannot sever a joint tenancy because it only operates on death.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-leasehold-covenants",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "leasehold covenants",
      "privity",
      "Landlord and Tenant Act 1995"
    ],
    "crossCutting": false,
    "front": "How do leasehold covenants bind assignees of the lease?",
    "back": "For leases granted on or after 1 January 1996 (Landlord and Tenant (Covenants) Act 1995): the benefit and burden of all covenants (except personal ones) pass automatically on assignment. The original tenant is released from liability on a lawful assignment. For pre-1996 leases: the original tenant remains liable on privity of contract for the entire lease term. The benefit/burden runs with the land for covenants that 'touch and concern' the land (Spencer's Case (1583)).",
    "details": "Under the 1995 Act, the landlord can require an 'authorised guarantee agreement' (AGA) — the outgoing tenant guarantees the incoming assignee's performance. If the landlord wishes to recover from a former tenant or guarantor (under pre-1996 leases or AGAs), s.17 of the 1995 Act requires the landlord to serve notice within 6 months. The tenant who pays under an AGA can claim an 'overriding lease' under s.19.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-forfeiture-lease",
    "type": "principle",
    "module": "Property Law",
    "tags": [
      "forfeiture",
      "lease",
      "breach of covenant",
      "s146 LPA 1925",
      "relief"
    ],
    "crossCutting": false,
    "front": "What is the procedure for forfeiture of a lease for breach of covenant?",
    "back": "For breach of a non-rent covenant: the landlord must serve a s.146 LPA 1925 notice specifying the breach, requiring remedy (if capable of remedy), and requiring compensation. The tenant has a reasonable time to remedy the breach. If unremedied, the landlord can forfeit by peaceable re-entry or court proceedings. The tenant (and sub-tenants/mortgagees) can apply for relief from forfeiture under s.146(2). For non-payment of rent: formal demand is required (unless waived by the lease or s.210 Common Law Procedure Act 1852 applies). Relief is available under County Courts Act 1984 s.138 or the court's inherent jurisdiction.",
    "details": "Whether a breach is capable of remedy: breach of a negative covenant is generally incapable of remedy (Rugby School v Tannahill [1935]) — but this is not absolute (Savva v Hussein [1996] — stigma cases). Breach of a positive covenant is generally remediable if the mischief can be corrected. Waiver: the landlord loses the right to forfeit if they do an unequivocal act recognising the lease as continuing after becoming aware of the breach (e.g. accepting rent — Segal Securities v Thoseby [1963]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-implied-easement-s62",
    "type": "case",
    "module": "Property Law",
    "tags": [
      "s62 LPA 1925",
      "implied easement",
      "diversity of occupation",
      "Wood v Waddington"
    ],
    "crossCutting": false,
    "front": "How does s.62 LPA 1925 operate to create easements on conveyance?",
    "back": "S.62 provides that a conveyance of land includes all privileges, easements, rights, and advantages appertaining to or enjoyed with the land. It can elevate a licence or permission enjoyed over neighbouring land into a legal easement when the benefited land is conveyed. Traditionally, it required prior diversity of occupation (Sovmots v Secretary of State [1979]), but Wood v Waddington [2015] suggested this is not always necessary where a right was being openly exercised.",
    "details": "Wright v Macadam [1949]: a tenant's licence to use a coal shed was converted into an easement on the grant of a new lease. S.62 operates automatically on any 'conveyance' (which includes a lease — s.205 LPA). It can be excluded by contrary intention in the conveyance. Compare Wheeldon v Burrows (1879): on a grant by a common owner, quasi-easements that are continuous and apparent, necessary for reasonable enjoyment, and used at the time of the grant may pass as implied easements.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-boland-actual-occupation",
    "type": "case",
    "module": "Property Law",
    "tags": ["actual occupation", "overriding interest", "Boland", "beneficial interest"],
    "crossCutting": false,
    "front": "What did Williams & Glyn's Bank v Boland [1981] establish about overriding interests and actual occupation?",
    "back": "A spouse (or any person) with a beneficial interest under a trust who is in actual occupation of registered land has an overriding interest that binds a purchaser (including a mortgagee) even though the interest is not on the register. The bank's mortgage was subject to Mrs Boland's equitable interest because she was in actual occupation and her husband (sole legal owner) had mortgaged the property without her knowledge.",
    "details": "Lord Wilberforce rejected the argument that a wife's occupation was merely 'shadow' occupation of her husband. 'Actual occupation' requires physical presence — it is a question of fact. The decision created concern for lenders, leading to: (1) the practice of requiring all adult occupiers to consent to mortgages; (2) LRA 2002 Sch 3 para 2 narrowing the protection (interest must be obvious on reasonably careful inspection, or the purchaser must have actual knowledge). City of London BS v Flegg [1988]: overreaching defeats even an occupier's overriding interest if capital money is paid to two trustees.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-flegg-overreaching",
    "type": "case",
    "module": "Property Law",
    "tags": ["overreaching", "Flegg", "two trustees", "actual occupation"],
    "crossCutting": false,
    "front": "What did City of London Building Society v Flegg [1988] decide about the interaction between overreaching and overriding interests?",
    "back": "Where capital money is paid to two trustees, equitable interests under a trust of land are overreached — they detach from the land and attach to the proceeds of sale (s.2 LPA 1925). This applies even if the beneficiaries are in actual occupation. The Fleggs' beneficial interests were overreached by the mortgage because it was granted by two legal owners (their daughter and son-in-law), so their overriding interest claim failed.",
    "details": "This resolved the tension between Boland (actual occupation protects beneficial interests) and overreaching (payment to two trustees defeats equitable interests). The key: if the purchaser/lender pays two trustees, overreaching operates and the beneficiary's remedy is against the trustees personally for the proceeds, not against the land. If only one trustee receives the money (as in Boland), overreaching does not occur and the beneficial interest binds the purchaser. Practical consequence: lenders insist on all legal owners being party to the mortgage.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-midland-bank-green",
    "type": "case",
    "module": "Property Law",
    "tags": ["land charges", "unregistered land", "Midland Bank v Green", "void"],
    "crossCutting": false,
    "front": "What did Midland Bank Trust Co v Green [1981] establish about registration of land charges?",
    "back": "An unregistered land charge is void against a purchaser of the legal estate for money or money's worth — even if the purchaser had actual knowledge of the interest (s.4 Land Charges Act 1972). A father granted his son an option to purchase (an estate contract, Class C(iv)). The son failed to register it. The father then sold the land to his wife for £500 (well below market value) who had full knowledge of the option. The option was void against her.",
    "details": "Lord Wilberforce: the registration system is designed to provide certainty — allowing actual knowledge to override the statutory scheme would undermine its purpose. 'Money or money's worth' need not be adequate consideration — £500 for land worth £40,000 was sufficient. This harsh result illustrates the 'registration gap' problem in unregistered land. Contrast: in registered land under LRA 2002, interests protected by notice or as overriding interests bind regardless; unprotected interests are defeated by a registered disposition for value (s.29).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-prescription-easements",
    "type": "principle",
    "module": "Property Law",
    "tags": ["prescription", "easement", "long use", "Prescription Act 1832"],
    "crossCutting": false,
    "front": "How can an easement be acquired by prescription?",
    "back": "Prescription allows an easement to be acquired through long use — 20 years of continuous use as of right (without force, secrecy, or permission — nec vi, nec clam, nec precario). Three methods: (1) common law prescription (use since time immemorial, 1189); (2) lost modern grant (a legal fiction — the court presumes a grant was made but has been lost); (3) Prescription Act 1832 — 20 years' uninterrupted use (40 years makes the right absolute and indefeasible).",
    "details": "The use must be: (a) by or on behalf of a freehold owner against a freehold owner; (b) continuous and uninterrupted; (c) as of right (not by force, stealth, or licence). Mills v Silver [1991]: tolerance by the servient owner does not amount to permission. Under the Prescription Act 1832 s.2, 20 years' use gives a presumption of a grant; 40 years makes the right absolute unless enjoyed by written consent. Prescription cannot operate against registered land to create new legal easements unless the conditions of LRA 2002 Sch 3 para 3 are met.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-wheeldon-v-burrows",
    "type": "case",
    "module": "Property Law",
    "tags": ["implied easement", "Wheeldon v Burrows", "quasi-easement", "grant"],
    "crossCutting": false,
    "front": "What is the rule in Wheeldon v Burrows (1879) for implied grant of easements?",
    "back": "On a grant (sale or lease) of part of land by a common owner, easements will be implied in favour of the grantee over the retained land if, prior to the grant, the quasi-easement was: (1) continuous and apparent (i.e. discoverable on reasonable inspection); (2) necessary for the reasonable enjoyment of the land granted; and (3) in use at the time of the grant for the benefit of the part granted.",
    "details": "A 'quasi-easement' is a right that would be an easement if the dominant and servient land were in separate ownership — since both belong to the same person, it is merely a use of one part for the benefit of another. On sale or lease, the quasi-easement ripens into a true easement by implication. Wheeldon v Burrows only operates on a grant (not a reservation — the grantor retains no implied rights except necessity). Compare s.62 LPA 1925 which can also create easements on conveyance. Borman v Griffith [1930]: a right of way over a private road was implied under Wheeldon v Burrows.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-bruton-v-lqht",
    "type": "case",
    "module": "Property Law",
    "tags": ["lease", "Bruton", "no estate", "tenancy by estoppel"],
    "crossCutting": false,
    "front": "What did Bruton v London & Quadrant Housing Trust [2000] decide about the creation of leases?",
    "back": "The House of Lords held that a lease can be created even where the grantor has no legal estate in the land. LQHT, a charitable trust with only a licence from the council, granted Bruton exclusive possession for a term at a rent — this created a lease (applying Street v Mountford). The lease bound the parties as a contractual relationship even though LQHT had no estate to grant.",
    "details": "Lord Hoffmann: a lease is a contractual relationship — it does not require the grantor to have a proprietary estate. The 'lease' created in Bruton was binding between the parties but did not create a proprietary interest binding third parties (since LQHT had no estate). This enabled Bruton to enforce the landlord's repairing covenant under s.11 Landlord and Tenant Act 1985. The decision was controversial because it separated the concept of a lease as contract from a lease as estate. Kay v Lambeth LBC [2006] confirmed that a Bruton tenancy does not bind the head landlord.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-walsh-v-lonsdale",
    "type": "case",
    "module": "Property Law",
    "tags": ["equitable lease", "Walsh v Lonsdale", "specific performance", "formalities"],
    "crossCutting": false,
    "front": "What is the principle in Walsh v Lonsdale (1882) regarding equitable leases?",
    "back": "Where parties enter into a specifically enforceable agreement for a lease but fail to execute a deed (required by s.52 LPA 1925 for leases exceeding 3 years), the agreement operates as an equitable lease. Since equity regards as done that which ought to be done, the tenant holds under an equitable lease on the same terms as the intended legal lease, provided the agreement satisfies s.2 LP(MP)A 1989 (writing, signed by both parties, containing all terms).",
    "details": "The equitable lease is enforceable between the parties but is weaker than a legal lease: (1) it may not bind third parties (in registered land, it must be protected by notice; in unregistered land, it is registrable as an estate contract Class C(iv)); (2) equitable remedies are discretionary. A legal lease of 3 years or less can be created without a deed if it takes effect in possession at the best rent with no premium (s.54(2) LPA 1925). Coatsworth v Johnson (1886): an equitable lease does not confer the same statutory protections as a legal lease.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-alteration-rectification-lra",
    "type": "principle",
    "module": "Property Law",
    "tags": ["alteration", "rectification", "register", "LRA 2002", "indemnity"],
    "crossCutting": false,
    "front": "When can the register of title be altered or rectified under the LRA 2002?",
    "back": "Schedule 4 LRA 2002 allows alteration of the register to: (1) correct a mistake, (2) bring the register up to date, (3) give effect to an estate, right, or interest excepted from registration. Alteration that prejudicially affects the title of a registered proprietor is called 'rectification.' For a proprietor in possession, rectification is only available if: (a) they consented, (b) it would be unjust not to rectify, or (c) the proprietor caused or substantially contributed to the mistake by fraud or lack of proper care.",
    "details": "The protection of the proprietor in possession reflects the principle that the register should be conclusive. If rectification is ordered, the person suffering loss is entitled to an indemnity from the Land Registry (Sch 8 LRA 2002). If rectification is refused, the person who would have benefited may claim indemnity for their loss. NRAM v Evans [2017]: the SC confirmed that a forged transfer could be rectified even against a subsequent innocent purchaser. The system aims to balance the 'insurance' principle (register is guaranteed) with justice in cases of mistake or fraud.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-cobbe-v-yeomans-row",
    "type": "case",
    "module": "Property Law",
    "tags": ["proprietary estoppel", "Cobbe", "commercial context", "certainty"],
    "crossCutting": false,
    "front": "What did Cobbe v Yeoman's Row Management Ltd [2008] decide about proprietary estoppel in commercial contexts?",
    "back": "The House of Lords held that proprietary estoppel cannot be founded on an expectation of an interest in land where the parties knew their agreement was not legally binding (being 'subject to contract'). Mr Cobbe, a property developer, spent time and money obtaining planning permission in reliance on an oral understanding, but the landowner reneged. His estoppel claim failed because in a commercial context, both parties understood that no binding obligation existed until contracts were exchanged.",
    "details": "Lord Scott: estoppel requires a belief or expectation that the claimant has or will acquire a right in land — not merely a commercial expectation. Lord Walker: distinguished domestic/family cases (where informality is expected) from commercial dealings (where parties know they need formal contracts). Contrast Thorner v Major [2009]: in a family/farming context, oblique assurances over many years were sufficient. The combined effect of Cobbe and Thorner: estoppel is harder to establish in commercial dealings but remains available in family contexts where informality is the norm.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-guest-v-guest",
    "type": "case",
    "module": "Property Law",
    "tags": ["proprietary estoppel", "remedy", "Guest v Guest", "expectation"],
    "crossCutting": false,
    "front": "How did Guest v Guest [2022] clarify the approach to remedies in proprietary estoppel?",
    "back": "The Supreme Court held that the starting point for the remedy in proprietary estoppel is the claimant's expectation (what they were promised), not the detriment suffered. The expectation should be fulfilled unless doing so would be out of all proportion to the detriment. Lord Briggs: the court should first identify the expectation, then consider whether the expectation-based remedy is proportionate to the detriment — if so, give effect to the expectation; if not, adjust downward.",
    "details": "Andrew Guest worked on his parents' farm for decades in expectation of inheriting it. His parents later excluded him from their wills. The SC awarded him a share of the farming business. This settled a long-running debate: earlier cases like Jennings v Rice [2003] emphasised proportionality and the 'minimum equity to do justice' (sometimes leading to detriment-based awards). Guest v Guest shifted the presumption: start with the expectation, only reduce if disproportionate. The court must still consider all circumstances, including the impact on third parties.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-lpa-s199-notice",
    "type": "principle",
    "module": "Property Law",
    "tags": ["notice", "constructive notice", "s199 LPA 1925", "bona fide purchaser"],
    "crossCutting": false,
    "front": "What is the doctrine of notice and how does it operate in unregistered land?",
    "back": "In unregistered land, equitable interests (not registrable as land charges) bind everyone except a bona fide purchaser for value of a legal estate without notice. Notice can be: (1) actual — the purchaser actually knew of the interest; (2) constructive — the purchaser would have discovered it had they made reasonable inquiries and inspections (s.199 LPA 1925); (3) imputed — knowledge of the purchaser's agent is imputed to the purchaser.",
    "details": "Constructive notice includes: (a) inspecting the land (an occupier's presence may give constructive notice of their rights — Hunt v Luck [1902]); (b) investigating the title deeds for the statutory period (15 years under s.23 LPA 1969). Kingsnorth Finance v Tizard [1986]: the bank's surveyor visited when the wife was absent but her belongings were there — constructive notice of her occupation and equitable interest. In registered land, the doctrine of notice is largely replaced by the registration system, but it remains relevant for overriding interests and equitable interests in unregistered land.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-commonhold",
    "type": "principle",
    "module": "Property Law",
    "tags": ["commonhold", "freehold flat", "positive covenants", "CLRA 2002"],
    "crossCutting": false,
    "front": "What is commonhold and what problem does it solve?",
    "back": "Commonhold (Commonhold and Leasehold Reform Act 2002) is a form of freehold ownership designed for multi-unit developments (e.g. blocks of flats). Each unit holder owns the freehold of their unit, and the common parts are owned and managed by a commonhold association (a company limited by guarantee of which all unit holders are members). It solves the positive covenant problem — positive obligations (repair, contribute to maintenance) are enforceable against successive unit holders because they bind as part of the commonhold community statement.",
    "details": "The positive covenant problem: at common law, the burden of positive freehold covenants does not run with the land (Rhone v Stephens [1994]). This means flat owners who hold freehold cannot be compelled by covenant to contribute to repairs. The leasehold system avoids this (covenants run in leases) but at the cost of diminishing assets. Commonhold was intended to replace leasehold for flats, but has been rarely used since 2004 due to practical difficulties (lender reluctance, inability to convert existing buildings without unanimous consent). The Law Commission recommended reforms in 2020.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-stack-v-dowden",
    "type": "case",
    "module": "Property Law",
    "tags": ["Stack v Dowden", "joint ownership", "beneficial shares", "presumption"],
    "crossCutting": true,
    "front": "What presumption did Stack v Dowden [2007] establish for jointly owned property?",
    "back": "Where property is conveyed into joint names, equity follows the law — the beneficial interest is presumed to be held equally (50:50). This presumption can be rebutted, but the burden on the party claiming unequal shares is heavy: they must show the parties had a different common intention, assessed by examining the whole course of dealing between them (financial contributions, discussions, arrangements regarding the property).",
    "details": "Baroness Hale identified relevant factors: advice or discussions about ownership shares, reasons for the property being in joint names, the purpose of the purchase, how the mortgage was arranged, and how finances were conducted generally. Stack v Dowden concerned an unmarried couple — Ms Dowden had contributed significantly more financially and succeeded in claiming a 65:35 split. Jones v Kernott [2011] developed this further: the court can impute an intention to the parties where their actual intention cannot be ascertained, based on what is fair. This cross-cuts with Equity & Trusts (constructive trusts).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-mortgage-undue-influence",
    "type": "case",
    "module": "Property Law",
    "tags": ["undue influence", "mortgage", "Etridge", "notice", "surety"],
    "crossCutting": true,
    "front": "What did Royal Bank of Scotland v Etridge (No 2) [2002] establish about undue influence and mortgages?",
    "back": "Where a wife (or cohabitant) charges her interest in the family home to secure her partner's business debts, the lender is put on inquiry that the surety's consent may have been procured by undue influence. To avoid being affected by the undue influence, the lender must ensure the surety received independent legal advice. If the lender fails to take these steps, the mortgage/charge is voidable at the surety's instance.",
    "details": "Lord Nicholls set out the steps a lender must take: (1) communicate directly with the surety, informing them that the bank needs confirmation from a solicitor that the nature and effect of the documents have been explained; (2) the solicitor must advise the surety in a face-to-face meeting without the debtor present, explaining the transaction, the risks, and that the surety has a choice. The bank is entitled to rely on the solicitor's confirmation. If these steps are not taken, the lender has constructive notice of the undue influence. Barclays Bank v O'Brien [1994] first established the framework; Etridge refined and consolidated it.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "prop-rhone-v-stephens",
    "type": "case",
    "module": "Property Law",
    "tags": ["positive covenant", "burden", "Rhone v Stephens", "freehold"],
    "crossCutting": false,
    "front": "What did Rhone v Stephens [1994] confirm about the running of positive freehold covenants?",
    "back": "The House of Lords confirmed the long-standing rule that the burden of a positive covenant does not run with freehold land — neither at common law nor in equity. A covenant to keep a roof in repair, made between the original parties, could not be enforced against a successor in title to the covenantor's land. Only the benefit (not the burden) of positive covenants runs.",
    "details": "Lord Templeman declined to reverse the rule established in Austerberry v Oldham Corp (1885). Workarounds for enforcing positive obligations against successors: (1) indemnity covenant chains; (2) Halsall v Brizell [1957] — the benefit and burden principle (a person who takes the benefit of a right must also accept the burden attached to it); (3) use of leasehold structure (covenants in leases run under the Landlord and Tenant (Covenants) Act 1995); (4) estate rentcharge with right of entry; (5) commonhold (CLRA 2002). The Law Commission has repeatedly recommended reform but no legislation has followed.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
