// Auto-generated from cards.js split. Module: Public Law
export const publicLawCards = [
  {
    "id": "4",
    "type": "distinction",
    "module": "Public Law",
    "tags": [
      "judicial review",
      "illegality",
      "irrationality"
    ],
    "crossCutting": true,
    "related": [
      "publaw-wednesbury-unreasonableness",
      "10"
    ],
    "front": "Distinguish illegality from irrationality as grounds for judicial review (CCSU framework).",
    "back": "Illegality: the decision-maker misunderstood or misapplied the law. Irrationality (Wednesbury): the decision was so outrageous no reasonable authority could have reached it. Illegality = what law was applied; irrationality = how discretion was exercised within the correct framework.",
    "details": "Lord Diplock in CCSU v Minister for Civil Service [1985]. Third ground: procedural impropriety. Cross-cuts: Wednesbury applies in planning, immigration, human rights contexts with varying intensity (anxious scrutiny).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "10",
    "type": "application",
    "module": "Public Law",
    "tags": [
      "wednesbury",
      "proportionality",
      "human rights"
    ],
    "crossCutting": true,
    "related": [
      "4",
      "publaw-wednesbury-unreasonableness"
    ],
    "front": "A local authority refuses planning permission for a mosque, citing 'community cohesion concerns' without evidence. Which JR standard applies?",
    "back": "If Art 9 ECHR is engaged, proportionality applies rather than bare Wednesbury. Four stages: (1) sufficiently important objective? (2) rationally connected? (3) less intrusive measure? (4) fair balance? Without evidence, likely fails stages 2 and 4.",
    "details": "R (Daly) v SSHD [2001] — proportionality more exacting than Wednesbury. Bank Mellat v HM Treasury (No 2) [2013] — four-stage test. Cross-cuts Public Law with Human Rights.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publiclaw-parliamentary-sovereignty",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "parliamentary sovereignty",
      "Dicey",
      "constitution",
      "supreme parliament",
      "HRA"
    ],
    "crossCutting": false,
    "front": "State Dicey's classic doctrine of parliamentary sovereignty and its contemporary limitations.",
    "back": "Under Dicey (1885): Parliament can make or unmake any law; no court can override a valid Act of Parliament; and no Parliament can bind its successors. Contemporary qualifications: HRA 1998 (courts can issue a declaration of incompatibility — s4); EU law (during membership — Factortame); devolution; the rule of law (Jackson v Attorney General [2005] — obiter suggestions of constitutional limits).",
    "details": "Dicey saw sovereignty as the cornerstone of the UK's unwritten constitution. The principle means courts apply Acts of Parliament without questioning their validity — they cannot strike down primary legislation. HRA 1998 does not enable courts to disapply legislation (contrast with EU law during membership): s4 declarations of incompatibility are not binding on Parliament (s4(6) HRA). Jackson: HL upheld Parliament Acts procedure but Lords Steyn and Hope suggested courts might refuse to apply a manifestly unconstitutional Act. Constitutional statutes (R (HS2 Action Alliance) [2014]) may have higher protection from implied repeal. Academic debate: common law constitutionalism (Laws LJ) vs political constitutionalism.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publiclaw-rule-of-law-dicey",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "rule of law",
      "Dicey",
      "supremacy of law",
      "equality",
      "constitution"
    ],
    "crossCutting": false,
    "front": "State Dicey's three meanings of the rule of law.",
    "back": "Dicey identified three elements: (1) Supremacy of regular law — no punishment except for a breach of established law; arbitrary power is excluded; (2) Equality before the law — every person, whatever their rank, is subject to the ordinary law and courts; (3) Constitutional law is the result of judicial decisions — rights are secured by the courts, not merely declared in a text.",
    "details": "Dicey wrote in 1885, contrasting England with France (where droit administratif gave special rules for the state). Critics note that equality is formal rather than substantive — the wealthy have access advantages. Raz's thin conception of the rule of law (The Rule of Law and Its Virtue, 1977): laws must be prospective, clear, stable, publicly accessible, and administered by independent courts. Fuller's eight requirements of legality (inner morality of law) also overlap — law must be general, public, non-retroactive, clear, consistent, possible to comply with, stable, and administered as declared. The rule of law is now a constitutional principle recognised in constitutional statutes (Constitutional Reform Act 2005, s1) and judicial review.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publiclaw-hra-s3-s4",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "HRA 1998",
      "s3",
      "s4",
      "compatible interpretation",
      "declaration of incompatibility",
      "ECHR"
    ],
    "crossCutting": false,
    "front": "What are the key mechanisms of the Human Rights Act 1998 for interpreting legislation?",
    "back": "S3 HRA: Courts must read and give effect to primary and secondary legislation in a way compatible with ECHR rights 'so far as it is possible to do so'. S4 HRA: Where compatibility cannot be achieved, a higher court may issue a declaration of incompatibility — this does not affect the validity or continuing operation of the provision; Parliament must act to amend it (s10 fast-track).",
    "details": "S3 is a strong interpretive obligation: courts can 'read in' words or 'read down' the effect of legislation to achieve compatibility (R v A (No 2) [2001] — rape shield provision read down). But courts cannot use s3 to legislate or go against the grain of legislation (Bellinger v Bellinger [2003] — could not read the Matrimonial Causes Act to allow a transgender woman to marry; declaration of incompatibility issued instead). S4 declarations have no direct legal effect — they signal to Parliament, which has remedied most declarations (Anderson v Secretary of State [2002] — mandatory life sentence tariff set by Home Secretary, incompatible with Art 6). S6 HRA: unlawful for public authorities to act incompatibly with Convention rights.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publiclaw-legitimate-expectation",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "legitimate expectation",
      "procedural",
      "substantive",
      "Coughlan",
      "judicial review"
    ],
    "crossCutting": false,
    "front": "What is legitimate expectation in public law and how does it arise?",
    "back": "Legitimate expectation (LE) arises where a public body's promise, representation, or established practice leads an individual to expect either a procedural right (to be consulted: GCHQ case) or a substantive benefit (to receive a particular outcome: R v North and East Devon HA ex parte Coughlan [2001]). Frustrating a legitimate expectation without sufficient reason is unlawful.",
    "details": "Coughlan: the health authority promised a severely disabled patient she could live in a care home for life. When it sought to close the home, the CA held this was an abuse of power — the promise was a substantive LE and could only be overridden for an overriding public interest. The court applies higher scrutiny to substantive LEs (not mere Wednesbury review). Procedural LE — expectation of being consulted before an adverse decision — is easier to establish (AG of Hong Kong v Ng Yuen Shiu [1983]; GCHQ). LE must be clear and unequivocal; cannot arise from ultra vires representations (Ultra Vires principle limits LE: Reprotech v East Sussex CC [2002]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publiclaw-judicial-review-standing",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "judicial review",
      "standing",
      "sufficient interest",
      "s31 Senior Courts Act",
      "pressure groups"
    ],
    "crossCutting": false,
    "front": "What is the test for standing (locus standi) in judicial review proceedings?",
    "back": "Under s31(3) Senior Courts Act 1981 the claimant must have a 'sufficient interest' in the matter to which the claim relates. The test is applied broadly and contextually — the House of Lords in IRC v National Federation of Self-Employed and Small Businesses [1982] confirmed that 'sufficient interest' is not a purely threshold concept but is merged with the merits.",
    "details": "The flexible approach means that individuals directly affected by a decision clearly have standing. Representative bodies and pressure groups can have standing where they represent affected members or where there is no other realistic challenger: R v Secretary of State for Foreign Affairs ex parte World Development Movement [1995] — WDM had standing to challenge aid expenditure in Malaysia, applying factors including the importance of the issue, the absence of other challengers, and the statute's purpose. The courts are reluctant to allow 'busybody' interventions but will grant standing where a sufficiently substantial public interest is at stake. Contrast EU law — the much narrower direct and individual concern test under Art 263 TFEU.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-parliamentary-sovereignty",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "parliamentary sovereignty",
      "Dicey",
      "supremacy of Parliament"
    ],
    "crossCutting": false,
    "front": "What are the three components of Dicey's doctrine of parliamentary sovereignty?",
    "back": "Parliament: (1) can make or unmake any law on any subject (positive limb), (2) no Parliament can bind its successors — later Acts impliedly repeal earlier inconsistent ones (negative limb), and (3) no body, including the courts, can question the validity of an Act of Parliament. Parliament is the supreme legal authority in the UK constitution.",
    "details": "Pickin v British Railways Board [1974]: courts will not inquire into the process by which an Act was passed. But challenges have emerged: R (Jackson) v AG [2005] — obiter, some Law Lords suggested parliamentary sovereignty has limits. Factortame (No 2) [1991] — EU law took precedence over inconsistent domestic legislation (now altered post-Brexit). Thoburn v Sunderland CC [2002] — Laws LJ: 'constitutional statutes' cannot be impliedly repealed.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-rule-of-law",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "rule of law",
      "Dicey",
      "constitutionalism"
    ],
    "crossCutting": false,
    "front": "What are Dicey's three meanings of the rule of law?",
    "back": "(1) No person shall be punished except for a distinct breach of law established before the ordinary courts — the absence of arbitrary power. (2) Every person, regardless of rank, is subject to the ordinary law of the land administered by ordinary courts — equality before the law. (3) The constitution is the result of the ordinary law of the land — individual rights are protected by the common law, not a written constitution.",
    "details": "The modern rule of law has been developed beyond Dicey. Lord Bingham (2010) identified 8 sub-rules including: accessible law, questions of legal right decided by law not discretion, equality before the law, adequate protection of fundamental human rights, means for resolving disputes without undue cost or delay. The rule of law is acknowledged in s.1 Constitutional Reform Act 2005.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-separation-powers",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "separation of powers",
      "constitutional principle",
      "checks and balances"
    ],
    "crossCutting": false,
    "front": "How does the separation of powers operate in the UK constitution?",
    "back": "The separation of powers requires that the three branches of government — legislature (Parliament), executive (government/Crown), and judiciary (courts) — should be separate in function and personnel to prevent abuse of power. The UK has a 'partial' or 'fused' separation: the executive sits in Parliament and the Lord Chancellor historically straddled all three branches. The Constitutional Reform Act 2005 strengthened judicial independence by creating the Supreme Court and reforming the Lord Chancellor's role.",
    "details": "Key reforms: CRA 2005 created the Supreme Court (replacing the Appellate Committee of the House of Lords), established the Judicial Appointments Commission, and limited the Lord Chancellor's judicial role. Overlaps persist: ministers sit in Parliament; delegated legislation is made by the executive under parliamentary authority. The judiciary's role is to check executive power through judicial review.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-jr-procedural-impropriety",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "judicial review",
      "procedural impropriety",
      "natural justice",
      "fairness"
    ],
    "crossCutting": false,
    "front": "What is procedural impropriety as a ground for judicial review?",
    "back": "Procedural impropriety encompasses: (1) failure to comply with statutory procedural requirements, and (2) breach of the common law rules of natural justice — the right to a fair hearing (audi alteram partem) and the rule against bias (nemo judex in causa sua). The content of fairness is context-dependent and flexible (R v Secretary of State for the Home Department, ex p Doody [1994]).",
    "details": "Fair hearing: notice of the case against you, opportunity to make representations, reasons for the decision (Doody). Bias: actual bias, or the appearance of bias — 'would a fair-minded and informed observer conclude there was a real possibility of bias?' (Porter v Magill [2002]). Mandatory vs directory procedural requirements: breach of a mandatory requirement renders the decision void; breach of a directory one may not.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-hra-s3-s4",
    "type": "distinction",
    "module": "Public Law",
    "tags": [
      "HRA 1998",
      "s3 interpretation",
      "s4 declaration of incompatibility"
    ],
    "crossCutting": false,
    "front": "Distinguish the s.3 and s.4 powers under the Human Rights Act 1998.",
    "back": "S.3: courts must, so far as it is possible to do so, read and give effect to legislation in a way compatible with Convention rights — this is a strong interpretive obligation that can go beyond normal statutory interpretation. S.4: if it is not possible to read legislation compatibly, the higher courts may issue a 'declaration of incompatibility' — this does not affect the validity of the legislation and does not bind the parties, but signals to Parliament that a change is needed.",
    "details": "Ghaidan v Godin-Mendoza [2004] — s.3 used to read 'spouse' as including same-sex partner in the Rent Act. Bellinger v Bellinger [2003] — s.4 declaration issued regarding the Matrimonial Causes Act and transsexual persons because the change required was too fundamental for s.3. S.3 is the primary remedy; s.4 is the remedy of last resort. Under s.10, a 'remedial order' can amend incompatible legislation.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-prerogative-power",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "royal prerogative",
      "executive power",
      "reviewability"
    ],
    "crossCutting": false,
    "front": "What is the royal prerogative and is it subject to judicial review?",
    "back": "The royal prerogative is the residue of powers remaining in the Crown — powers that were formerly exercised by the monarch and now exercised by ministers. Examples: treaty-making, defence, mercy, passports. Since CCSU v Minister for Civil Service [1985], prerogative powers are subject to judicial review if their subject matter is justiciable. The court asks whether the nature of the power makes it suitable for judicial scrutiny.",
    "details": "Non-justiciable prerogatives traditionally included: treaty-making, defence, dissolution of Parliament, grant of honours. R (Miller) v Secretary of State [2017]: the SC held that triggering Article 50 required an Act of Parliament — the prerogative could not be used to remove statutory rights. R (Miller) v Prime Minister [2019]: prorogation of Parliament for 5 weeks was justiciable and unlawful.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-legitimate-expectation",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "legitimate expectation",
      "substantive",
      "procedural",
      "judicial review"
    ],
    "crossCutting": false,
    "front": "What is the doctrine of legitimate expectation in judicial review?",
    "back": "A legitimate expectation arises where a public body makes a clear, unambiguous, and unconditional promise or adopts a regular practice, giving rise to an expectation that it will act in a certain way. Procedural legitimate expectation: the right to be consulted before a decision is made. Substantive legitimate expectation: the right to a particular outcome. Frustrating either requires lawful justification.",
    "details": "R v North and East Devon HA, ex p Coughlan [2001]: the CA held that a promise of a 'home for life' gave rise to a substantive legitimate expectation — it was unfair to frustrate it. R (Bancoult) v Secretary of State [2008] — legitimate expectations can arise from official statements. The expectation must be reasonable and the representation must come from someone with authority.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-wednesbury-unreasonableness",
    "type": "case",
    "module": "Public Law",
    "tags": [
      "Wednesbury",
      "unreasonableness",
      "irrationality",
      "judicial review"
    ],
    "crossCutting": false,
    "front": "What is the Wednesbury unreasonableness test?",
    "back": "From Associated Provincial Picture Houses v Wednesbury Corporation [1948]: a decision is Wednesbury unreasonable if it is 'so unreasonable that no reasonable authority could ever have come to it.' This sets a very high threshold — the court does not substitute its own view but asks whether the decision falls outside the range of responses open to a reasonable decision-maker.",
    "details": "Lord Greene MR. The test has been criticised as circular and as setting too high a threshold. In practice, courts now often use the language of 'irrationality' (Lord Diplock in CCSU). Where fundamental rights are at stake, an 'anxious scrutiny' standard applies, which is more intensive than standard Wednesbury (R v Ministry of Defence, ex p Smith [1996]). In HRA cases, proportionality has largely replaced Wednesbury.",
    "related": [
      "4",
      "10"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-illegality-ground",
    "type": "application",
    "module": "Public Law",
    "tags": [
      "illegality",
      "ultra vires",
      "relevant considerations",
      "improper purpose"
    ],
    "crossCutting": false,
    "front": "A local council uses its statutory power to maintain public parks to ban all dogs, citing a desire to increase revenue from park cafes. Is this decision vulnerable to judicial review on the ground of illegality?",
    "back": "Likely yes. Illegality encompasses: (1) acting ultra vires (beyond statutory power), (2) using power for an improper purpose (the power is for park maintenance, not revenue generation — Padfield v Minister of Agriculture [1968]), (3) taking into account irrelevant considerations (cafe revenue), or (4) failing to consider relevant matters. The council has misdirected itself as to the purpose of its power.",
    "details": "Sub-categories of illegality: error of law (Anisminic v FCC [1969]), error of fact (E v Secretary of State for the Home Department [2004]), fettering discretion by adopting a rigid policy (British Oxygen v Minister of Technology [1971]), and unauthorised delegation (Carltona v Commissioners of Works [1943] — delegation is permitted within the departmental hierarchy).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-proportionality-test",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "proportionality",
      "HRA",
      "ECHR",
      "four-stage test"
    ],
    "crossCutting": false,
    "front": "What is the four-stage proportionality test applied in human rights judicial review?",
    "back": "From Bank Mellat v HM Treasury (No 2) [2013] (Lord Reed): (1) Is the objective sufficiently important to justify limiting a fundamental right? (2) Is the measure rationally connected to the objective? (3) Could a less intrusive measure have been used? (4) Has a fair balance been struck between the rights of the individual and the interests of the community?",
    "details": "Proportionality provides a more structured and intensive review than Wednesbury. It applies whenever Convention rights are engaged under the HRA 1998. R (Daly) v Secretary of State [2001] — Lord Steyn explained that proportionality requires the court to assess the balance struck by the decision-maker, not merely whether the decision is within the range of reasonable responses. The court may require the decision-maker to justify each stage.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-art10-expression",
    "type": "application",
    "module": "Public Law",
    "tags": [
      "Article 10",
      "freedom of expression",
      "ECHR",
      "qualified right"
    ],
    "crossCutting": true,
    "front": "A journalist is prosecuted under the Official Secrets Act for publishing a leaked government report about military spending. Does Article 10 ECHR provide a defence?",
    "back": "Article 10 protects freedom of expression but is a qualified right — it can be restricted under Art 10(2) if the restriction is (1) prescribed by law, (2) pursues a legitimate aim (e.g. national security), and (3) is necessary in a democratic society (i.e. proportionate). The court must balance the public interest in press freedom and open government against the legitimate aim of protecting national security.",
    "details": "Sunday Times v UK (1979): the ECtHR established that 'necessary in a democratic society' means a 'pressing social need' and the restriction must be proportionate. R v Shayler [2003]: the HL held the OSA restrictions on disclosures by security services personnel were compatible with Art 10 because adequate safeguards existed. Cross-cuts with Evidence (public interest immunity).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-miller-prorogation",
    "type": "case",
    "module": "Public Law",
    "tags": [
      "prorogation",
      "Miller",
      "parliamentary sovereignty",
      "justiciability"
    ],
    "crossCutting": false,
    "front": "What did the Supreme Court decide in R (Miller) v The Prime Minister [2019] regarding prorogation?",
    "back": "The SC (11-0) held that the advice to prorogue Parliament for five weeks was unlawful and void. The prorogation was justiciable because it affected the fundamental constitutional principle of parliamentary sovereignty and accountability. It was unlawful because it frustrated Parliament's ability to carry out its constitutional functions without reasonable justification.",
    "details": "Lady Hale and Lord Reed (joint judgment): the standard of review was whether the prorogation had the effect of frustrating Parliament's ability to carry out its constitutional functions and whether there was a reasonable justification. A prorogation of 5 weeks during the Brexit period, with no justification beyond the norm of 4-6 days, was disproportionate. The decision extended judicial review into previously non-justiciable territory.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-convention-rights-abs-qual",
    "type": "distinction",
    "module": "Public Law",
    "tags": [
      "ECHR",
      "absolute rights",
      "qualified rights",
      "limited rights"
    ],
    "crossCutting": false,
    "front": "Distinguish absolute, limited, and qualified Convention rights.",
    "back": "Absolute rights cannot be restricted under any circumstances (e.g. Art 3 — prohibition of torture; Art 4(1) — prohibition of slavery). Limited rights can be restricted in defined circumstances specified in the Article itself (e.g. Art 5 — right to liberty, subject to lawful arrest/detention). Qualified rights can be restricted if the restriction is prescribed by law, pursues a legitimate aim, and is necessary in a democratic society (e.g. Arts 8-11).",
    "details": "Art 3 is absolute — no derogation even in war or emergency (Chahal v UK [1996]). Art 5 lists exhaustive exceptions (e.g. lawful detention after conviction, mental health detention). Arts 8 (private life), 9 (religion), 10 (expression), 11 (association) each contain paragraph 2 specifying permitted restrictions. Art 15 permits derogation from most rights in times of emergency, but never from Art 3.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-standing-jr",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "standing",
      "sufficient interest",
      "judicial review",
      "locus standi"
    ],
    "crossCutting": false,
    "front": "Who has standing to bring a claim for judicial review?",
    "back": "Under s.31(3) Senior Courts Act 1981, the claimant must have a 'sufficient interest' in the matter. This is a flexible test assessed in relation to the subject matter and the claimant's connection to it (R v IRC, ex p National Federation of Self-Employed [1982]). Pressure groups and public interest organisations can have standing where the issue is of general public importance (R v Secretary of State, ex p World Development Movement [1995]).",
    "details": "The sufficient interest test is applied at two stages: the permission stage (relatively easy to satisfy) and the substantive hearing (more rigorously assessed). Factors for group standing: no other challenger, the importance of vindicating the rule of law, the expertise of the applicant, the nature of the breach. The claim must be brought promptly and in any event within 3 months (CPR 54.5).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-devolution",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "devolution",
      "Scotland",
      "Wales",
      "Northern Ireland",
      "Sewel convention"
    ],
    "crossCutting": false,
    "front": "What is devolution and how does it relate to parliamentary sovereignty?",
    "back": "Devolution is the transfer of powers from the UK Parliament to elected bodies in Scotland (Scotland Act 1998), Wales (Government of Wales Act 2006), and Northern Ireland (Northern Ireland Act 1998). These bodies have legislative competence in devolved matters. However, under s.28(7) Scotland Act 1998, the UK Parliament retains the power to legislate for Scotland — parliamentary sovereignty is preserved. The Sewel Convention (now s.2 Scotland Act 2016) provides that Westminster will 'not normally' legislate on devolved matters without consent.",
    "details": "R (Miller) v Secretary of State [2017]: the SC held (8-3) that the Sewel Convention is a political convention, not a legal rule — courts cannot enforce it. Acts of the devolved legislatures can be struck down if they exceed competence (AXA General Insurance v Lord Advocate [2011]). The devolution statutes are often regarded as 'constitutional statutes' that cannot be impliedly repealed.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-ouster-clauses",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "ouster clause",
      "judicial review",
      "rule of law",
      "Anisminic"
    ],
    "crossCutting": false,
    "front": "Can Parliament oust the jurisdiction of the courts to conduct judicial review?",
    "back": "In Anisminic v Foreign Compensation Commission [1969], the House of Lords held that a statutory clause stating a decision 'shall not be called in question in any court of law' did not prevent judicial review of a decision made in error of law — because a decision made in error of law is a nullity, not a 'decision' within the meaning of the ouster clause. The rule of law requires that the courts have the final say on legality.",
    "details": "R (Privacy International) v Investigatory Powers Tribunal [2019]: the SC (by majority) held that even a carefully worded ouster clause could not prevent judicial review for errors of law. Lord Carnwath: parliamentary sovereignty and the rule of law are both fundamental — the courts will interpret ouster clauses restrictively. However, time-limited ouster clauses (e.g. 'within 6 weeks') are generally effective.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-constitutional-conventions",
    "type": "distinction",
    "module": "Public Law",
    "tags": [
      "conventions",
      "rules",
      "non-legal",
      "constitutional"
    ],
    "crossCutting": false,
    "front": "Distinguish constitutional conventions from legal rules.",
    "back": "Constitutional conventions are non-legal rules of political practice that are considered binding by those who operate the constitution, but are not enforceable by the courts. Legal rules are enforced by courts and carry legal sanctions. Examples of conventions: the monarch assents to Bills, ministers are responsible to Parliament, the Sewel Convention. They exist because the formal legal rules alone cannot describe how the constitution actually works.",
    "details": "AG v Jonathan Cape [1976]: the court acknowledged the convention of collective ministerial responsibility but held it could not enforce it directly. R (Miller) v Secretary of State [2017]: the Sewel Convention was held to be a convention, not justiciable law. Conventions can crystallise into law (e.g. the Parliament Acts). Dicey: conventions are observed because breach would lead to a breach of the law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-delegated-legislation",
    "type": "principle",
    "module": "Public Law",
    "tags": [
      "delegated legislation",
      "statutory instruments",
      "ultra vires",
      "scrutiny"
    ],
    "crossCutting": false,
    "front": "What is delegated legislation and how is it controlled?",
    "back": "Delegated (or secondary) legislation is law made by a body other than Parliament under authority granted by an Act of Parliament (the 'parent' or 'enabling' Act). Common forms include statutory instruments and Orders in Council. Controls: (1) Parliamentary — affirmative and negative resolution procedures, Joint Committee on Statutory Instruments. (2) Judicial — courts can declare delegated legislation ultra vires if it exceeds the scope of the enabling Act or fails to follow prescribed procedures.",
    "details": "R v Secretary of State for Social Security, ex p Joint Council for the Welfare of Immigrants [1997] — regulations removing benefits from asylum seekers were ultra vires because they rendered the statutory right to claim asylum nugatory. Delegated legislation can also be challenged on grounds of unreasonableness (Kruse v Johnson [1898]) or incompatibility with Convention rights under the HRA (s.3 interpretation or s.4 declaration).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-entick-carrington",
    "type": "case",
    "module": "Public Law",
    "tags": ["rule of law", "executive power", "Entick v Carrington", "legality"],
    "crossCutting": false,
    "front": "Entick v Carrington (1765) — what foundational principle did it establish about executive power?",
    "back": "The state and its officials may only act with positive legal authority. Where no statute or common law rule authorises an action affecting private rights, the action is unlawful — even if undertaken by ministers of state. Lord Camden CJ: 'If it is law, it will be found in our books. If it is not to be found there, it is not law.'",
    "details": "King's messengers broke into Entick's house and seized his papers on a Secretary of State's warrant. Entick sued in trespass. Held: unlawful — no legal authority existed for the warrant. Bedrock of the legality principle. Confirmed in R v Somerset CC, ex p Fewings [1995] and M v Home Office [1994].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-ridge-baldwin",
    "type": "case",
    "module": "Public Law",
    "tags": ["natural justice", "audi alteram partem", "Ridge v Baldwin", "procedural fairness"],
    "crossCutting": false,
    "front": "Ridge v Baldwin [1964] — what did the House of Lords decide about natural justice and administrative decisions?",
    "back": "The rules of natural justice — in particular the right to be heard (audi alteram partem) — apply not only to judicial and quasi-judicial decisions but also to administrative decisions affecting a person's rights. The HL rejected the narrow view that natural justice was confined to judicial-style proceedings.",
    "details": "Lord Reid. A Chief Constable was dismissed without notice of charges or opportunity to be heard. HL: dismissal void. This revived the audi alteram partem rule after decades of decline and opened the door to the broader 'duty to act fairly' (Re HK [1967]) culminating in the CCSU 'procedural impropriety' head.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-padfield",
    "type": "case",
    "module": "Public Law",
    "tags": ["improper purposes", "Padfield", "discretion", "illegality"],
    "crossCutting": false,
    "front": "Padfield v Minister of Agriculture [1968] — what did it establish about the exercise of ministerial discretion?",
    "back": "A minister exercising statutory discretion must do so to promote the policy and objects of the Act. A court can intervene if the minister frustrates those objects, refuses to act without good reason, or exercises discretion for an improper purpose. An apparently unfettered discretion is never truly unfettered.",
    "details": "Lord Reid. The Minister refused to refer a milk pricing complaint to a committee, fearing political embarrassment. HL: unlawful. Cornerstone of the 'illegality' ground (CCSU). Also established that reasons given can be examined, and absent reasons the court may infer bad reasons from the circumstances.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-anisminic",
    "type": "case",
    "module": "Public Law",
    "tags": ["ouster clauses", "jurisdictional error", "Anisminic", "errors of law"],
    "crossCutting": true,
    "front": "Anisminic Ltd v Foreign Compensation Commission [1969] — how did it transform the law on ouster clauses and errors of law?",
    "back": "Any error of law by a statutory tribunal goes to its jurisdiction and renders its decision a 'nullity'. An ouster clause protecting a 'determination' cannot protect a decision vitiated by error of law, because such a decision is not a real determination at all. The distinction between jurisdictional and non-jurisdictional errors of law was effectively abolished.",
    "details": "Lord Reid. The FCA 1950 stated that any 'determination' of the Commission 'shall not be called in question in any court of law'. The Commission misconstrued the governing Order. HL: the misconstruction was a nullity, so the ouster clause did not bite. Reinforced in R (Privacy International) v IPT [2019] — Parliament must use the most clear and explicit words to oust JR.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-ccsu-gchq",
    "type": "case",
    "module": "Public Law",
    "tags": ["CCSU", "GCHQ", "grounds of JR", "prerogative", "Lord Diplock"],
    "crossCutting": false,
    "front": "Council of Civil Service Unions v Minister for the Civil Service [1985] (GCHQ) — what two things did Lord Diplock set out?",
    "back": "(1) The three heads of judicial review: illegality, irrationality, and procedural impropriety (with proportionality as a possible future head). (2) The exercise of the royal prerogative is in principle subject to judicial review — reviewability depends on the subject matter of the power, not on whether its source is statute or prerogative.",
    "details": "Trade union membership was withdrawn at GCHQ by Order in Council without consultation. The unions had a legitimate expectation of consultation. HL: normally reviewable on procedural impropriety grounds, but national security justified the lack of consultation here. The case is the modern foundation of JR grounds and of prerogative reviewability (prior to CCSU, prerogative was thought immune: Chandler v DPP [1964]).",
    "related": ["4", "publaw-wednesbury-unreasonableness"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-wednesbury-case",
    "type": "case",
    "module": "Public Law",
    "tags": ["Wednesbury", "unreasonableness", "Associated Provincial Picture Houses", "Lord Greene"],
    "crossCutting": false,
    "front": "Associated Provincial Picture Houses Ltd v Wednesbury Corporation [1948] — state the Wednesbury formula and explain why the threshold is set so high.",
    "back": "Lord Greene MR: a court may quash an administrative decision as unreasonable only if it is 'so unreasonable that no reasonable authority could ever have come to it'. The deliberately high threshold exists because the court is not substituting its own view — it polices only the outer limits of rationality.",
    "details": "A local authority licensed a Sunday cinema on condition no child under 15 was admitted. The cinema challenged the condition. CA: the condition was not so unreasonable as to be struck down. Lord Greene also identified irrelevant considerations and improper purposes as separate grounds. 'Wednesbury unreasonableness' was reframed as 'irrationality' by Lord Diplock in CCSU. Where fundamental rights are at stake, 'anxious scrutiny' applies (ex p Smith [1996]); proportionality now often replaces Wednesbury in HRA cases.",
    "related": ["publaw-wednesbury-unreasonableness", "4"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-factortame",
    "type": "case",
    "module": "Public Law",
    "tags": ["Factortame", "EU law", "parliamentary sovereignty", "supremacy"],
    "crossCutting": false,
    "front": "R v Secretary of State for Transport, ex p Factortame (No 2) [1991] — what did it decide about Acts of Parliament and EU law?",
    "back": "National courts must disapply Acts of Parliament that conflict with directly effective EU law, and must grant interim injunctions against the Crown to protect EU rights. During UK membership of the EU, a later Act could not prevail over EU law unless Parliament expressly said so. This appeared to qualify traditional parliamentary sovereignty.",
    "details": "The Merchant Shipping Act 1988 restricted fishing vessel registration to British-owned vessels, conflicting with the Treaty of Rome. HL: the Act had to be disapplied. Academic debate: revolution in sovereignty (Wade) or self-imposed limitation (Craig)? Post-Brexit (EU Withdrawal Agreement Act 2020), retained EU law no longer has automatic supremacy. Factortame remains historically important as a marker of sovereignty's limits during EU membership.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-miller-1",
    "type": "case",
    "module": "Public Law",
    "tags": ["Miller 1", "Article 50", "prerogative", "Brexit", "statutory rights"],
    "crossCutting": false,
    "front": "R (Miller) v Secretary of State for Exiting the EU [2017] — what principle did the Supreme Court apply to Article 50 notification?",
    "back": "The Crown cannot use prerogative powers to take away rights conferred by an Act of Parliament. Notification under Article 50 TEU would inevitably remove rights conferred by EU membership under the European Communities Act 1972, so notification required parliamentary authorisation by primary legislation.",
    "details": "UKSC 8-3. The government argued triggering Article 50 was a treaty-making act within prerogative. Held: the ECA 1972 created rights that would be lost on withdrawal, and the executive cannot frustrate rights granted by statute (De Keyser's Royal Hotel [1920]). Parliament responded with the EU (Notification of Withdrawal) Act 2017. Distinguish Miller (No 2) [2019] (prorogation).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-ghaidan",
    "type": "case",
    "module": "Public Law",
    "tags": ["HRA", "s.3", "interpretation", "Ghaidan v Godin-Mendoza"],
    "crossCutting": false,
    "front": "Ghaidan v Godin-Mendoza [2004] — how far can courts go in 'reading down' legislation under HRA s.3?",
    "back": "Under HRA s.3, courts must read and give effect to legislation compatibly with Convention rights 'so far as it is possible to do so'. This may require departing from ordinary meaning, reading words in, or reading words down — provided the interpretation does not go 'against the grain' of the legislation or require the court to make policy choices reserved for Parliament.",
    "details": "Lord Nicholls, Lord Rodger. The Rent Act 1977 treated an unmarried opposite-sex partner 'as his or her wife or husband' for tenancy succession. HL (4-1): read this to include same-sex partners under Art 14 + Art 8 ECHR. A s.4 declaration of incompatibility is a 'measure of last resort'. Contrast Re S (Children) [2002] — s.3 cannot rewrite a statutory scheme fundamentally.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-daly",
    "type": "case",
    "module": "Public Law",
    "tags": ["proportionality", "Daly", "Wednesbury", "fundamental rights"],
    "crossCutting": false,
    "front": "R (Daly) v Secretary of State for the Home Department [2001] — how did it distinguish proportionality from Wednesbury review?",
    "back": "Proportionality is more structured and more intrusive than Wednesbury. The court asks: (1) is the objective sufficiently important? (2) is the measure rationally connected to it? (3) could a less intrusive measure achieve it? (4) has a fair balance been struck? The court weighs competing interests itself rather than merely asking whether the decision fell within a 'range of reasonable responses'.",
    "details": "Lord Steyn. A blanket prison policy required prisoners to be absent during cell searches, so legally privileged correspondence was read. HL: unlawful under common law and Art 8 ECHR. Lord Steyn's postscript explained proportionality is 'more precise and more sophisticated' than Wednesbury. Refined into the four-stage test in Bank Mellat v HM Treasury (No 2) [2013]. Daly bridges traditional JR and modern proportionality.",
    "related": ["publaw-wednesbury-unreasonableness"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-belmarsh",
    "type": "case",
    "module": "Public Law",
    "tags": ["Belmarsh", "HRA s.4", "declaration of incompatibility", "detention", "Art 5"],
    "crossCutting": false,
    "front": "A v Secretary of State for the Home Department [2004] (Belmarsh) — what did the HL decide about indefinite detention of foreign terror suspects?",
    "back": "Section 23 ATCSA 2001, permitting indefinite detention without trial of foreign nationals suspected of terrorism but not British nationals, was incompatible with Articles 5 and 14 ECHR. The discrimination was disproportionate — confining detention to foreigners was not rationally connected to the threat. A s.4 declaration of incompatibility was issued.",
    "details": "HL 8-1. Lord Hoffmann alone would have quashed the Art 5 derogation as not responding to a 'threat to the life of the nation'. Lord Bingham rejected the argument that national security matters are non-justiciable, reasserting the courts' constitutional duty to review compatibility. The regime was replaced by control orders (Prevention of Terrorism Act 2005). Leading example of a major s.4 declaration.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-thoburn",
    "type": "case",
    "module": "Public Law",
    "tags": ["constitutional statutes", "implied repeal", "Thoburn", "metric martyrs"],
    "crossCutting": false,
    "front": "Thoburn v Sunderland City Council [2002] — what is the distinction between 'ordinary' and 'constitutional' statutes?",
    "back": "Laws LJ held that some statutes are 'constitutional' — they condition the legal relationship between citizen and state in an overarching manner or enlarge/diminish fundamental constitutional rights. Constitutional statutes are not subject to implied repeal: they can only be repealed by express words or by words so specific that the inference of actual repeal is irresistible.",
    "details": "The 'metric martyrs' sold goods using imperial measures. They argued the ECA 1972 had been impliedly repealed. Laws LJ: the ECA 1972 is a constitutional statute. Examples: Magna Carta, Bill of Rights 1689, Act of Union 1707, HRA 1998, Scotland Act 1998. Recognised by the UKSC in HS2 [2014]. Adds nuance to parliamentary sovereignty without denying it.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-jackson",
    "type": "case",
    "module": "Public Law",
    "tags": ["Jackson", "Parliament Acts", "sovereignty", "rule of law"],
    "crossCutting": false,
    "front": "Jackson v Attorney General [2005] — what did the HL say about parliamentary sovereignty and the rule of law?",
    "back": "Ratio: The Hunting Act 2004, enacted under the Parliament Acts 1911/1949 without Lords consent, was valid. Obiter (Lords Steyn, Hope, Baroness Hale): parliamentary sovereignty is a common-law construct and could be qualified in extreme cases — e.g. if Parliament tried to abolish judicial review or the ordinary role of the courts. Lord Hope: sovereignty is 'no longer absolute'.",
    "details": "Lord Steyn: 'In exceptional circumstances involving an attempt to abolish judicial review … the court may have to consider whether this is a constitutional fundamental which even a sovereign Parliament cannot abolish.' These dicta have influenced later decisions (Privacy International [2019]) but have not been relied on to strike down legislation. Lord Bingham disagreed extra-judicially, reaffirming orthodox Dicey. Jackson symbolises the ongoing debate between orthodox and 'common law constitutionalist' views.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-pickin",
    "type": "case",
    "module": "Public Law",
    "tags": ["Pickin", "enrolled bill rule", "parliamentary procedure", "sovereignty"],
    "crossCutting": false,
    "front": "British Railways Board v Pickin [1974] — what is the 'enrolled bill rule'?",
    "back": "Once a Bill has received Royal Assent and is enrolled on the Parliament Roll, the courts will not inquire into the internal procedures by which it was passed — whether Parliament was misled, whether standing orders were followed, or whether procedural fraud occurred. The validity of an Act depends only on whether it has been duly enacted by the Queen in Parliament.",
    "details": "Lord Reid: 'The function of the court is to construe and apply the enactments of Parliament. The court has no concern with the manner in which Parliament or its officers carrying out its Standing Orders perform these functions.' Reinforces Article 9 of the Bill of Rights 1689. Distinguish examining whether an Act exists (permissible) from examining how it was passed (impermissible).",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "publaw-oreilly-mackman",
    "type": "case",
    "module": "Public Law",
    "tags": ["O'Reilly v Mackman", "procedural exclusivity", "public/private divide"],
    "crossCutting": false,
    "front": "O'Reilly v Mackman [1983] — what is the 'procedural exclusivity' rule and how has it been qualified?",
    "back": "Where a claimant asserts a purely public-law right against a public body, they must generally proceed by judicial review (now CPR Part 54) rather than by ordinary action. Lord Diplock justified this to protect public authorities from being sued out of time and without the safeguards of the JR procedure (permission, short time limit, discretionary remedies).",
    "details": "Prisoners challenged disciplinary decisions by ordinary writ after the JR time limit expired. HL: abuse of process. Significant qualifications since: collateral challenges in defence are permitted (Wandsworth v Winder [1985]; Boddington v BTP [1999]); the divide is not rigid where public and private rights are intertwined (Roy v Kensington FPC [1992]); the CPR has softened the distinction. Now treated as guidance rather than a strict rule.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
