// Auto-generated from cards.js split. Module: Tort
export const tortCards = [
  {
    "id": "2",
    "type": "case",
    "module": "Tort",
    "tags": [
      "negligence",
      "duty of care",
      "neighbour principle"
    ],
    "crossCutting": true,
    "front": "Donoghue v Stevenson [1932] AC 562 — reconstruct the ratio decidendi.",
    "back": "A manufacturer owes a duty of care to the ultimate consumer of their product where the product reaches the consumer without reasonable possibility of intermediate examination.",
    "details": "Lord Atkin's neighbour principle. Foundation of modern negligence law. Majority 3-2. Cross-cuts into Contract (privity boundary) and Consumer Law (product liability origins).",
    "related": [
      "tort-caparo-duty",
      "tort-hedley-byrne-misstatement",
      "contract-privity-crtpa1999"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "7",
    "type": "case",
    "module": "Tort",
    "tags": [
      "negligence",
      "causation",
      "but-for test"
    ],
    "crossCutting": false,
    "front": "Barnett v Chelsea & Kensington Hospital [1969] — key issue and outcome?",
    "back": "Causation in negligence. Doctor negligently refused to examine a patient who died of arsenic poisoning. Held: even with examination, he would have died — 'but for' test not satisfied. Breach established but no causal link.",
    "details": "Compare: Fairchild v Glenhaven (material contribution to risk); McGhee v NCB (material increase in risk).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-caparo-duty",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "duty of care",
      "caparo",
      "negligence",
      "three-part test"
    ],
    "crossCutting": false,
    "front": "What is the Caparo three-part test for establishing a duty of care in negligence?",
    "back": "The claimant must show: (1) the damage was foreseeable; (2) there was sufficient proximity between the parties; (3) it is fair, just and reasonable to impose a duty. All three limbs must be satisfied (Caparo Industries plc v Dickman [1990] 2 AC 605).",
    "details": "Caparo replaced the Anns two-stage test and remains the leading authority. Courts use it incrementally — new duty situations are recognised only by analogy with established categories. In Caparo itself the House of Lords held auditors owed no duty to individual shareholders when they relied on accounts to buy shares, because proximity and fairness were absent. The test is particularly relevant in cases involving pure economic loss and negligent misstatement.",
    "related": [
      "2",
      "tort-hedley-byrne-misstatement"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-breach-reasonable-person",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "breach",
      "negligence",
      "reasonable person",
      "objective standard",
      "bolton v stone"
    ],
    "crossCutting": false,
    "front": "How does the law determine whether a defendant has breached the standard of care in negligence?",
    "back": "The defendant is measured against the 'reasonable person' — an objective standard. The court weighs (i) probability of harm, (ii) potential severity, (iii) cost of precautions, and (iv) social utility of the activity. A small risk with disproportionate precaution cost may not constitute breach (Bolton v Stone [1951]).",
    "details": "In Bolton v Stone a cricket ball hit a pedestrian; the House of Lords held no breach because the risk was foreseeable but very low, and the cost of eliminating it entirely was unreasonably high. Contrast Paris v Stepney Borough Council [1951] where the known vulnerability of a one-eyed employee elevated the standard — the employer was liable for not providing goggles. The standard is fixed (not personalised), but context adjusts the outcome: professionals are judged against the reasonable professional in their field (Bolam v Friern [1957]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-fairchild-material-contribution",
    "type": "case",
    "module": "Tort",
    "tags": [
      "causation",
      "material contribution",
      "fairchild",
      "mesothelioma",
      "multiple defendants"
    ],
    "crossCutting": false,
    "front": "What principle did Fairchild v Glenhaven Funeral Services [2002] establish regarding causation in negligence?",
    "back": "Where a claimant cannot identify which of several defendant employers' negligent exposures to asbestos dust caused mesothelioma (due to scientific uncertainty), it is sufficient to show each defendant materially increased the risk of the disease. Each employer is jointly and severally liable.",
    "details": "Fairchild created a narrow exception to the 'but for' causation test where (a) the harm is indivisible, (b) each defendant acted wrongfully, and (c) scientific uncertainty makes it impossible to pinpoint the causative exposure. The Supreme Court in Barker v Corus [2006] modified this to proportionate liability, but Parliament reversed that by s3 Compensation Act 2006, reinstating full joint and several liability in mesothelioma cases. Compare McGhee v NCB [1972], an earlier case where material contribution to risk was accepted on similar policy grounds.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-remoteness-wagon-mound",
    "type": "case",
    "module": "Tort",
    "tags": [
      "remoteness",
      "wagon mound",
      "reasonable foreseeability",
      "type of harm"
    ],
    "crossCutting": false,
    "front": "What test for remoteness of damage was established in The Wagon Mound (No 1) [1961]?",
    "back": "A defendant is only liable for damage of a type that was reasonably foreseeable at the time of the negligent act. The precise manner of occurrence need not be foreseeable, but the kind of damage must be. Unforeseeable damage, however direct, is too remote.",
    "details": "The Privy Council overruled the directness test from Re Polemis [1921]. Oil spilled from a ship ignited cotton waste in Sydney Harbour and burnt the plaintiff's wharf. The defendants were not liable because fire damage from oil floating on water was not reasonably foreseeable (only oil fouling was foreseeable). The 'type of damage' test has nuance: the 'thin skull' (eggshell skull) rule provides that once a type of damage is foreseeable, the defendant takes the victim as they find them, so an unforeseeably severe reaction does not break causation (Smith v Leech Brain [1962]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-psychiatric-injury-primary-secondary",
    "type": "distinction",
    "module": "Tort",
    "tags": [
      "psychiatric injury",
      "nervous shock",
      "primary victim",
      "secondary victim",
      "page v smith",
      "alcock"
    ],
    "crossCutting": false,
    "front": "Distinguish between primary and secondary victims in psychiatric injury claims in tort.",
    "back": "A primary victim is directly imperilled or in the zone of physical danger (Page v Smith [1996] — foreseeability of physical injury suffices). A secondary victim witnesses injury to another and must satisfy four Alcock control mechanisms: (i) close tie of love and affection to the primary victim; (ii) proximity in time and space; (iii) perception with own unaided senses; (iv) medically recognised psychiatric illness.",
    "details": "Page v Smith: claimant in a minor car accident suffered no physical injury but experienced chronic fatigue syndrome. HL held that because physical injury to him was foreseeable, psychiatric injury was actionable without the need for foreseeability of psychiatric harm specifically. Alcock v Chief Constable of South Yorkshire [1992] arose from Hillsborough: relatives watching on TV or who arrived after the disaster failed all control mechanisms. The distinction is critical — primary victims face fewer hurdles. White v Chief Constable of South Yorkshire [1999] held that police officers at Hillsborough were secondary victims (not primary) because they were not in personal danger.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-rylands-fletcher",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "rylands v fletcher",
      "strict liability",
      "non-natural use",
      "escape"
    ],
    "crossCutting": false,
    "front": "State the rule in Rylands v Fletcher and its requirements.",
    "back": "A person who for their own purposes brings onto their land something likely to do mischief if it escapes must keep it at their peril. If they fail to do so they are prima facie answerable for all the direct consequences of its escape (Blackburn J, confirmed HL 1868). Requirements: accumulation, non-natural use of land, escape, and foreseeable damage.",
    "details": "The defendant in Rylands v Fletcher built a reservoir; contractors negligently failed to block old mine shafts; water flooded the plaintiff's mine. The House of Lords added 'non-natural use' as a qualifying element. Cambridge Water Co v Eastern Counties Leather [1994] confirmed the requirement of foreseeability of damage of the relevant type. The tort is essentially dormant in England & Wales after Transco v Stockport MBC [2003], where the House of Lords declined to abolish it but significantly restricted 'non-natural use' — ordinary domestic or commercial use of land does not qualify.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-vicarious-liability",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "vicarious liability",
      "course of employment",
      "employer",
      "frolic"
    ],
    "crossCutting": false,
    "front": "When is an employer vicariously liable for the torts of an employee?",
    "back": "An employer is vicariously liable for an employee's tort if (1) an employment relationship (or akin to employment) exists, and (2) the tort was committed in the course of employment — meaning there is a sufficient close connection between the employment and the wrongful act (Lister v Hesley Hall [2001]; Various Claimants v Catholic Child Welfare Society [2012]).",
    "details": "The old 'Salmond test' asked whether the act was authorised or a wrongful mode of a lawful act. The close connection test, developed for intentional wrongdoing (sexual abuse by a warden), is now the main approach. Frolic of one's own (going completely off piste for personal purposes) breaks the employment connection — but a detour for mixed purposes may not (Rose v Plenty [1976]: milkman letting a child on his float was still acting in course of employment). The two-stage test in Various Claimants includes: (i) does the relationship make it just to impose liability, and (ii) is there a sufficient connection between the relationship and the tort?",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "cross-damages-compensatory",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "damages",
      "compensatory",
      "expectation",
      "reliance",
      "restitution",
      "contract",
      "tort"
    ],
    "crossCutting": true,
    "front": "How do the principles for compensatory damages differ between contract and tort?",
    "back": "Contract damages: aim to put the claimant in the position they would have been in had the contract been performed (expectation/loss of bargain). Tort damages: aim to restore the claimant to the position before the tort (restitutio in integrum). Contract may also award reliance loss (wasted expenditure). Both require proof of causation, remoteness, and a duty to mitigate.",
    "details": "The remoteness rules also differ: contract — loss reasonably in the contemplation of the parties at the time of contracting (Hadley v Baxendale [1854] — two limbs); tort — reasonable foreseeability at the time of the tort (Wagon Mound). These can produce different outcomes: a loss that was not in the contemplation of the parties at contract-making may still be recoverable in tort if foreseeable. Punitive/exemplary damages are rare in contract (no English authority for them) but available in tort in Rookes v Barnard [1964] categories. Loss of amenity, pain and suffering are general damages in personal injury tort; contract claims for non-financial loss are narrower (Watts v Morrow [1991] — limited to physical inconvenience and distress in certain contracts).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-ola1957-visitor",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "occupiers liability",
      "OLA 1957",
      "lawful visitor",
      "common duty of care"
    ],
    "crossCutting": false,
    "front": "What duty does an occupier owe to lawful visitors under the Occupiers' Liability Act 1957?",
    "back": "Under s.2(2) OLA 1957, an occupier owes a 'common duty of care' to all lawful visitors — a duty to take such care as is reasonable in the circumstances to see that the visitor will be reasonably safe in using the premises for the purposes for which they are invited or permitted to be there.",
    "details": "Visitors include invitees, licensees, and those entering under a contract or right conferred by law. Under s.2(3), an occupier must be prepared for children to be less careful than adults; and under s.2(3)(b), may expect professionals (e.g. window cleaners) to guard against risks ordinarily incident to their trade. Warnings may discharge the duty only if sufficient to enable the visitor to be reasonably safe (s.2(4)(a)).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-ola1984-trespasser",
    "type": "distinction",
    "module": "Tort",
    "tags": [
      "occupiers liability",
      "OLA 1984",
      "trespasser",
      "non-visitor"
    ],
    "crossCutting": false,
    "front": "Distinguish the duty owed to trespassers (OLA 1984) from the duty to visitors (OLA 1957).",
    "back": "Under OLA 1984, the duty to non-visitors (trespassers) is more limited. It only arises if: (a) the occupier is aware of the danger or has reasonable grounds to believe it exists, (b) the occupier knows or has reasonable grounds to believe the non-visitor is in the vicinity of the danger, and (c) the risk is one against which the occupier may reasonably be expected to offer some protection. The 1957 Act imposes a broader common duty of care on the assumption the visitor is welcome.",
    "details": "S.1(3) OLA 1984. Compare Tomlinson v Congleton BC [2004] where the HL held the council owed no duty under OLA 1984 to an adult trespasser who dived into a shallow lake — the risk was obvious and the claimant had freely chosen to accept it. Under OLA 1984, the duty cannot be discharged by warning alone (cf. OLA 1957 s.2(4)).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-nuisance-private",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "private nuisance",
      "unreasonable use",
      "land"
    ],
    "crossCutting": false,
    "front": "What are the elements of the tort of private nuisance?",
    "back": "Private nuisance is an unlawful interference with a person's use or enjoyment of land, or some right over or in connection with it. The claimant must show: (1) they have a proprietary interest in the land (Hunter v Canary Wharf [1997]), (2) the interference was indirect and continuous, and (3) the interference was unreasonable, assessed by balancing the competing interests of the parties.",
    "details": "Factors for unreasonableness: locality (Sturges v Bridgman [1879]), duration and frequency, sensitivity of the claimant (Robinson v Kilvert [1889]), malice of the defendant (Hollywood Silver Fox Farm v Emmett [1936]). Remedies include injunction and/or damages. A landlord can be liable if they authorised the nuisance (Tetley v Chitty [1986]).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-rylands-v-fletcher",
    "type": "case",
    "module": "Tort",
    "tags": [
      "rylands v fletcher",
      "strict liability",
      "non-natural use",
      "escape"
    ],
    "crossCutting": false,
    "front": "What is the rule in Rylands v Fletcher [1868] and how has it been modified?",
    "back": "A person who brings onto their land and accumulates anything likely to cause mischief if it escapes, must keep it in at their peril, and is prima facie liable for all damage that is the natural consequence of its escape. The defendant must have made a 'non-natural use' of the land. In Transco v Stockport MBC [2004], the House of Lords confirmed the tort survives but as a sub-species of nuisance.",
    "details": "Defences: act of God, act of a stranger, statutory authority, consent of the claimant, default of the claimant. Transco narrowed 'non-natural use' — ordinary domestic water supply is not non-natural. Cambridge Water v Eastern Counties Leather [1994] added a foreseeability of damage requirement.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-psychiatric-injury-primary",
    "type": "distinction",
    "module": "Tort",
    "tags": [
      "psychiatric injury",
      "nervous shock",
      "primary victim",
      "secondary victim"
    ],
    "crossCutting": false,
    "front": "Distinguish primary and secondary victims in psychiatric injury claims.",
    "back": "A primary victim is someone within the zone of physical danger caused by the defendant's negligence (Page v Smith [1996]) — foreseeability of physical injury suffices. A secondary victim witnesses injury to another and must satisfy the Alcock v Chief Constable of South Yorkshire [1992] control mechanisms: (1) close tie of love and affection, (2) proximity in time and space to the accident or its immediate aftermath, (3) perception through own unaided senses.",
    "details": "In Page v Smith, the HL held foreseeability of psychiatric injury is not required for primary victims. For secondary victims, the Alcock criteria remain restrictive — in Alcock itself, relatives who saw the Hillsborough disaster on TV failed on proximity. White v Chief Constable [1999]: police officers at Hillsborough were not primary victims as they were not in danger.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-pure-economic-loss",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "pure economic loss",
      "negligence",
      "exclusionary rule",
      "spartan steel"
    ],
    "crossCutting": false,
    "front": "Why is pure economic loss generally irrecoverable in the tort of negligence?",
    "back": "Pure economic loss — financial loss not consequential on physical injury or property damage — is generally irrecoverable because: (1) it raises indeterminate liability concerns ('floodgates'), (2) contract law is the appropriate mechanism for allocating economic risk, and (3) imposing tortious duties for pure economic loss would undermine contractual risk allocation.",
    "details": "Spartan Steel v Martin [1973]: lost profit on future melts (not in the furnace at the time) was irrecoverable as pure economic loss. Exceptions: negligent misstatement (Hedley Byrne v Heller [1964]) where there is a special relationship; assumption of responsibility (Henderson v Merrett Syndicates [1995]). Murphy v Brentwood [1991] overruled Anns — defective building damage is pure economic loss.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-hedley-byrne-misstatement",
    "type": "case",
    "module": "Tort",
    "tags": [
      "negligent misstatement",
      "hedley byrne",
      "special relationship",
      "assumption of responsibility"
    ],
    "crossCutting": true,
    "front": "What principle did Hedley Byrne & Co Ltd v Heller & Partners Ltd [1964] establish?",
    "back": "A duty of care can arise for negligent misstatements causing pure economic loss where there is a 'special relationship' between the parties. This exists where: the defendant possesses special skill/knowledge, the claimant reasonably relies on the statement, and the defendant knows or ought to know of that reliance. The claim failed on the facts because the defendant had included a disclaimer.",
    "details": "Extended by Caparo (auditors owe no duty to individual shareholders buying shares) and Henderson v Merrett Syndicates [1995] (assumption of responsibility test). The principle applies to professional advisers, bankers giving references, and similar situations. Cross-cuts with Contract Law (concurrent liability in tort and contract: Henderson).",
    "related": [
      "tort-caparo-duty",
      "2",
      "tort-product-liability-cpa"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-product-liability-cpa",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "product liability",
      "CPA 1987",
      "strict liability",
      "defective product"
    ],
    "crossCutting": true,
    "front": "What is the basis of liability under the Consumer Protection Act 1987 Part I?",
    "back": "The CPA 1987 imposes strict liability on producers for damage caused by defective products. A product is defective if its safety is not such as persons generally are entitled to expect (s.3). The producer, own-brander, or importer into the EU can be liable. No need to prove fault — only that the product was defective and caused the damage.",
    "details": "Defences include: the defect is attributable to compliance with legislation, the defendant did not supply the product, the 'development risks' defence (s.4(1)(e)) — the state of scientific knowledge at the time was such that the defect could not have been discovered. A v National Blood Authority [2001] — infected blood was defective. Cross-cuts with Commercial Law (sale of goods).",
    "related": [
      "2",
      "13"
    ],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-vicarious-liability-close-connection",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "vicarious liability",
      "employer",
      "course of employment",
      "close connection"
    ],
    "crossCutting": true,
    "front": "When is an employer vicariously liable for the torts of an employee?",
    "back": "An employer is vicariously liable when: (1) there is a relationship akin to employment (Various Claimants v Barclays Bank [2020]), and (2) the tort was committed in the 'course of employment' — there must be a sufficiently close connection between the employment and the wrongful act (Lister v Hesley Hall [2002]).",
    "details": "The 'close connection' test replaced the older Salmond test. In Mohamud v WM Morrison [2016], the Supreme Court held that an employee who attacked a customer at a petrol station was acting in the course of employment. Cox v Ministry of Justice [2016] extended vicarious liability to relationships 'akin to employment'. Cross-cuts with employment law.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-contributory-negligence",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "contributory negligence",
      "defence",
      "Law Reform Act 1945",
      "apportionment"
    ],
    "crossCutting": true,
    "front": "How does contributory negligence operate as a defence in tort?",
    "back": "Under the Law Reform (Contributory Negligence) Act 1945, where damage is partly the claimant's fault, damages are reduced to the extent the court thinks just and equitable having regard to the claimant's share in responsibility. It is a partial defence — it reduces rather than eliminates damages.",
    "details": "The claimant must fail to take reasonable care for their own safety and that failure must be causally connected to the damage. Seatbelt cases: Froom v Butcher [1976] — 25% reduction for not wearing a seatbelt where injuries would have been prevented, 15% where merely reduced. Applies across tort generally, not just negligence.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-defamation-elements",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "defamation",
      "libel",
      "slander",
      "reputation"
    ],
    "crossCutting": false,
    "front": "What must a claimant prove to establish defamation?",
    "back": "The claimant must show: (1) the statement was defamatory — it tends to lower the claimant in the estimation of right-thinking members of society; (2) it referred to the claimant; (3) it was published to a third party; and (4) under s.1 Defamation Act 2013, the statement caused or is likely to cause 'serious harm' to the claimant's reputation (for bodies trading for profit: serious financial loss).",
    "details": "Libel is in permanent form; slander is transitory. Key defences: truth (s.2 DA 2013), honest opinion (s.3), publication on a matter of public interest (s.4), and privilege (absolute and qualified). Reynolds privilege was replaced by s.4 DA 2013. The serious harm threshold in Lachaux v Independent Print [2019] requires actual serious harm, not merely a tendency.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-trespass-person",
    "type": "distinction",
    "module": "Tort",
    "tags": [
      "trespass to the person",
      "battery",
      "assault",
      "false imprisonment"
    ],
    "crossCutting": true,
    "front": "Distinguish the three forms of trespass to the person.",
    "back": "Battery: direct and intentional application of unlawful force to the claimant. Assault: an act causing the claimant to reasonably apprehend the immediate infliction of a battery. False imprisonment: the total restraint of the claimant's liberty without lawful justification, whether or not the claimant is aware of it at the time.",
    "details": "Battery requires no harm — any unwanted touching suffices (Collins v Wilcock [1984]). Assault requires reasonable apprehension of imminent contact — words alone may suffice (R v Ireland [1998] for criminal assault). False imprisonment: Meering v Grahame-White Aviation [1920] — knowledge of imprisonment is not required. Cross-cuts with Criminal Law (non-fatal offences).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-employers-liability",
    "type": "principle",
    "module": "Tort",
    "tags": [
      "employers liability",
      "non-delegable duty",
      "safe system of work"
    ],
    "crossCutting": false,
    "front": "What is the scope of an employer's common law duty to employees?",
    "back": "An employer owes a personal, non-delegable duty to provide: (1) competent fellow employees, (2) adequate plant and equipment, (3) a safe place of work, and (4) a safe system of work. The standard is that of a reasonable employer, and the duty is owed to each individual employee (Paris v Stepney BC [1951]).",
    "details": "Wilsons & Clyde Coal v English [1938] established the fourfold duty. The duty is non-delegable — the employer cannot escape liability by delegating to a competent independent contractor. Employer's Liability (Defective Equipment) Act 1969 makes the employer liable for defective equipment even if the defect is the manufacturer's fault.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-volenti-defence",
    "type": "application",
    "module": "Tort",
    "tags": [
      "volenti",
      "consent",
      "voluntary assumption of risk",
      "defence"
    ],
    "crossCutting": false,
    "front": "A spectator at an amateur rugby match is injured when a player tackles another player, who is propelled into the spectator. Can the organiser raise volenti fit non injuria?",
    "back": "Likely yes. By attending a contact sport, the spectator voluntarily assumes the risk of injuries arising from the ordinary conduct of the game. However, volenti only applies to inherent risks, not negligent organisation (e.g. inadequate barriers). The defence requires full knowledge of the nature and extent of the risk and voluntary acceptance of it.",
    "details": "Wooldridge v Sumner [1963] — spectator at a horse show could not recover for injuries from a horse going off course during competition, as the rider was not negligent. Volenti is a complete defence. Under s.149 Road Traffic Act 1988, volenti cannot be raised against a passenger in a motor vehicle. ICI v Shatwell [1965] — the defence succeeded where employees jointly decided to ignore safety rules.",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-novus-actus-chain",
    "type": "application",
    "module": "Tort",
    "tags": [
      "novus actus interveniens",
      "causation",
      "intervening act",
      "chain of causation"
    ],
    "crossCutting": true,
    "front": "D negligently injures C. At hospital, a doctor negligently performs surgery, worsening C's condition. Is D liable for the additional harm?",
    "back": "Generally yes. Medical treatment, even if negligent, does not normally break the chain of causation unless it is 'so independent of D's act and so potent in causing the damage that it eclipses D's wrongdoing' (Webb v Barclays Bank). The original tortfeasor takes the victim as they find them and must anticipate that medical treatment may follow.",
    "details": "In Robinson v Post Office [1974], a negligent employer was liable for an allergic reaction to an anti-tetanus injection given to treat the original injury. But in R v Jordan [1956] (criminal case), where the victim was virtually healed and then given treatment that was 'palpably wrong', the chain was broken. The threshold for breaking the chain by medical negligence is very high. Cross-cuts with Criminal Law (causation).",
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-bolam",
    "type": "case",
    "module": "Tort",
    "tags": ["Bolam", "professional negligence", "standard of care", "medical"],
    "crossCutting": false,
    "front": "Bolam v Friern Hospital Management Committee [1957] — what is the Bolam test for professional negligence?",
    "back": "A doctor is not negligent if they act in accordance with a practice accepted as proper by a responsible body of professional opinion, even if other professionals would take a different view. The defendant need not prove majority support — a 'responsible body', however small, suffices.",
    "details": "McNair J. The claimant suffered fractures during electro-convulsive therapy administered without relaxant drugs or restraints. Held: not negligent. The test applies broadly to skilled professions. Qualified by Bolitho [1998]: the court retains power to reject expert opinion that is not logically defensible.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-bolitho",
    "type": "case",
    "module": "Tort",
    "tags": ["Bolitho", "Bolam qualification", "logical basis", "medical negligence"],
    "crossCutting": false,
    "front": "Bolitho v City and Hackney Health Authority [1998] — how did it qualify the Bolam test?",
    "back": "The court is not bound to accept expert opinion merely because a body of professionals supports the practice. The opinion must have a 'logical basis': the judge must be satisfied the experts directed their minds to comparative risks and benefits and reached a defensible conclusion. In rare cases, a court can reject opinion not capable of withstanding logical analysis.",
    "details": "Lord Browne-Wilkinson. A child suffered brain damage when a doctor failed to attend and intubate. The defendant argued a responsible body would support non-intubation. HL: Bolam applies but the court can reject illogical expert evidence. In practice rarely invoked, but prevents Bolam becoming a rubber stamp.",
    "related": ["tort-bolam"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-nettleship-weston",
    "type": "case",
    "module": "Tort",
    "tags": ["standard of care", "objective", "learner driver", "Nettleship"],
    "crossCutting": false,
    "front": "Nettleship v Weston [1971] — what standard of care is expected of a learner driver?",
    "back": "The standard of care is objective and impersonal: a learner driver must meet the same standard as a reasonably competent driver. The law does not adjust the standard downward for inexperience. The test asks what a reasonable person in the defendant's position would have done, not what this particular defendant could have achieved.",
    "details": "Lord Denning MR. A driving instructor injured by a learner on her third lesson. CA: the learner was liable — the standard is that of the 'ordinary skilful driver'. Exceptions: children are judged by the standard of a reasonable child of the same age (Mullin v Richards [1998]). Professionals are held to the Bolam standard.",
    "related": ["tort-bolam"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-smith-leech-brain",
    "type": "case",
    "module": "Tort",
    "tags": ["eggshell skull", "thin skull", "Smith v Leech Brain", "remoteness"],
    "crossCutting": false,
    "front": "Smith v Leech Brain & Co Ltd [1962] — what is the 'eggshell skull' (thin skull) rule?",
    "back": "The defendant must take the claimant as they find them. If the type of injury is foreseeable, the defendant is liable for its full extent even if the severity is unforeseeable due to a pre-existing vulnerability. The Wagon Mound foreseeability test applies to the type of harm, not its extent.",
    "details": "Lord Parker CJ. A worker was burned on the lip by molten metal due to employer's negligence. The burn activated a pre-malignant cancer, and he died. Held: the burn (type) was foreseeable; the cancer (extent) need not have been. Applied in Robinson v Post Office [1974] and Page v Smith [1996].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-mcghee",
    "type": "case",
    "module": "Tort",
    "tags": ["causation", "material contribution", "McGhee", "but-for"],
    "crossCutting": false,
    "front": "McGhee v National Coal Board [1973] — what did it decide about causation where the but-for test cannot be satisfied?",
    "back": "Where the defendant's breach 'materially increased the risk' of the claimant's injury, and the injury occurred, the law may treat the material increase in risk as sufficient to establish causation, even though the claimant cannot prove on the balance of probabilities that the breach was the but-for cause.",
    "details": "The claimant developed dermatitis after working in brick kilns. The employer negligently failed to provide washing facilities. Medical evidence could not distinguish tortious from non-tortious exposure. HL: causation established. Later narrowed in Wilsher v Essex AHA [1988] (must identify a single noxious agent) then revived in Fairchild v Glenhaven [2002] for mesothelioma.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-wilsher",
    "type": "case",
    "module": "Tort",
    "tags": ["causation", "Wilsher", "multiple causes", "but-for"],
    "crossCutting": false,
    "front": "Wilsher v Essex Area Health Authority [1988] — how did it limit the McGhee approach to causation?",
    "back": "Where several qualitatively different agents could each have independently caused the injury, the claimant must still prove on the balance of probabilities that the defendant's specific breach was a cause. McGhee does not apply where there are multiple different risk factors — it is confined to single-agent exposure cases.",
    "details": "Lord Bridge. A premature baby received excess oxygen due to negligence and developed retrolental fibroplasia, but RLF has several possible causes unrelated to oxygen. HL: ordered retrial — the claimant had not proved excess oxygen caused the RLF. Wilsher draws a line: McGhee's material-increase-in-risk applies where tortious and non-tortious exposure are the same agent. Later reconciled with Fairchild [2002].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-cambridge-water",
    "type": "case",
    "module": "Tort",
    "tags": ["Rylands v Fletcher", "Cambridge Water", "foreseeability", "nuisance"],
    "crossCutting": false,
    "front": "Cambridge Water Co v Eastern Counties Leather plc [1994] — how did the HL modify Rylands v Fletcher?",
    "back": "Foreseeability of the type of damage is a prerequisite for liability under Rylands v Fletcher. The rule is not strict in the absolute sense — the defendant is only liable if damage of the relevant type was foreseeable at the time of the escape. The HL also confirmed Rylands v Fletcher is a sub-species of nuisance, not an independent tort.",
    "details": "Lord Goff. A tannery's organochlorine solvents seeped into the aquifer, contaminating a borehole 1.3 miles away. HL: no liability — groundwater contamination by those chemicals was not foreseeable at the relevant time. The decision imported the Wagon Mound foreseeability requirement into Rylands and doubted whether Rylands adds anything to nuisance. Also rejected a general strict liability principle for ultra-hazardous activities.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-hunter-canary-wharf",
    "type": "case",
    "module": "Tort",
    "tags": ["private nuisance", "standing", "Hunter", "proprietary interest"],
    "crossCutting": false,
    "front": "Hunter v Canary Wharf Ltd [1997] — who has standing to sue in private nuisance?",
    "back": "Only a person with a proprietary interest in the land (owner, tenant, or person with exclusive possession) can sue in private nuisance. A mere licensee, family member, or lodger without such an interest has no standing. Private nuisance protects interests in land, not personal comfort in the abstract.",
    "details": "HL. Residents near Canary Wharf Tower complained it interfered with TV reception. HL: (1) interference with TV by a building is not actionable nuisance (analogous to loss of a view); (2) only those with exclusive possession can sue. Overruled Khorasandjian v Bush [1993]. Lord Goff: nuisance is a tort to land.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-sturges-bridgman",
    "type": "case",
    "module": "Tort",
    "tags": ["nuisance", "locality", "coming to nuisance", "Sturges v Bridgman"],
    "crossCutting": false,
    "front": "Sturges v Bridgman (1879) — does 'coming to the nuisance' provide a defence?",
    "back": "Coming to the nuisance is not a defence: the fact that the defendant's activity pre-dated the claimant's arrival does not prevent the claimant from suing. Locality is relevant to nuisance by interference with amenity (but not to nuisance causing physical damage): what is reasonable depends on the character of the neighbourhood.",
    "details": "Thesiger LJ. A confectioner had used heavy pestles and mortars for over 20 years. A doctor then built a consulting room nearby and complained. CA: no defence. The locality principle means industrial noise may be reasonable in a factory district but not in a residential area. Physical damage cases are not subject to the locality test: St Helen's Smelting v Tipping [1865].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-lister-hesley-hall",
    "type": "case",
    "module": "Tort",
    "tags": ["vicarious liability", "close connection", "Lister", "sexual abuse"],
    "crossCutting": false,
    "front": "Lister v Hesley Hall Ltd [2002] — what 'close connection' test did the HL adopt for vicarious liability?",
    "back": "An employer is vicariously liable for an employee's tort if the tort was so closely connected with the employment that it would be fair and just to hold the employer liable. The question is the closeness of the connection between the nature of the employment and the tort, not whether the act was expressly or impliedly authorised.",
    "details": "Lord Steyn. A warden at a boarding school for vulnerable children sexually abused residents. HL: vicarious liability established — the role created the opportunity. Replaced the older Salmond formulation. Developed in Various Claimants v Catholic Child Welfare Society [2012] ('akin to employment') and Mohamud v WM Morrison Supermarkets [2016].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-dorset-yacht",
    "type": "case",
    "module": "Tort",
    "tags": ["duty of care", "omissions", "third parties", "Dorset Yacht", "Home Office"],
    "crossCutting": false,
    "front": "Dorset Yacht Co v Home Office [1970] — when does a public body owe a duty for the acts of third parties?",
    "back": "A duty of care may arise where a defendant has assumed responsibility for supervising a source of danger, and damage is a direct and foreseeable consequence of their negligent failure to exercise that control — even for the acts of third parties whom they were supervising.",
    "details": "Lord Reid. Borstal officers took boys to an island; the officers fell asleep and the boys escaped and damaged nearby yachts. HL (4-1): the Home Office was liable. First major extension of Donoghue to public authority liability. Anticipated the Anns two-stage test. Now read in light of the Caparo incremental approach.",
    "related": ["2", "tort-caparo-duty"],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-hill-west-yorkshire",
    "type": "case",
    "module": "Tort",
    "tags": ["police", "immunity", "Hill", "duty of care", "public policy"],
    "crossCutting": false,
    "front": "Hill v Chief Constable of West Yorkshire [1989] — why did the HL deny a duty of care against the police in crime investigation?",
    "back": "The police do not owe a duty of care to individual victims in the investigation and suppression of crime. Two reasons: (1) insufficient proximity — the victim was one of a large unidentifiable class; (2) public policy — imposing liability would lead to defensive policing and divert resources.",
    "details": "Lord Keith. The mother of the Yorkshire Ripper's last victim sued for negligent investigation. HL: no duty. Reaffirmed in Michael v CC South Wales [2015] (UKSC, 5-2). The ECtHR in Osman v UK [1998] criticised blanket immunity, but the HL/UKSC maintains that Hill involves no duty in the first place. An assumption of responsibility to a specific individual may create a duty: Swinney v CC Northumbria [1997].",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-page-v-smith",
    "type": "case",
    "module": "Tort",
    "tags": ["psychiatric injury", "primary victim", "Page v Smith", "eggshell skull"],
    "crossCutting": false,
    "front": "Page v Smith [1996] — what is the rule for primary victims claiming psychiatric injury?",
    "back": "A primary victim (one directly involved as a participant in the accident) need only show that personal injury of some kind was foreseeable. It is unnecessary to show that psychiatric injury specifically was foreseeable. The thin skull rule applies: if physical injury was foreseeable, liability extends to psychiatric injury actually suffered.",
    "details": "Lord Lloyd. The claimant was in a minor car collision; he suffered no physical injury but the accident triggered chronic fatigue syndrome. HL (3-2): liable. Contrast secondary victims (Alcock [1992]) who must satisfy proximity requirements. Page v Smith was doubted in Rothwell v Chemical & Insulating Co [2007] but remains good law.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  },
  {
    "id": "tort-alcock",
    "type": "case",
    "module": "Tort",
    "tags": ["psychiatric injury", "secondary victim", "Alcock", "Hillsborough", "proximity"],
    "crossCutting": false,
    "front": "Alcock v Chief Constable of South Yorkshire [1992] — what must a secondary victim prove to recover for psychiatric injury?",
    "back": "A secondary victim must prove: (1) a recognised psychiatric illness (not mere grief); (2) a close tie of love and affection with the primary victim (presumed for spouses, parents, children; otherwise must be proved); (3) proximity in time and space to the accident or its immediate aftermath; (4) perception with their own unaided senses (not via television or third-party report).",
    "details": "Lord Ackner. Claims arising from the Hillsborough disaster. Relatives who watched on TV or arrived hours later failed on proximity. 'Immediate aftermath' construed narrowly — McLoughlin v O'Brian [1983] (hospital within two hours) was at the outer limit. No duty to mere bystanders (McFarlane v EE Caledonia [1994]). The Alcock criteria have been criticised as arbitrary but remain the law.",
    "related": [],
    "easeFactor": 2.5,
    "interval": 0,
    "repetitions": 0,
    "nextReview": 0,
    "lastReview": 0
  }
];
